name: attrs
version: "25.4.0"
release: 1
description: Python classes without boilerplate
license: MIT
homepage: https://www.attrs.org/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://files.pythonhosted.org/packages/source/a/attrs/attrs-${version}.tar.gz
  sha256: 16d5969b87f0859ef33a48b35d55ac1be6e42ae49d5e853b597db70c35c57e11
dependencies:
  build:
  - hatch-fancy-pypi-readme
  - hatch-vcs
  host: []
  runtime: []
verify_paths:
  - /usr/lib/python3.14/site-packages/attr
