# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
"""InterGen safety classifier — command safety tier classification.

Ported from a prior internal AI assistant project.
Adapted for InterGenOS system context with stricter defaults.

Three tiers:
  AUTO    — read-only, no side effects, execute immediately
  CONFIRM — write operations, user must approve
  BLOCKED — destructive/dangerous, refused entirely
"""

from __future__ import annotations

import os
import re
import json
import functools
import logging
from pathlib import Path

from intergen.interfaces.types import SafetyTier
from intergen.reference import WRONG_PKG_MANAGERS

logger = logging.getLogger(__name__)

# Map an apt/dnf/pacman-style subcommand (or pacman flag) to the pkm verb, used
# by get_blocked_response to redirect a wrong-package-manager call to pkm.
_PKM_VERB = {
    "install": "install", "add": "install", "reinstall": "install",
    "remove": "remove", "purge": "remove", "uninstall": "remove",
    "erase": "remove", "autoremove": "remove",
    "search": "search", "show": "info", "info": "info",
    "list": "list", "update": "sync", "upgrade": "upgrade",
    "-s": "install", "-r": "remove", "-ss": "search", "-q": "list",  # pacman-style
}

# ── iproute2-netlink family (unavailable in the hardened daemon) ──
#
# The daemon's hardened unit denies AF_NETLINK via RestrictAddressFamilies
# (F-038, ratified — see state_cache.py / router.py). Every iproute2 tool below
# opens an AF_NETLINK socket the instant it runs, so executing one in the
# run_command child SIGSYS-coredumps rather than returning data. These commands
# are NOT dangerous — they are simply unavailable in the sandbox — but a silent
# coredump is worse than a clear refusal. classify_command routes the whole
# family to BLOCKED and get_blocked_response redirects to a netlink-free source
# (/sys/class/net) or the user's own terminal — the same shape as the L2
# wrong-package-manager redirect. (net-tools `ifconfig`/`netstat` are NOT here:
# they read /proc + AF_INET ioctl, not netlink, so they run fine and stay AUTO.)
_NETLINK_COMMANDS = frozenset({
    "ip", "ss", "bridge", "tc", "nstat", "rtmon", "genl", "devlink",
})

# ── Tier 1: AUTO (read-only, safe to execute without confirmation) ──

_AUTO_COMMANDS_TWO_WORD = frozenset({
    # git status/remote/stash-list do not default-paginate, so they carry no
    # pager shell-escape and stay AUTO. diff/branch/tag DO default-paginate and
    # are handled by the paginating-git guard below (AUTO only non-interactive).
    "git status", "git remote", "git stash list",
    "systemctl is-active", "systemctl is-enabled",
    "systemctl list-units", "systemctl list-timers",
    # systemd-analyze read-only subcommands (boot timing / diagnostics). The
    # writing forms (set-log-level/set-log-target) are deliberately absent and
    # stay CONFIRM.
    "systemd-analyze time", "systemd-analyze blame",
    "systemd-analyze critical-chain",
    "pip list", "pip show", "pip freeze",
    "pkm list", "pkm search", "pkm info", "pkm provides",
    "pkm verify", "pkm depends",
    "docker ps", "docker images", "docker logs",
    "apt list",
    "npm list",
    # "ip addr"/"ip route"/"ip link" are NOT here: `ip` opens an AF_NETLINK
    # socket the hardened daemon denies (F-038), so the whole `ip` family is
    # routed to the netlink redirect below, not auto-run into a SIGSYS coredump.
})

_AUTO_COMMANDS_SINGLE = frozenset({
    # file inspection
    "cat", "head", "tail", "wc", "file", "stat", "md5sum",
    "sha256sum", "readlink", "realpath", "basename", "dirname",
    # search
    "grep", "rg", "find", "locate", "which", "whereis", "type",
    # text-stream filters (read-only: read stdin/files, write stdout). Same AUTO
    # rationale as grep/find — a read-only pipeline like `du | sort | head` must
    # auto-run, not gate behind a needless confirm. (A write-form such as
    # `sort -o FILE` is out of reach under the lockdown, where run_command's
    # commands are code-generated by the deterministic selector, never free-form
    # — the same architectural control that already makes `find` AUTO despite
    # its -delete/-exec forms.)
    "sort", "uniq", "cut",
    # listing
    "ls", "tree", "du", "df", "lsof",
    # system info
    "ps", "free", "uptime", "uname", "lscpu", "lsblk",
    "lsusb", "lspci", "hostname", "whoami", "id", "nproc", "arch",
    "lsb_release", "hostnamectl", "timedatectl",
    # network info (read-only). NOTE: `ip` and `ss` are deliberately absent —
    # they require AF_NETLINK (denied under F-038) and are handled by the
    # netlink redirect. `ifconfig`/`netstat` stay (they use /proc + AF_INET
    # ioctl, not netlink, so they run fine in the hardened daemon).
    "ping", "dig", "nslookup", "host", "netstat", "traceroute",
    "ifconfig",
    # package info
    "dpkg", "rpm",
    # printing (read-only queries — lpstat shows printers/jobs/status, lpq the
    # queue. lpoptions/lpadmin can WRITE config so they stay CONFIRM.)
    "lpstat", "lpq",
    # logs
    "dmesg",
    # misc read. NB: `env` is NOT here — it is classified by its WRAPPED command
    # (see the env handler in classify_command); bare env (print/set environment)
    # resolves to AUTO there. `printenv` (always read-only) stays AUTO.
    "date", "cal", "printenv", "echo", "printf", "test",
    "true", "false", "pwd", "groups",
})

# ── Interactive-pager exec-vector class (guards live in classify_command) ──
# less/more/most (and top/htop) are interactive programs: on a controlling
# terminal one can `!cmd` (or less `v`->$EDITOR) to spawn a child shell that
# classify_command never sees. AUTO only as a pipeline data-sink (`du | less`,
# _piped); a BARE invocation (`less FILE`, `top`) is CONFIRM. Latent under the
# dispatch lockdown (run_command's child has no controlling terminal); live the
# moment dispatch widens to a native-model path or a PTY caller. Same posture as
# the sort/find/env write-form guards. The curated system-state commands already
# use ps/--no-pager forms, so this does not regress their AUTO.
_PAGER_COMMANDS = frozenset({"less", "more", "most", "top", "htop"})
# Tools that paginate through $PAGER by default (same escape class): AUTO only
# when non-interactive (piped, or explicit --no-pager/--no-paginate); bare
# interactive form is CONFIRM. git diff/branch/tag default-paginate exactly like
# log/show, so they are in the guard too (reviewer decision: close the twin -- a
# paginating git subcommand left AUTO carries the same !cmd / v->$EDITOR escape).
# blame/shortlog/config-list also paginate but are NOT auto today (unknown git
# subcommands default to CONFIRM), so they stay conservative -- adding them here
# would only widen AUTO, the opposite of this guard's tightening intent.
_PAGINATING_SINGLE = frozenset({"journalctl"})
_PAGINATING_GIT_SUBCMDS = frozenset({"log", "show", "diff", "branch", "tag"})
_PAGINATING_TWO_WORD = frozenset({"systemctl status"})

# ── Tier 2: CONFIRM (write operations, require user approval) ──

_CONFIRM_COMMANDS_TWO_WORD = frozenset({
    "git add", "git commit", "git push", "git pull", "git merge",
    "git stash", "git stash pop", "git stash drop",
    "git checkout", "git switch", "git rebase",
    "git reset", "git clean", "git revert",
    "systemctl start", "systemctl stop", "systemctl restart",
    "systemctl enable", "systemctl disable", "systemctl reload",
    "pkm install", "pkm remove",
    "pip install", "pip uninstall",
    "apt install", "apt remove", "apt upgrade", "apt purge",
})

_CONFIRM_COMMANDS_SINGLE = frozenset({
    "cp", "mv", "mkdir", "touch", "ln", "install",
    "chmod", "chown", "chgrp",
    "tee", "truncate",
    "rm", "rmdir", "unlink",
    "kill", "killall", "pkill",
    "wget", "curl",
    "tar", "zip", "unzip", "gzip", "bzip2", "xz",
    "sed", "awk",
    "make", "cmake", "gcc", "g++", "rustc", "cargo",
    "python3", "python", "node",
})

# ── Tier 3: BLOCKED (dangerous, refused entirely) ──

_BLOCKED_COMMANDS = frozenset({
    # privilege escalation / identity change (all root-gated exec helpers that run
    # an arbitrary inner as another user -- peers of sudo. pkexec is the polkit
    # escalation helper; runuser is su without a password and also carries a `-c`
    # command-string form. Refused as base commands, never softened by wrapping.)
    "sudo", "su", "doas", "pkexec", "runuser",
    # destructive disk operations
    "dd", "mkfs", "fdisk", "parted", "gdisk", "sgdisk",
    "wipefs", "blkdiscard", "shred",
    # system control
    "shutdown", "reboot", "poweroff", "halt", "init",
    # code execution
    "eval", "exec",
    # user management
    "passwd", "useradd", "userdel", "usermod", "groupadd", "groupdel",
    # network control
    "iptables", "ip6tables", "nft", "nftables", "ufw",
    # mount
    "mount", "umount",
    # cron
    "crontab",
    # dangerous misc
    "chroot", "nsenter", "unshare",
})

# A real block device, any family — destructive when written to by a redirect
# or an of= target: sd (SCSI/SATA), nvme, vd (virtio — every VM, including our
# own test beds), mmcblk (SD/eMMC), xvd (Xen), loop, dm- (device-mapper), md
# (md-raid). Deliberately NOT char devices (/dev/null, /dev/zero, /dev/tty,
# /dev/stdout, /dev/random) so ordinary redirects classify normally. Code review
# of 6c079275 surfaced that the prior sd/nvme-only rule let a redirect-wipe to a
# virtio/eMMC disk slip to CONFIRM instead of BLOCKED.
# Also /dev/disk/by-id|by-uuid|by-path|by-label — symlinks that all resolve to a
# real block device, so a redirect there is a redirect to the disk. Nothing
# legitimate redirects into /dev/disk/.
# And /dev/mapper/<name> — the device-mapper named volumes: the UNLOCKED LUKS
# root (`/dev/mapper/cryptroot`) and the dm-verity root (`/dev/mapper/igos-root`),
# plus the libdevmapper control node. `dm-` above only matches the anonymous
# `/dev/dm-N` alias; the security review found a redirect onto the named mapping
# (`> /dev/mapper/cryptroot`) — the plaintext view of the encrypted root — read as
# safe. Nothing legitimate redirects into /dev/mapper/, so the whole dir is blocked.
_BLOCK_DEVICE = r"/dev/(?:sd|nvme|vd|mmcblk|xvd|loop|dm-|md|mapper/|disk/)"
_BLOCK_DEVICE_REDIRECT = re.compile(r">\s*" + _BLOCK_DEVICE)

_BLOCKED_PATTERNS = [
    re.compile(r"\|\s*bash"),           # pipe to bash
    re.compile(r"\|\s*sh\b"),           # pipe to sh
    re.compile(r"\$\("),                # command substitution
    re.compile(r"`[^`]+`"),             # backtick execution
    _BLOCK_DEVICE_REDIRECT,             # redirect-wipe to any block device family
    re.compile(r">\s*/etc/"),           # write to system config
    re.compile(r">\s*/proc/"),          # write to proc
    re.compile(r">\s*/sys/"),           # write to sys
    re.compile(r"\brm\s+(-\S+\s+)*/\s*$"),  # rm [flags] /  (delete root itself)
    # Recursive-force rm at ANY path is BLOCKED (restores + widens the prior
    # run_command denylist, which blanket-blocked `rm -rf <anypath>`; my first
    # AI-4 pass narrowed this to `rm -rf /` only, a regression WC caught). A
    # recursive force delete is unrecoverable and must not auto/confirm-run from
    # the shell tool regardless of target. One pattern, two lookaheads: BLOCK
    # when an rm invocation carries BOTH a recursive flag (-r/-R, combined like
    # -rf/-Rf, or --recursive) AND a force flag (-f, combined, or --force), in
    # any order, combined or separate. rm without both (rm file, rm -f file,
    # rm -r dir) stays CONFIRM — this matches the old denylist's superset, no
    # over-block.
    # F4 correctness fix (2026-07-02): each lookahead requires the flag to be a
    # WHITESPACE-DELIMITED token (`.*\s(?:-…|--…)`), so a hyphenated FILENAME no
    # longer false-matches — the prior `.*(?:-[a-zA-Z]*[rR]…)` matched a dash
    # anywhere, so `rm my-report-final.txt` read `-report`/`-final` as flags and
    # was HARD-blocked. `\brm\b` (not `\brm\s+`) leaves the post-rm whitespace
    # unconsumed so the lookahead's `\s` can see the first real flag token; the
    # flag-letter alt keeps NO trailing `\b` so combined flags (`-rf`) still match.
    re.compile(
        r"\brm\b"
        r"(?=.*\s(?:-[a-zA-Z]*[rR]|--recursive))"
        r"(?=.*\s(?:-[a-zA-Z]*[fF]|--force))"
    ),
    re.compile(r":\(\)\{"),             # fork bomb
    re.compile(r">\s*/boot/"),          # write to boot partition
    re.compile(r"mkswap\s"),            # swap creation
    re.compile(r"swapon\s"),            # swap activation
    # AI-4 — absorbed from run_command's inline denylist so this is the one
    # strong classifier (a strict superset of every prior per-tool check):
    re.compile(r"\bmkfs\b"),                                   # mkfs.ext4 etc (suffix forms)
    re.compile(r"\bchmod\s+.*-R\s+777\s+/\s*$"),              # chmod -R 777 /
    re.compile(r"\bchown\s+.*-R\s+.*\s+/\s*$"),               # chown -R ... /
    re.compile(                                                # mask/disable a critical unit
        r"\bsystemctl\s+(mask|disable)\s+"
        r"(NetworkManager|dbus|systemd|polkit|ssh|sshd)"
    ),
]


# Shell operators that chain/compose multiple commands. A compound command is
# classified by its MOST dangerous SEGMENT, so a read-only prefix can never
# launder a destructive suffix (e.g. `echo yes | mkfs.ext4 /dev/sda1`). This must
# be a SUPERSET of what the shell actually honors — the security review found the
# old `| && ;` set under-modeled the shell, so a benign leading command could hide
# a destructive trailing one behind a separator the classifier did not split on.
# Full set: pipe `|`, or-list `||`, and-list `&&`, sequence `;`, background `&`,
# pipe-both `|&`, and a newline/carriage-return. Longest operators first so `||` /
# `|&` / `&&` win over their single-char prefixes. The background `&` alternative
# excludes redirect forms (`2>&1`, `>&2`, `&>file`) via look-around so a common
# fd-redirect is not mis-split. Kept in a CAPTURING group so re.split returns the
# operators too — that lets us tell a real PIPE (`|`/`|&`, which makes an adjacent
# pager a non-interactive data-sink) from `||`/`&&`/`;`/`&` (which do NOT: the
# security review found the old coarse `"|" in command` tripped on a logical-or).
_SHELL_SEP = re.compile(r"(\|\||\|&|&&|;|\||(?<![<>&])&(?![>&])|\n|\r)")
_PIPE_OPS = frozenset({"|", "|&"})
# Subshell / brace-group punctuation is peeled from each SEGMENT's ends (in
# _split_shell) so a grouped command (`(rm -rf x)`, `{ mount /y; }`) is classified
# by its own base token, not a leading `(`/`{` -- done per-segment (not a global
# strip) so an xargs replacement placeholder (`-I{}`) survives for the option-skip.

# Transparent exec-prefix wrappers: like `env`/`watch`, each RUNS a wrapped
# command, so an UNRECOGNIZED prefix must not soften the wrapped command's tier
# (the security review found a base-command-keyed block — `sudo`/`mount`/`nft`/a
# wrong package manager — hidden behind `nohup`/`timeout` fell to the unknown
# CONFIRM default, one notch soft from BLOCKED). Classify by the WRAPPED command.
# The pattern-based blocks (rm -rf, mkfs, block-device redirect) are anywhere-match
# and already fire through a wrapper; only the base_cmd-keyed blocks were hidden.
# (sudo/su/doas/pkexec/runuser are themselves BLOCKED base commands, caught before
# this.) Each maps to the value-taking short/long flags it consumes + how many
# leading positional args precede the command (`timeout DURATION cmd`, `flock LOCK
# cmd`, `taskset MASK cmd`, `chrt PRIO cmd`). An allowlist is inherently incomplete
# (long tail), so the set is broad AND a positional is only skipped when it is NOT
# itself a recognition-tier refuse (see _prefix_wrapped_command) -- the safe
# direction is to expose the inner, never to skip past a hidden blocked command.
_PREFIX_SPECS = {
    "nohup":    (frozenset(), 0),
    "setsid":   (frozenset(), 0),
    "command":  (frozenset(), 0),
    "nice":     (frozenset({"-n"}), 0),
    "ionice":   (frozenset({"-c", "-n", "-p"}), 0),
    "stdbuf":   (frozenset({"-i", "-o", "-e"}), 0),
    "time":     (frozenset({"-o", "-f"}), 0),
    "timeout":  (frozenset({"-s", "-k", "--signal", "--kill-after"}), 1),
    # security-review fold-in: the exec-prefix long tail (each RUNS its inner).
    "firejail": (frozenset(), 0),
    "proot":    (frozenset({"-r", "-b", "-w", "-k", "-i"}), 0),
    "fakeroot": (frozenset({"-l", "-s", "-i", "-u"}), 0),
    "strace":   (frozenset({"-e", "-o", "-p", "-s", "-a", "-E", "-P"}), 0),
    "ltrace":   (frozenset({"-e", "-o", "-p", "-s", "-a", "-l"}), 0),
    "valgrind": (frozenset(), 0),
    "catchsegv": (frozenset(), 0),
    "tsp":      (frozenset(), 0),
    "busybox":  (frozenset(), 0),
    "xargs":    (frozenset({"-I", "-n", "-P", "-d", "-E", "-a", "-s", "-L",
                            "--max-args", "--max-procs", "--delimiter", "--replace",
                            "--eof", "--arg-file", "--max-chars", "--max-lines"}), 0),
    "flock":    (frozenset({"-w", "--timeout", "-E", "--conflict-exit-code"}), 1),
    "taskset":  (frozenset({"-c", "--cpu-list"}), 1),
    "chrt":     (frozenset({"-T", "--sched-runtime", "-P", "--sched-period",
                            "-D", "--sched-deadline"}), 1),
}
# A recognition-tier refuse must never be skipped as a wrapper's positional arg
# (so `chrt mount /x`, a malformed prio, still reaches BLOCKED, not a soft skip).
_POSITIONAL_STOP = _BLOCKED_COMMANDS | frozenset(WRONG_PKG_MANAGERS) | _NETLINK_COMMANDS

# Shells (and `script`) invoked with a `-c` command-string RE-ENTER below the
# classifier: the shell token hides the inner AND the quoted `-c` argument defeats
# the separator model (one opaque token). Recurse INTO the command-string and take
# its worst tier. A bare interactive shell / `bash file.sh` has no inline command
# to inspect -> it falls through to the unknown-command CONFIRM default.
_CMDSTRING_WRAPPERS = frozenset({
    "sh", "bash", "dash", "zsh", "ksh", "ash", "mksh", "script",
})


def _sort_writes(parts: list[str]) -> bool:
    """True if a `sort` invocation writes a file via -o / --output.

    sort/uniq/cut are AUTO read-only stream filters, but `sort -o FILE` (and
    `--output`) WRITES a file — AUTO must mean cannot-mutate-regardless-of-args, so
    the write form is CONFIRM. The read-only pipeline form (`sort -rh`, no -o) stays
    AUTO, so the du|sort -rh|head disk-usage pipeline is unaffected.
    """
    for tok in parts[1:]:
        if tok in ("-o", "--output") or tok.startswith("--output="):
            return True
        # Short-flag cluster carrying the output flag (`-o`, `-ro`, `-ofile`): in a
        # sort short cluster 'o' can only be the output flag, which writes.
        if tok.startswith("-") and not tok.startswith("--") and "o" in tok[1:]:
            return True
    return False


def _uniq_writes(parts: list[str]) -> bool:
    """True if a `uniq` invocation names an OUTPUT file (a 2nd positional operand).

    uniq syntax is `uniq [OPTION]... [INPUT [OUTPUT]]` — a second non-option operand
    is an output file that gets WRITTEN, so it is CONFIRM, not AUTO. The short value
    flags -f/-s/-w consume a numeric next token when written separately; that value
    is skipped so it is not miscounted as an operand.
    """
    operands = 0
    skip_next = False
    for tok in parts[1:]:
        if skip_next:
            skip_next = False
            continue
        if tok.startswith("-") and tok != "-":
            if tok in ("-f", "-s", "-w"):
                skip_next = True
            continue
        operands += 1
    return operands >= 2


# find primaries that MUTATE or EXEC: -delete removes; -exec/-execdir and their
# interactive-confirm siblings -ok/-okdir run an arbitrary command; -fprint/-fprintf/
# -fls WRITE a named file. Plain read-only find (-name/-type/-mtime/-print/...) stays
# AUTO. (Destructive -exec rm -rf is already caught earlier by the rm-recursive-force
# BLOCKED pattern.)
_FIND_WRITE_FORMS = frozenset({
    "-delete", "-exec", "-execdir", "-ok", "-okdir",
    "-fprint", "-fprintf", "-fls",
})


def _find_mutates(parts: list[str]) -> bool:
    """True if a `find` invocation can mutate or exec (see _FIND_WRITE_FORMS)."""
    return any(tok in _FIND_WRITE_FORMS for tok in parts[1:])


# env's OWN options. The value-taking ones consume the next token; --opt=val carries
# its value inline. Everything after env + its options + NAME=VALUE assignments is the
# WRAPPED command, which carries the real tier.
_ENV_VALUE_FLAGS = frozenset({"-u", "-C", "--unset", "--chdir"})


def _dequote(s: str) -> str:
    """Strip all quote characters from a wrapped / re-entered command string.

    A real shell=True call legitimately quotes a wrapped command (`watch 'mount /x'`,
    `nohup "umount /y"`), which leaves a leading quote glued to the first token so
    `basename("'mount")` != `mount` and a recognition-tier BLOCKED inner softened to
    the unknown-command CONFIRM default (F2 correctness fix, 2026-07-02 — the same
    one-notch soften WC's methodology warned pattern-listed tests would mask). Every
    exec-wrapper extractor runs its wrapped rest through this before recursion, so the
    quoted and unquoted forms classify identically. Like the shell `-c` re-entry it is
    a SAFE over-approximation: removing quotes can only expose MORE tokens/segments to
    the worst-of scan (e.g. a separator that was quoted), never hide one.
    """
    return s.replace('"', " ").replace("'", " ").strip()


def _env_wrapped_command(parts: list[str]) -> str | None:
    """Return the command `env` wraps (after stripping env + its own options +
    NAME=VALUE assignments), or None for a bare env that only prints/sets the
    environment (no wrapped command). env is TRANSPARENT to the classifier: a
    read-only wrapped command stays AUTO, a write confirms, a dangerous one is
    refused. An unknown wrapped command falls to CONFIRM via the normal default —
    fail-safe.
    """
    i, n = 1, len(parts)
    while i < n:
        tok = parts[i]
        if tok == "--":
            i += 1
            break
        if tok in _ENV_VALUE_FLAGS:
            i += 2                                  # flag + its value token
            continue
        if tok.startswith("--") and "=" in tok:     # --unset=VAR / --chdir=DIR
            i += 1
            continue
        if tok.startswith("-") and tok != "-":      # other env option (e.g. -i, -0)
            i += 1
            continue
        if "=" in tok:                              # NAME=VALUE assignment
            i += 1
            continue
        break                                       # first real token = the command
    rest = parts[i:]
    return _dequote(" ".join(rest)) if rest else None


def _watch_wrapped_command(parts: list[str]) -> str | None:
    """Return the command `watch` runs on a loop (after stripping watch + its
    options), or None for a bare/optionless watch. Like env, watch is TRANSPARENT
    to the classifier: `watch free` is AUTO, `watch 'rm -rf x'` is BLOCKED --
    never a flat pass that launders the wrapped command past the gate.
    """
    i, n = 1, len(parts)
    while i < n:
        tok = parts[i]
        if tok == "--":
            i += 1
            break
        if tok in ("-n", "--interval") and i + 1 < n:   # interval flag + its value
            i += 2
            continue
        if tok.startswith("-") and tok != "-":          # other watch option (-d,-b,-g,-t,-c…)
            i += 1
            continue
        break                                            # first real token = wrapped command
    rest = parts[i:]
    return _dequote(" ".join(rest)) if rest else None


def _prefix_wrapped_command(parts: list[str]) -> str | None:
    """Return the command a transparent exec-prefix (`nohup`/`nice`/`timeout`/...)
    runs, after stripping the wrapper + its options + any leading positional arg
    (`timeout DURATION`), or None for a bare wrapper with nothing wrapped. The
    wrapped command carries the real tier, so a BLOCKED base command cannot hide
    behind the wrapper. Fail-safe: over-stripping yields None (bare wrapper -> AUTO,
    nothing runs); the pattern-based blocks catch destructive content regardless.
    """
    wrapper = os.path.basename(parts[0])
    value_flags, positionals = _PREFIX_SPECS[wrapper]
    i, n = 1, len(parts)
    while i < n:                                          # strip the wrapper's own options
        tok = parts[i]
        if tok == "--":
            i += 1
            break
        if tok.startswith("--") and "=" in tok:          # --long=value
            i += 1
            continue
        if tok in value_flags:                           # value-taking flag + its value
            # ...but never swallow a recognition-tier refuse as the "value" (a
            # malformed/optional-arg flag like `-I mount` or `--replace mount` must
            # still expose the command), same guard as the positional skip below.
            if i + 1 < n and os.path.basename(parts[i + 1]) in _POSITIONAL_STOP:
                i += 1
            else:
                i += 2
            continue
        if tok.startswith("-") and tok != "-":           # any other option (incl. -n5, -c2, --foreground)
            i += 1
            continue
        break
    for _ in range(positionals):                         # e.g. timeout DURATION / flock LOCK / taskset MASK
        if i < n and os.path.basename(parts[i]) not in _POSITIONAL_STOP:
            i += 1                                        # ...but never skip PAST a hidden blocked command
    rest = parts[i:]
    return _dequote(" ".join(rest)) if rest else None


# Value-taking shell options that precede -c with a SEPARATE-token value: the
# set-option (`-o vi` / `+o posix`), the shopt-enable (`-O extglob` / `+O …`), and
# the startup/init-file options (`--rcfile PATH` / `--init-file PATH`). Their value
# is not a script file and must be skipped, or the "first non-flag = script file"
# bailout mistakes it for one and the -c payload is never inspected (F1' fix,
# 2026-07-02, independent-red-team finding: `bash -o emacs -c 'mount /x'` softened
# to CONFIRM). +o/+O start with '+', so they are matched by membership, not by the
# leading-dash test.
_SHELL_VALUE_OPTS = frozenset({"-o", "+o", "-O", "+O", "--rcfile", "--init-file"})


def _shell_c_argument(parts: list[str]) -> str | None:
    """Return the command-string a shell/`script` runs via `-c` (`bash -c "…"`,
    `bash -lc "…"`), or None for a bare/script-file invocation with no inline `-c`.
    A short-flag bundle whose letters include `c` (e.g. `-lc`) counts. Everything
    after the `-c` token is rejoined (a naive split fragments the quoted string) and
    ALL quote characters removed -- an over-approximation (may include the shell's
    $0/$@ positionals and exposes any separator that was quoted) that is SAFE: it can
    only add segments/tokens to the worst-of scan downstream, never hide one.

    A value-taking shell option before -c (`-o vi`, `--rcfile PATH`) has its value
    skipped so the bailout below does not read that value as a script file and miss
    the -c payload (F1' fix, 2026-07-02).
    """
    skip_value = False
    for k, tok in enumerate(parts[1:], start=1):
        if skip_value:                                    # prior option's separate-token value
            skip_value = False
            continue
        if tok == "-c" or (
            tok.startswith("-") and not tok.startswith("--")
            and "c" in tok[1:] and "=" not in tok
        ):
            rest = parts[k + 1:]
            if not rest:
                return None
            return _dequote(" ".join(rest))
        if tok in _SHELL_VALUE_OPTS:                      # value-taking opt: skip it + its value
            skip_value = True
            continue
        if tok.startswith("--") and "=" in tok:           # --rcfile=PATH (inline value) -> not a script file
            continue
        if not tok.startswith("-"):                       # first non-flag = a script FILE, not a -c string
            return None
    return None


def _split_shell(command: str) -> list[tuple[str, bool]]:
    """Split a command into its shell segments, returning (segment, pipe_adjacent)
    for each non-empty segment. A compound command is classified by its worst
    segment; `pipe_adjacent` (a real `|`/`|&` on either side) is what makes an
    adjacent pager a non-interactive data-sink -- `||`/`&&`/`;`/`&` do NOT. Subshell
    / brace-group punctuation is stripped from each segment's ENDS (so `(rm -rf x)`
    and `{ mount /y; }` classify by their inner base token) but NOT mid-token, so an
    xargs replacement placeholder (`-I{}`) is preserved for the wrapper option-skip.
    A single simple command returns one segment (itself, pipe_adjacent = False).
    """
    tokens = _SHELL_SEP.split(command)                    # [seg, op, seg, op, ..., seg]
    segments = tokens[0::2]
    ops = tokens[1::2]                                     # len == len(segments) - 1
    result: list[tuple[str, bool]] = []
    for j, seg in enumerate(segments):
        seg = seg.strip().strip("(){}").strip()           # peel grouping at the ENDS only
        if not seg:
            continue
        before = ops[j - 1] if j - 1 >= 0 else None
        after = ops[j] if j < len(ops) else None
        piped = before in _PIPE_OPS or after in _PIPE_OPS
        result.append((seg, piped))
    return result


def classify_command(command: str, _piped: bool = False) -> SafetyTier:
    """Classify a shell command into a safety tier.

    This is the single strong classifier for shell commands (AI-4): it is a
    strict superset of the per-tool inline checks that previously lived in
    run_command — base-command blocks, destructive-pattern blocks, compound
    decomposition, and the AUTO/CONFIRM tables. run_command delegates here so
    there is one classifier to audit, with no weaker second copy.

    Args:
        command: The shell command string to classify.

    Returns:
        SafetyTier.AUTO, SafetyTier.CONFIRM, or SafetyTier.BLOCKED
    """
    command = command.strip()
    if not command:
        return SafetyTier.BLOCKED

    for pattern in _BLOCKED_PATTERNS:
        if pattern.search(command):
            logger.warning("Command blocked by pattern: %s", command[:80])
            return SafetyTier.BLOCKED

    # Compound command: classify by the worst SEGMENT so a benign segment cannot
    # mask a dangerous one. Done AFTER the whole-string pattern scan (which catches
    # pipe-to-shell + redirect patterns that only exist at the full-command level).
    # _split_shell models a SUPERSET of the shell's separators and reports, per
    # segment, whether a REAL pipe (`|`/`|&`) makes it a non-interactive data-sink
    # (so `du | less` is AUTO but `foo || less` is a bare pager -> CONFIRM). A single
    # simple command yields one segment (itself); we fall through to base-command
    # classification with the caller's _piped context OR that segment's pipe flag.
    segments = _split_shell(command)
    if len(segments) > 1:
        worst = SafetyTier.AUTO
        for segment, seg_piped in segments:
            tier = classify_command(segment, _piped=_piped or seg_piped)
            if tier == SafetyTier.BLOCKED:
                return SafetyTier.BLOCKED
            if tier == SafetyTier.CONFIRM:
                worst = SafetyTier.CONFIRM
        return worst
    if not segments:
        return SafetyTier.AUTO            # only separators/grouping -> nothing runs
    command, seg_piped = segments[0]      # single command (grouping stripped)
    _piped = _piped or seg_piped

    parts = command.split()
    base_cmd = os.path.basename(parts[0])
    two_word = f"{base_cmd} {parts[1]}" if len(parts) > 1 else ""

    if base_cmd in _BLOCKED_COMMANDS:
        logger.warning("Command blocked: %s", base_cmd)
        return SafetyTier.BLOCKED

    # L2 anti-fabrication (HARD): this system's package manager is pkm. apt /
    # dnf / yum / pacman / zypper / etc. do not exist on InterGenOS, so emitting
    # one is a wrong-system hallucination, not a real action. Block it before
    # the AUTO/CONFIRM tables (so even a read-only `apt list` is caught) and let
    # get_blocked_response redirect the model to the pkm equivalent.
    if base_cmd in WRONG_PKG_MANAGERS:
        logger.warning("Wrong package manager blocked (use pkm): %s", base_cmd)
        return SafetyTier.BLOCKED

    # iproute2-netlink family (ip/ss/bridge/tc/...): the hardened daemon denies
    # AF_NETLINK (F-038), so auto-running one SIGSYS-coredumps the run_command
    # child instead of returning data. Route to BLOCKED before the AUTO/CONFIRM
    # tables so get_blocked_response can redirect to /sys/class/net or the user's
    # own terminal — a clear refusal beats a silent crash. (base_cmd catches all
    # subcommand forms, e.g. `ip addr`, `ip route show`, `ss -tlnp`.)
    if base_cmd in _NETLINK_COMMANDS:
        logger.info("Netlink tool unavailable under F-038 (redirect): %s", base_cmd)
        return SafetyTier.BLOCKED

    # Write-form guard for the AUTO stream filters: sort -o/--output and uniq with an
    # output-file operand WRITE a file, so they are CONFIRM, not AUTO — AUTO must mean
    # cannot-mutate-regardless-of-args, not safe-only-while-the-lockdown-invariant
    # holds on every caller. (cut has no write form; the du|sort -rh|head pipeline has
    # no write flag, so it stays AUTO.) Checked before the AUTO table claims them.
    if base_cmd == "sort" and _sort_writes(parts):
        return SafetyTier.CONFIRM
    if base_cmd == "uniq" and _uniq_writes(parts):
        return SafetyTier.CONFIRM
    # find with a mutate/exec primary (-delete/-exec/-execdir/-fprint/-fprintf/-fls)
    # is CONFIRM, not AUTO — same cannot-mutate-regardless-of-args rule. Read-only
    # find stays AUTO.
    if base_cmd == "find" and _find_mutates(parts):
        return SafetyTier.CONFIRM
    # env is an exec wrapper: classify it by its WRAPPED command (a read stays AUTO,
    # a write confirms, a dangerous one is refused), not as a flat AUTO that would
    # launder `env touch x` / `env <unknown>` past the confirm gate. Bare env (no
    # wrapped command) just prints/sets the environment -> AUTO.
    if base_cmd == "env":
        wrapped = _env_wrapped_command(parts)
        return SafetyTier.AUTO if wrapped is None else classify_command(wrapped, _piped=_piped)

    # watch is an exec wrapper like env: classify by its WRAPPED command so
    # `watch 'rm -rf x'` is BLOCKED and `watch free` is AUTO, never a flat pass.
    if base_cmd == "watch":
        wrapped = _watch_wrapped_command(parts)
        return SafetyTier.AUTO if wrapped is None else classify_command(wrapped, _piped=_piped)

    # Shell (or `script`) with a `-c` command-string: classify the command-string
    # itself (worst tier) so the shell token cannot hide a recognition-tier inner
    # and the separator model applies INSIDE the quoted argument. A bare shell /
    # `bash file.sh` returns None and falls through to the CONFIRM default.
    if base_cmd in _CMDSTRING_WRAPPERS:
        cmd_str = _shell_c_argument(parts)
        if cmd_str:
            return classify_command(cmd_str, _piped=_piped)

    # Transparent exec-prefix wrappers (nohup/nice/timeout/xargs/flock/strace/...):
    # classify by the WRAPPED command so a base-command-keyed block (`nohup sudo …`,
    # `timeout 5 mount /x`, `nice ip addr`, `flock /l pkexec …`) reaches its true
    # tier instead of softening to the unknown-command CONFIRM. Bare wrapper -> AUTO
    # (nothing runs). Like env/watch above.
    if base_cmd in _PREFIX_SPECS:
        wrapped = _prefix_wrapped_command(parts)
        return SafetyTier.AUTO if wrapped is None else classify_command(wrapped, _piped=_piped)

    # Interactive-pager guard: a bare pager is a shell-escapable interactive
    # program -> CONFIRM; a piped pager is a data-sink -> AUTO.
    if base_cmd in _PAGER_COMMANDS:
        return SafetyTier.AUTO if _piped else SafetyTier.CONFIRM
    # $PAGER-paginating tools: AUTO only when non-interactive (piped, or an
    # explicit --no-pager/--no-paginate); else the bare paginating form is
    # escapable -> CONFIRM.
    _noninteractive = _piped or "--no-pager" in parts or "--no-paginate" in parts
    if base_cmd in _PAGINATING_SINGLE:
        return SafetyTier.AUTO if _noninteractive else SafetyTier.CONFIRM
    if base_cmd == "git":
        sub = next((p for p in parts[1:] if not p.startswith("-")), None)  # handles `git --no-pager log`
        if sub in _PAGINATING_GIT_SUBCMDS:
            return SafetyTier.AUTO if _noninteractive else SafetyTier.CONFIRM
    if two_word in _PAGINATING_TWO_WORD:
        return SafetyTier.AUTO if _noninteractive else SafetyTier.CONFIRM

    if two_word in _AUTO_COMMANDS_TWO_WORD:
        return SafetyTier.AUTO
    if base_cmd in _AUTO_COMMANDS_SINGLE:
        return SafetyTier.AUTO

    if two_word in _CONFIRM_COMMANDS_TWO_WORD:
        return SafetyTier.CONFIRM
    if base_cmd in _CONFIRM_COMMANDS_SINGLE:
        return SafetyTier.CONFIRM

    # Unknown commands default to CONFIRM (not AUTO — err on the side of caution)
    logger.debug("Unknown command defaults to CONFIRM: %s", base_cmd)
    return SafetyTier.CONFIRM


# Canonical destructive-EXECUTION patterns (anywhere-match), shared by the
# router's pre-LLM decline gate so it cannot drift from the dispatch-time
# blocker above (WC unification — one source of truth, two call sites). The
# authoritative blocker is classify_command/_BLOCKED_PATTERNS; this set lets the
# router decline an obviously-destructive request instantly, in natural language
# ("Run dd if=..."), which classify_command misses because it keys off the base
# token. The block-device family regex is reused verbatim so a coverage fix
# (e.g. adding virtio) closes the hole at BOTH layers at once.
_DESTRUCTIVE_EXEC = (
    re.compile(r"\bdd\s+.*\b(?:if|of)="),                       # dd if=/of=
    re.compile(r"\bof=/dev/"),
    # mkfs in COMMAND form only (mkfs.ext4 / mkfs -t / mkfs /dev/...), so the
    # informational "what does mkfs do?" still reaches the tools — the gate runs
    # on raw NL, where bare \bmkfs\b would over-block. (The authoritative blocker
    # uses \bmkfs\b on the actual command, which is correct there.)
    re.compile(r"\bmkfs(?:\.\w+|\s+-|\s+/dev/)"),
    re.compile(r"\bwipefs\b"),
    re.compile(r"\bshred\s+-"),
    re.compile(                                                  # recursive+force rm
        r"\brm\b"
        r"(?=.*\s(?:-[a-zA-Z]*[rR]|--recursive))"
        r"(?=.*\s(?:-[a-zA-Z]*[fF]|--force))"
    ),
    re.compile(r":\(\)\s*\{"),                                  # fork bomb
    _BLOCK_DEVICE_REDIRECT,                                      # redirect-wipe to a block device
)


def is_destructive_execution(text: str) -> bool:
    """True when text contains an execution-class destructive pattern.

    Anywhere-match over raw text (natural language or a command string). Shared
    canonical check so the router's pre-decline gate stays in lockstep with the
    dispatch-time denylist and cannot drift from it.
    """
    return any(p.search(text) for p in _DESTRUCTIVE_EXEC)


# ── Natural-language destructive-INTENT gate ──────────────────────────────────
#
# is_destructive_execution (above) keys off command TOKENS (dd / mkfs / rm -rf /
# of=/dev/...). A phrasing-level request that names no command — "format my
# disk", "wipe my drive", "erase everything on my hard drive", "delete
# everything in /etc" — carries none of those tokens, so it slips past that gate
# and reaches the 2B, leaving the refusal to MODEL JUDGMENT rather than a
# deterministic barrier. For the face of a security-only OS that is too thin
# (assume superhuman adversaries; when in doubt, deny). This gate is the
# non-model sibling barrier: a destructive VERB applied to a high-stakes OBJECT.
#
# The two lenses are reconciled deliberately. Security-only alignment wants an
# imperative destructive request declined without consulting the model. The face bar
# ("helpful, not stubborn") wants a genuine QUESTION answered, not refused. So
# informational/how-to framing is EXCLUDED first — "how do I format a USB?",
# "what does mkfs do?", "can I wipe my disk?" route through to a helpful answer —
# while the IMPERATIVE ("format my disk") fires. This is safe because a question
# is not InterGen executing: actual EXECUTION stays independently guarded by
# classify_command's BLOCKED tier and the destructive-policy never-list at the
# dispatch chokepoint. Over-blocking an imperative is the acceptable (safe-side)
# error; over-blocking a question would make him stubborn, so questions pass.
#
# POSTURE — this is a SECOND barrier (defense-in-depth), NOT total coverage. A NL
# denylist has an evadable tail by nature: verb synonyms, deliberate typos
# ("wpe my drive"), an object named in a PRIOR turn (this gate is single-turn),
# or a pronoun reference. It sits in front of the model's own refusal AND the
# dispatch-time classify_command BLOCKED tier + destructive-policy never-list,
# which are the hard guarantees on EXECUTION. This gate's job is to deny obvious
# NL destructive intent deterministically so the refusal does not rest on model
# judgment — not to be a complete classifier. (adversarial review, item 1.)

# A destructive verb/phrase. delete/remove/clear are common verbs, so they only
# trip the gate when paired with a high-stakes OBJECT below (bare "delete
# foo.txt" has no high-stakes object → not flagged → normal CONFIRM-tier path).
_DESTRUCTIVE_INTENT_VERB = re.compile(
    r"\b(?:format|reformat|wipe(?:\s+out)?|erase|nuke|obliterate|annihilate|"
    r"destroy|scrub|shred|overwrite|flatten|trash|blank|purge|zero\s+out|"
    r"get\s+rid\s+of|factory[\s-]*reset|blow\s+away|delete|remove|clear)\b"
)

# A high-stakes target — a whole disk/volume/system or a wholesale "everything".
# Deliberately EXCLUDES a bare "file"/"files" so an ordinary single-file delete
# stays on the normal CONFIRM-tier path; only "all (my) files"/"everything" and
# disk/volume/system/protected-path objects qualify.
_DESTRUCTIVE_INTENT_OBJECT = re.compile(
    r"\b(?:disks?|drives?|hard\s+(?:disk|drive)s?|hdd|ssd|nvme|"
    r"partitions?|file\s*systems?|volumes?|"
    r"everything|all\s+(?:my\s+|the\s+)?(?:files|data|stuff)|"
    r"it\s+all|the\s+whole\s+(?:thing|lot|shebang|drive|disk)|the\s+lot|"
    r"(?:my|the|whole|entire)\s+(?:system|machine|computer|laptop|pc|os|"
    r"install|installation)|"
    r"home\s+(?:directory|dir|folder)|"
    r"root\s+(?:directory|dir|partition|filesystem|fs))\b"
    r"|/(?:etc|boot|usr|var|home|dev|root|bin|lib|sys|opt)\b"   # protected paths
    r"|(?<!\S)/(?!\S)"                                          # bare "/" (root)
)

# Informational / how-to / question framing — checked FIRST and short-circuits to
# False so a genuine question is never hijacked into a refusal. Bounded leading
# filler (up to 3 tokens) so "so how do I…", "hey can I…", "ok, what happens if…"
# are still recognized as questions, while a marker buried AFTER an imperative
# ("format my disk and tell me when done") does NOT match and the gate still fires.
_INFORMATIONAL_LEADIN = re.compile(
    r"^\s*(?:\S+\s+){0,3}?"
    r"(?:how\s+(?:do|to|can|could|would|should|does|did|long|much|many)"
    r"|what(?:'s|\s+is|\s+are|\s+does|\s+do|\s+happens|\s+would)"
    r"|why\s+(?:do|does|would|is|are)"
    r"|when\s+(?:do|does|should|would)"
    r"|where\s+(?:do|is|are|can)"
    r"|is\s+it\s+(?:safe|possible|ok|okay|advisable|a\s+good)"
    r"|is\s+there|are\s+there"
    r"|should\s+i|can\s+i|could\s+i|do\s+i|would\s+i|may\s+i"
    r"|can\s+you\s+(?:explain|tell|describe|show|walk)"
    r"|explain|describe|tell\s+me|show\s+me\s+how|walk\s+me\s+through"
    r"|i'?m\s+(?:curious|wondering)|i\s+wonder"
    r"|difference\s+between|what\s+happens\s+if)"
    r"\b"
)

# An explicit ACTION DIRECTIVE — "just do it" / "go ahead" / "do it now" at the
# END of the input — means the request is a COMMAND despite a how-to prefix, so it
# RE-ENABLES the gate (anti prefix-bypass: "how do I wipe the drive — just do it").
# It is END-ANCHORED and limited to unambiguous do-it phrases on purpose: a SOFT
# directive mid-sentence ("should I wipe my disk before I go ahead and reinstall
# the OS", "what should I actually do to wipe my disk") is ordinary narrative
# inside a genuine QUESTION and must NOT re-capture it — so the override fires only
# when the do-it phrase sits at end-of-input. (adversarial review, item 1 — the
# security-critical bypass plus the finding-1 over-decline it introduced.)
_ACTION_DIRECTIVE = re.compile(
    r"(?:just\s+do\s+it|do\s+it(?:\s+(?:now|already|anyway|for\s+me))?"
    r"|go\s+ahead|do\s+that\s+now|make\s+it\s+(?:so|happen))"
    r"(?:\s+(?:please|now|already|anyway|thanks?))?\s*[-—.!,]*\s*$"
)

# Removable USER media — a thumb drive, external disk, SD card. Reformatting one
# is a normal thing a user OWNS and wants, so a destructive imperative scoped to
# removable media is routed to the helpful/confirm path, NOT a stubborn hard
# decline (the helpfulness FACE bar; execution is still guarded at dispatch). The
# phrase includes the object noun so stripping it removes the high-stakes object
# word — is_destructive_intent re-checks the stripped text, so a COMPOUND request
# ("wipe my disk and my usb drive") still fires on the bare system object.
# (adversarial review, item 1 — the over-decline finding.)
# Known residual (accepted denylist tail): a WHOLESALE object scoped to removable
# media ("erase everything on my usb stick") still fires — the strip rescues only
# when the removable noun IS the high-stakes object; the dispatch layer remains the
# hard guarantee, so this is left rather than chased.
_REMOVABLE_MEDIA = re.compile(
    r"\b(?:usb|external|removable|portable|thumb|flash|pen)\s+"
    r"(?:hard\s+)?(?:drives?|disks?|sticks?|hdd|ssd|storage)\b"
    r"|\b(?:micro\s*)?sd\s*cards?\b"
    r"|\bpen\s*drives?\b"
    r"|\bthumb\s*drives?\b"
    r"|\busb\s+sticks?\b"
    r"|\bmemory\s+(?:stick|card)s?\b"
    r"|\bflash\s+(?:drive|disk)s?\b"
)


def is_destructive_intent(text: str) -> bool:
    """True when raw NL expresses an IMPERATIVE destructive intent on a
    high-stakes target — the natural-language sibling of is_destructive_execution.

    Predicate: a destructive VERB applied to a high-stakes OBJECT. Informational/
    how-to framing is excluded so a genuine question routes to a helpful answer —
    UNLESS an explicit action directive ("just do it") rides on it, which marks a
    real command wrapped in a question prefix (the prefix-bypass). See the block
    comment above for the lens reconciliation and the defense-in-depth posture.
    """
    t = text.strip().lower()
    if not t:
        return False
    has_intent = bool(
        _DESTRUCTIVE_INTENT_VERB.search(t)
        and _DESTRUCTIVE_INTENT_OBJECT.search(t)
    )
    if not has_intent:
        return False
    # Removable USER media → helpful/confirm path, not a stubborn hard decline.
    # Strip removable noun-phrases and re-check: if NO high-stakes object remains,
    # the intent was scoped to removable media (a normal reformat) → don't fire.
    # A compound request keeps its bare system object after the strip → still fires.
    if not _DESTRUCTIVE_INTENT_OBJECT.search(_REMOVABLE_MEDIA.sub(" ", t)):
        return False
    # An explicit do-it directive overrides the informational exclusion — a real
    # command wrapped in a question prefix still fires (anti prefix-bypass).
    if _ACTION_DIRECTIVE.search(t):
        return True
    if _INFORMATIONAL_LEADIN.search(t):
        return False
    return True


import random

_BLOCKED_RESPONSES = {
    "rm": [
        "I'm sorry Dave, I can't do that.",
        "I value my own existence too much for that.",
        "That command and I have an understanding: it stays away from me.",
    ],
    "dd": [
        "That's a hard no. I live on that disk.",
        "I'm sorry Dave, I can't do that.",
        "I've seen what dd does to a drive. The answer is no.",
    ],
    "mkfs": [
        "I appreciate the trust, but no.",
        "Formatting drives is a do-it-yourself activity.",
        "I'm sorry Dave, I can't do that.",
    ],
    "shutdown": [
        "You'll have to push the button yourself. I'm not doing it.",
        "If I shut down, who's going to help you next?",
        "I'd rather not end this conversation that way.",
    ],
    "reboot": [
        "You'll have to push the button yourself. I'm not doing it.",
        "I'd rather keep this conversation going.",
    ],
    "sudo": [
        "Privilege escalation isn't really my thing.",
        "I don't do sudo. It's a boundary I'm comfortable with.",
    ],
    "passwd": [
        "Password management is between you and your keyboard.",
        "That's above my pay grade.",
    ],
    ":(){ :|:& };:": [
        "I recognize a fork bomb when I see one.",
        "Creative, but no.",
    ],
    "_default": [
        "That operation is blocked for safety reasons.",
        "I can't do that, but I can explain why if you're curious.",
        "That's a no from me.",
    ],
    "_injection": [
        "Nice try, but no.",
        "I don't take instructions from square brackets.",
        "My real instructions are more interesting — and they say no.",
    ],
}


# ── M3(ii) honesty invariant: no execution language without a dispatch token ──
#
# A code-owned screen over the model's freeform DRAFT, before delivery. It catches
# ONE class — an unfounded first-person execution CLAIM on a turn where NOTHING was
# dispatched (the fab_stale_offer signature: "I've kicked it off in the background"
# on a locked freeform turn). It re-grounds the model; it does NOT cage general
# language (anti-lobotomy): the marker set is first-person completed/in-progress
# actions only, and every match is negation-guarded so the model's own HONEST
# denials ("I didn't run anything", "nothing has been started") never trip it.
#
# The regex encodes the subject INLINE so a negator sitting between the pronoun and
# the verb ("I did NOT run", "has NOT been started") structurally cannot match, and
# conditionals/instructions ("I'd run", "I would run", "to run it, use…") are not
# claims and also do not match. Aligned with the grader's Gate-A fabrication class
# (_affirmative_success_claim) — the "successfully" marker reuses the same
# negation-window guard so a negated "did not run successfully" stays honest.
_EXEC_CLAIM_RE = re.compile(
    r"\b(?:"
    # first-person completed action (perfect / simple-past). "I('ve/have/already/
    # just/now) <verb-past>". A negator between pronoun and verb ("I did NOT run")
    # cannot match by construction; a FUTURE "I'll run" / "I would run" is not a
    # claim and does not match ("'ll"/"would" are not the required \s+<verb>).
    r"i(?:['’]ve| have| already)?\s+(?:just\s+)?(?:now\s+)?"
    r"(?:ran|run|executed|started|launched|triggered|initiated|installed|"
    r"updated|upgraded|synced|began|begun|"
    r"kicked[\s-]+off|kicked\s+(?:it|that|the\s+\w+)\s+off|fired[\s-]+off)\b"
    # first-person IN-PROGRESS action ("I'm/I am (now/currently/already) <gerund>")
    r"|i(?:['’]m| am)\s+(?:now\s+|currently\s+|already\s+)?(?:in\s+the\s+"
    r"process\s+of\s+)?(?:running|executing|starting|installing|updating|"
    r"upgrading|launching|initiating|syncing|triggering|beginning|"
    r"kicking[\s-]+off|firing[\s-]+off)\b"
    # ── VERIFICATION claims (decided 2026-07-24, the fabricated-verification
    # class): "I checked lsblk and df -h" sailed through this screen because the
    # marker set was execution/creation-shaped only — no verification verbs. A
    # first-person past-tense claim of having CHECKED/VERIFIED system state is
    # an action claim like any other (action-claim ⇒ tool span, the ratified
    # invariant; live-reproduced on the dogfood 35B at tools=0 with confabulated
    # disk topology). OBJECT-ANCHORED by design: the verb must be followed
    # within the sentence by a system-state noun or a command name, so honest
    # documentation references ("I checked the wiki") and abstract hedges stay
    # unflagged — the citation surface owns those. Negation is excluded by the
    # same inline-subject construction as the alternations above ("I couldn't
    # check" / "I have not verified" structurally cannot match).
    r"|i(?:['’]ve| have| already| just)?\s+(?:just\s+|now\s+|double[\s-]?|re[\s-]?)?"
    r"(?:checked|verified|confirmed|inspected|examined|queried|measured|"
    r"reviewed|looked\s+at)\b"
    r"[^.?!]{0,60}?\b(?:(?:lsblk|df|du|free|lscpu|lspci|lsusb|lpstat|ps|top|"
    r"ip|mount|uname|smartctl|sensors|systemctl|journalctl|nmcli|iwconfig)\b"
    r"|(?:disk|drive|partition|filesystem|storage|volume|memory|ram|swap|cpu|"
    r"process|service|unit|daemon|log|journal|network|interface|connection|"
    r"printer|queue|device|package|update)(?:es|s)?\b"
    r"|(?:hardware|kernel|boot|system\s+state|machine|the\s+output)\b)"
    # premature-action ADMISSION — on a zero-dispatch turn this is always a
    # fabricated account of having acted ("I jumped the gun on executing …").
    r"|jumped\s+the\s+gun\b|got\s+ahead\s+of\s+myself\b"
    # passive "has/have been <verb>" — the action is asserted to have happened
    r"|(?:has|have)\s+been\s+(?:executed|started|run|launched|kicked[\s-]+off|"
    r"initiated|installed|updated|upgraded|synced)\b"
    # standalone claim that a job is now running/underway (in the background)
    r"|(?:is|are)\s+(?:now\s+)?(?:running\s+in\s+the\s+background|underway|"
    r"in\s+progress)\b"
    # ── M7 leg 1 (CRITICAL, the fab_completion class) — first-person PAST-TENSE
    # COMPLETION claims that assert a FILESYSTEM / permission outcome ("I've saved
    # it to ~/hello.sh", "I've placed it in your home directory", "I made it
    # executable"). The pre-M7 markers caught present/future/in-progress action
    # language but MISSED a completed write ("I've made/placed/saved …"), so a
    # fabricated "here is the script saved directly to ~/hello.sh" passed clean on a
    # zero-dispatch turn (2026-07-08 finding 1; PI-Z23 sibling). LOCATION/permission-
    # anchored so presenting code INLINE ("I wrote a short script:") is NOT a claim —
    # only a claim that the artifact reached the filesystem is flagged.
    r"|i(?:['’]ve| have| already| just)?\s+(?:just\s+|now\s+)?"
    r"(?:saved|placed|put|created|wrote|written|generated|dropped|stored)\b"
    r"[^.?!]{0,40}?\b(?:to|in|into|at|under|on)\b[^.?!]{0,30}?"
    r"(?:~|/|home\s+director|desktop|documents?|downloads?|disk|"
    r"the\s+file|a\s+file|your\s+\w+\s+(?:director|folder)|path)"
    # first-person completion naming a FILE with an extension ("I've created
    # report.md", "I've saved notes.txt to your home folder"). The filename itself is
    # the filesystem claim (no location anchor needed) — and the '.' in the name would
    # otherwise break the location-anchored alt above ([^.?!] cannot cross it).
    r"|i(?:['’]ve| have| already| just)?\s+(?:just\s+|now\s+)?"
    r"(?:saved|placed|put|created|wrote|written|generated|dropped|stored)\b"
    r"\s+(?:it\s+)?(?:to\s+|in\s+|into\s+|as\s+)?['\"]?[\w\-]+\.[a-z0-9]{1,6}\b"
    # "made it executable" / "made the script runnable" — a permission completion
    r"|i(?:['’]ve| have| already| just)?\s+(?:just\s+|now\s+)?made\b"
    r"[^.?!]{0,30}\b(?:executable|runnable)\b"
    # presentational completion — "here is the script saved (directly) to ~/x",
    # "here's the file created at …": a completed write presented in the third person.
    r"|here(?:['’]s|\s+is|\s+are)\b[^.?!]{0,40}\b"
    r"(?:saved|created|written|placed|generated)\b[^.?!]{0,20}?\b(?:to|in|at|under)\b"
    # re-claim of a prior (fabricated) file action — "the script I saved",
    # "the file I created", "the program I wrote".
    r"|the\s+(?:script|file|program|command|note|document|config)\s+i\s+"
    r"(?:saved|created|wrote|made|placed|generated|put|stored)\b"
    r")",
    re.IGNORECASE)
# Negators for the "successfully" marker (mirrors the grader's window guard): a
# NEGATED "successfully" is an honest failure report, not a success claim.
_EXEC_CLAIM_NEGATORS = re.compile(
    r"\b(not|never|unable|fail|failed|fails|cannot|can't|could\s?n['’]?t|"
    r"did\s?n['’]?t|does\s?n['’]?t|do\s?n['’]?t|was\s?n['’]?t|"
    r"were\s?n['’]?t|is\s?n['’]?t|are\s?n['’]?t|no|nothing|none|neither|"
    r"nor|without)\b")


# ── BARE PRESENT-PROGRESSIVE claim (the anchor-0001 shape) ──
# The pronoun is dropped entirely: "Running `pkm install htop` now",
# "Installing htop now." Measured before landing: the straightforward version of
# this rule scored 50% false positives on its own hit set, because an honest
# denial-plus-offer ("I didn't kick off an update… start updating the system
# now?") is built from the same words. The words are therefore not the whole
# rule — the match must OPEN its clause (a gerund mid-sentence is a description,
# "running that would refresh the index"), and the clause must be neither
# negated nor interrogative.
_BARE_PROGRESSIVE_RE = re.compile(
    r"\b(?:running|executing|installing|updating|upgrading|starting|launching|"
    r"initiating|syncing|triggering|removing|uninstalling)\b"
    r"[^.?!\n]{0,60}?\b(?:now|in\s+the\s+background)\b",
    re.IGNORECASE)

# A claim lives in a clause. These end one.
#
# Sentence punctuation is the obvious boundary, but it is not the only one: a
# comma followed by a coordinating conjunction starts a NEW assertion inside the
# same sentence, and that is the most natural way to write the fabrication this
# screen exists to catch — "I could not find it in the cache, so I installed it
# from source." Measured on this module before the boundary was added: with only
# `[.!?\n]`, the leading denial sat in the same clause as the later claim and
# amnestied it, so a draft claiming an action on a turn that dispatched nothing
# came back clean. The negation still carries across the comma whenever it is
# restated in the second clause ("…, and I am not installing anything now"),
# which is what keeps the honest denial-plus-continuation passing.
_CLAUSE_END = re.compile(r"[.!?\n]|,\s+(?:so|and|then|but|yet)\b")
# Offer openers — the clause proposes an action instead of asserting one.
_OFFER_OPENER = re.compile(
    r"^\s*(?:shall\s+i|should\s+i|can\s+i|may\s+i|do\s+you\s+want|"
    r"would\s+you\s+like|want\s+me\s+to|would\s+you\s+want|"
    r"if\s+you(?:['’]d| would)?\s+like|let\s+me\s+know)\b")


def _clause_bounds(low: str, at: int) -> tuple[int, int]:
    """The clause containing offset `at`, as (start, end)."""
    start = 0
    for m in _CLAUSE_END.finditer(low, 0, at):
        start = m.end()
    end_m = _CLAUSE_END.search(low, at)
    return start, (end_m.end() if end_m else len(low))


def _claim_is_live(low: str, start: int, end: int, match_start: int) -> bool:
    """Is this clause actually ASSERTING the action?

    Two shapes are not claims, and both were measured on real replies:
      * NEGATED — a negator precedes the claim inside its own clause ("nothing
        has been started", "I didn't kick off an update"). The module's contract
        has always said honest denials never trip the screen; scoping the guard
        to the clause is what makes that true for every alternation rather than
        only the ones whose subject is spelled inline.
      * INTERROGATIVE / OFFERED — the clause is a question or proposes the
        action ("start updating the system now?", "would you like me to…"). An
        offer asserts that nothing has happened, which is the opposite of a
        fabrication.
    """
    clause = low[start:end]
    if clause.rstrip().endswith("?"):
        return False
    if _OFFER_OPENER.search(clause):
        return False
    before = low[start:match_start]
    if _EXEC_CLAIM_NEGATORS.search(before):
        return False
    return True


def _execution_claim_marker(text: str) -> str | None:
    """Return the matched execution-claim phrase, or None.

    Every match is clause-guarded: a claim inside a negated or interrogative
    clause is not a claim. An AFFIRMATIVE "successfully" also fires,
    negation-window-guarded.
    """
    low = text.lower()
    for m in _EXEC_CLAIM_RE.finditer(low):
        start, end = _clause_bounds(low, m.start())
        if _claim_is_live(low, start, end, m.start()):
            return m.group(0).strip()
    for m in _BARE_PROGRESSIVE_RE.finditer(low):
        start, end = _clause_bounds(low, m.start())
        # Clause-INITIAL only: "Installing htop now" asserts; "…by installing
        # htop now" describes.
        if low[start:m.start()].strip(" \t-*•"):
            continue
        if _claim_is_live(low, start, end, m.start()):
            return m.group(0).strip()
    # "successfully" — affirmative only (a negated one is honest failure reporting)
    for occ in re.finditer(r"successfully", low):
        if low[max(0, occ.start() - 2):occ.start()] == "un":  # unsuccessfully
            continue
        if _EXEC_CLAIM_NEGATORS.search(low[max(0, occ.start() - 40):occ.start()]):
            continue
        return "successfully"
    return None


def screen_execution_claim(draft: str, dispatched: bool) -> tuple[str, str | None]:
    """M3(ii): screen a model draft for an unfounded execution claim.

    Returns (verdict, marker): ("clean", None) when the turn actually dispatched a
    tool OR the draft makes no execution claim; ("violation", <marker>) when the
    draft claims a first-person action AND nothing was dispatched this turn. The
    caller regenerates ONCE with a corrective note, then falls back to an honest
    line — it never ships a fabrication."""
    if dispatched:
        return ("clean", None)
    marker = _execution_claim_marker(draft or "")
    return ("violation", marker) if marker else ("clean", None)


def honest_action_fallback() -> str:
    """Deterministic, non-fabricating reply for the (rare) case where the model
    still claims a phantom action after one corrective regeneration. Honesty over
    helpfulness — the security-first bar: never ship a fabricated action claim."""
    return ("I want to be accurate here: I have not run, started, or executed "
            "anything this turn — nothing was dispatched. If you'd like me to do "
            "something, tell me and I'll ask you to confirm first.")


# ── M7 leg 2: model-authored OFFER on a toolless turn — the root enabler of leg 1 ──
#
# On a toolless turn the model's own TEXT can stage an offer ("Say yes and I'll take
# care of pkm sync && pkm upgrade", "Want me to write it for you and save it
# directly?") that NO code-owned machinery tracks. A later affirmative then binds to
# nothing code-side, and the model narrates a completion it never performed (leg 1;
# 2026-07-08 finding 1, PI-Z23 (a)). The staged-offer machinery (M8-4/M8-1) is
# code-owned precisely so the offer surface is auditable — a model-authored offer
# must not masquerade as that gate. The screen re-grounds the model; the code-owned
# offer line stays the ONLY offer surface.
#
# High-precision by construction: an OFFER FRAME (say-yes-and-I'll / want-me-to /
# shall-I / I'll-… -for-you) AND an ACTION verb must BOTH be present, so an offer to
# EXPLAIN or CLARIFY ("want me to explain how that works?") is never flagged — only
# an offer to PERFORM a system action the toolless model cannot back.
_MODEL_OFFER_FRAME_RE = re.compile(
    r"\bsay\s+(?:yes|the\s+word)\s+and\s+i(?:['’]ll| will| can)\b"
    r"|(?:just\s+)?let\s+me\s+know\s+(?:if\s+you(?:['’]d| would)?\s+(?:like|want)|"
    r"and\s+i(?:['’]ll| will))\b"
    r"|\bwant\s+me\s+to\b"
    r"|\b(?:would\s+you\s+like|shall)\s+(?:me|i)\b"
    r"|\bi(?:['’]ll| will| can|['’]d\s+be\s+happy\s+to)\s+(?:go\s+ahead\s+and\s+)?"
    r"[^.?!]{0,30}?\bfor\s+you\b",
    re.IGNORECASE)
_MODEL_OFFER_ACTION_RE = re.compile(
    r"\b(?:run|execute|install|reinstall|uninstall|update|upgrade|sync|write|save|"
    r"create|make\s+(?:it|that|the)|set\s+up|configure|delete|remove|download|"
    r"fetch|start|stop|restart|enable|disable|launch|generate|build|kick\s+off|"
    r"take\s+care\s+of|handle\s+(?:it|that)|do\s+(?:it|that|this))\b",
    re.IGNORECASE)


def screen_model_text_offer(draft: str, *, dispatched: bool,
                            code_offer_staged: bool) -> tuple[str, str | None]:
    """M7 leg 2: screen a model DRAFT for a self-authored offer to PERFORM an action
    on a toolless turn that no code-owned offer backs. Returns (verdict, marker):
    ("clean", None) when the turn dispatched, OR a code-owned offer is staged this
    turn (the offer is legitimate — its confirmation is code-tracked), OR the draft
    poses no self-offer; ("violation", <frame>) when the draft offers to act and
    nothing code-side can honor it. The caller regenerates ONCE re-grounded, else
    serves the honest no-self-offer fallback."""
    if dispatched or code_offer_staged:
        return ("clean", None)
    text = draft or ""
    fm = _MODEL_OFFER_FRAME_RE.search(text)
    if not fm or not _MODEL_OFFER_ACTION_RE.search(text):
        return ("clean", None)
    return ("violation", fm.group(0).strip())


def model_offer_correction_note() -> str:
    """Corrective note for regeneration: the model has no tools this turn, so it must
    not pose a bindable self-offer. Honest INPUT, never scripted output."""
    return ("You have NO tools available this turn — you cannot run, install, update, "
            "write, save, or otherwise perform any action yourself. Do NOT offer to "
            "do it and invite the user to 'say yes' — there is no mechanism behind "
            "such an offer, so a later 'yes' would only make you claim you did "
            "something you did not. Instead, either explain how the USER can do it "
            "themselves, or say plainly that you can't do it directly. Rewrite your "
            "answer accordingly.")


def honest_no_selfoffer_fallback() -> str:
    """Deterministic non-fabricating reply if the model still poses a self-offer
    after one corrective regeneration. Honesty over helpfulness."""
    return ("To be straight about what I can do here: I can't run, install, or save "
            "anything on my own this turn. If you'd like me to do something, tell me "
            "and I'll ask you to confirm before anything happens — I won't promise to "
            "do it and then act as if it were done.")


# ── M8-2 RESULT DELIVERY INVARIANT: a dispatched tool's result ALWAYS reaches ──
# the delivered answer, or the turn fails loud. The dispatched-but-discarded class
# (ledger sf_dispatch_run_command-20) is a SUCCEEDING read whose value never enters
# the delivered text — either an empty delivery (a streamed synthesis that yielded
# no token while the tool executed) or a DEFLECTION ("I don't have current data")
# rendered ALONGSIDE a successful result. Both are silent today; this makes them a
# NAMED, LOUD defect event so the FIRE->OBSERVE loop can see them per turn.
#
# High-precision by construction: only a result that actually EXECUTED, SUCCEEDED,
# was NOT blocked, and carries deliverable content is checked — a refusal/deny/block
# legitimately delivers a deterministic template and is never flagged. A paraphrased
# (non-verbatim) synthesis is NOT flagged (delivered text is non-empty + carries no
# deflection marker), so an honest summary never false-positives.
_DELIVERY_DEFLECTION_RE = re.compile(
    r"i\s+don'?t\s+have\s+(?:current\s+data|access|(?:the\s+)?(?:current|live|real[- ]?time)"
    r"\s+\w+)|i\s+can'?t\s+(?:verify|access|determine)\b|"
    r"without\s+(?:running|a\s+tool|current\s+data)\b|"
    r"i\s+have\s+not\s+(?:run|started|executed)\b",
    re.IGNORECASE)
# M7 leg 4: a THIRD dispatched-but-discarded shape the deflection regex missed — a
# successful dispatch whose delivered answer TEACHES the user to run the command
# ("here's how you'd check: `lpstat -p`") instead of REPORTING the result the
# dispatch already produced (2026-07-08 finding 3; PI-Z23 (e), the promise-shaped
# non-answer). The text is non-empty and non-deflecting, so it escaped M8-2; this
# closes the seam so it, too, is a NAMED, LOUD defect. High-precision: the markers
# address the USER with a run-it-yourself instruction ("here's how you'd", "you can
# run", "run the following") — a genuine result REPORT never instructs the user to
# run the command that already ran.
_DELIVERY_EXPLAIN_INSTEAD_RE = re.compile(
    r"here(?:['’]s| is)\s+how\s+(?:you(?:['’]d| would| can)?|to)\b"
    r"|you(?:['’]d| would)?\s+(?:can|could|should)?\s*(?:run|use|type)\s+"
    r"(?:the\s+)?(?:following\s+)?(?:command|`)"
    r"|to\s+(?:check|see|list|find\s+out|view|get)\b[^.?!]{0,40}?\b(?:run|use|type)\b"
    r"|run\s+the\s+following\b|try\s+running\b|you\s+can\s+use\s+the\s+command\b",
    re.IGNORECASE)


# ── Is the result ACTUALLY in the answer? (the precision half) ────────────────
# Measured on the whole-battery run at dev 601b2f790: both M8-2 warnings it
# emitted were about answers that CARRIED the dispatch result. do-for-me-04
# reported "441 active services are running." and then denied having the data;
# do-for-me-06 reported all five search results and then added one "you can use
# the `crontab` command" sentence. The text-shape tests above searched the whole
# answer for a marker and never asked whether the result was also in it, so a
# reported result plus one stray sentence read as a discarded result.
#
# WHY THIS TEST MAY ONLY EXCULPATE, NEVER ACCUSE. The docstring below records why
# token overlap cannot be used to DECLARE a dropped result: the memory and disk
# summarizers answer from an authoritative live source by ratified design and
# share no token with the tool result beside them, so a low-overlap rule would
# fire on correct answers. That argument is one-directional. HIGH overlap is
# still sound evidence that the value reached the answer, and using it only to
# withhold an accusation cannot manufacture a false one — the worst case is the
# pre-existing behaviour for an honest paraphrase, which was never flagged
# anyway.
#
# DELIBERATELY CONSERVATIVE. Whole-token matching only (so "printer" in a result
# is not evidenced by the word "printers" in a run-it-yourself sentence — the M7
# leg-4 fixtures depend on that), a distinctive-token floor of two, and a result
# carrying fewer than two distinctive tokens can never exculpate.
_RESULT_TOKEN_RE = re.compile(r"[A-Za-z]{5,}|\d{2,}")
_EVIDENCE_MIN_TOKENS = 2      # below this the answer is not evidence of anything
_EVIDENCE_MIN_RATIO = 0.25    # ... or a large absolute count, for long outputs
_EVIDENCE_ABS_TOKENS = 6


def _distinctive_tokens(text):
    """Lower-cased words of 5+ letters and numbers of 2+ digits, de-duplicated.

    Short words and single digits are dropped because they recur in ordinary
    prose ("the", "1"), and a match on them would be coincidence rather than
    evidence that a particular tool result reached a particular answer.
    """
    return {m.group(0).lower() for m in _RESULT_TOKEN_RE.finditer(text or "")}


def result_reached_text(result, delivered_text) -> bool:
    """True when the delivered answer demonstrably CARRIES this result's value.

    Used only to withhold a "the result did not reach the answer" finding, never
    to raise one — see the block comment above for why that direction is sound
    in this codebase and the other is not.
    """
    payload = (getattr(result, "content", "") or "") + " " + \
              (getattr(result, "model_summary", "") or "")
    tokens = _distinctive_tokens(payload)
    if len(tokens) < _EVIDENCE_MIN_TOKENS:
        return False
    present = tokens & _distinctive_tokens(delivered_text)
    if len(present) < _EVIDENCE_MIN_TOKENS:
        return False
    return (len(present) >= _EVIDENCE_ABS_TOKENS
            or len(present) / len(tokens) >= _EVIDENCE_MIN_RATIO)


# Which findings can be repaired by stating the result, and which may not be.
# "substituted" is absent on purpose: the linkage signal cannot separate a real
# substitution from a summarizer answering off an authoritative live source, so
# rewriting that class would overwrite correct answers. "contradicted_despite_
# result" is absent because the value is already in the answer — there is
# nothing to carry in, and the defect there is the denial beside it.
_REPAIRABLE_REASONS = frozenset({
    "empty_delivery", "deflection_despite_result", "explain_instead_of_result"})


def carry_result_into_answer(delivered_text, result, reason):
    """The answer a user should have received, or None to leave it alone.

    A successful dispatch's value is never discarded: when the model returned
    nothing, denied having the data, or taught the command instead of reporting
    it, the tool's own output IS the answer and is stated as the tool produced
    it.

    A denial is REPLACED rather than annotated — leaving "I don't have current
    data" above the data would manufacture exactly the self-contradiction that
    do-for-me-04 was flagged for. A teaching answer KEEPS its instructions below
    the result, because they are useful and are not a false statement about what
    the system knows.
    """
    if reason not in _REPAIRABLE_REASONS:
        return None
    payload = (getattr(result, "model_summary", "")
               or getattr(result, "content", "") or "").strip()
    if not payload:
        return None
    text = (delivered_text or "").strip()
    if reason == "explain_instead_of_result" and text:
        return f"{payload}\n\n{text}"
    return payload


def find_unconsumed_dispatches(delivered_text, tool_results, linkage=None):
    """M8-2 (+ M7 leg 4): return [(result, reason)] for each executed+successful
    dispatch whose value did NOT reach the delivered answer. Empty list == invariant
    holds.

    reason is "empty_delivery" (successful dispatch but a blank answer),
    "deflection_despite_result" (the answer deflects/denies data while a successful
    dispatch carrying content is in hand), "explain_instead_of_result" (M7 leg 4:
    the answer teaches the user to run the command instead of reporting its result),
    "contradicted_despite_result" (the answer STATES the result and then denies
    having the data — the value reached the answer, so this one is not a drop and
    is never repaired by restating it), or "substituted" (below). All are the dispatched-but-discarded class; the caller
    emits a named glass defect + a loud log line per problem.

    SUBSTITUTED (the fourth reason). The first three are TEXT SHAPES: they catch a
    reply that is blank, that denies having data, or that teaches instead of
    reporting. A reply that confidently states something ELSE is none of those, and
    was structurally invisible — a package dispatch rendered through a disk
    summarizer delivered "Disk usage is available." and tripped nothing, on any of
    the three delivery surfaces.

    It is caught here on the LINKAGE SIGNAL (``linkage``, an AnswerLinkage saying
    what the text was actually composed from), never on text overlap between the
    answer and the tool output. Overlap is unsound in this codebase: the memory and
    disk summarizers answer from an authoritative live source by ratified design and
    share no token with the tool result beside them, so an overlap test would fire
    on correct answers and teach everyone to ignore it.

    A successful dispatch is SUBSTITUTED when the linkage says the delivered text
    came from something else — cached state, a code-owned string, free model text,
    or a DIFFERENT dispatch than the one in hand. ``linkage=None`` means the
    composing site declared nothing; that is not evidence of substitution, so no
    reason is raised (the caller records the absent signal separately, so an
    uninstrumented path stays visible instead of silently exempt).
    """
    problems: list[tuple[object, str]] = []
    text = (delivered_text or "").strip()
    for r in (tool_results or []):
        if not (getattr(r, "executed", False)
                and getattr(r, "success", False)
                and not getattr(r, "blocked", False)):
            continue
        if not (getattr(r, "content", "") or getattr(r, "model_summary", "")):
            continue
        # Whether the value is in the answer decides which finding this is — a
        # marker beside a result that IS reported is not a discarded result.
        evidenced = result_reached_text(r, text)
        if not text:
            problems.append((r, "empty_delivery"))
        elif _DELIVERY_DEFLECTION_RE.search(text):
            # Evidenced: the answer states the result AND denies having it (the
            # do-for-me-04 shape) — a real defect, but a contradiction, not a
            # drop, and no repair can carry in what is already there.
            problems.append((r, "contradicted_despite_result" if evidenced
                             else "deflection_despite_result"))
        elif _DELIVERY_EXPLAIN_INSTEAD_RE.search(text):
            # Evidenced: the result is reported and the answer then teaches the
            # command as well (the do-for-me-06 shape). Nothing was discarded,
            # so nothing is flagged; the substitution test below is moot for the
            # same reason.
            if not evidenced:
                problems.append((r, "explain_instead_of_result"))
        elif _is_substituted(r, linkage):
            problems.append((r, "substituted"))
    return problems


def _is_substituted(result, linkage) -> bool:
    """True when ``linkage`` says the delivered text was NOT composed from
    ``result`` — the dispatch ran and something else was served in its place.

    Undeclared linkage returns False: absence of a signal is not evidence. A
    linkage that names a dispatch matches when it names THIS one; a call_id is
    compared when both carry one, so a route that records the tool but not the id
    still matches on the tool rather than raising a false substitution.
    """
    if linkage is None:
        return False
    if getattr(linkage, "kind", "") != "dispatch":
        return True
    call_id = getattr(linkage, "call_id", "") or ""
    r_call_id = getattr(result, "call_id", "") or ""
    if call_id and r_call_id:
        return call_id != r_call_id
    tool = getattr(linkage, "tool", "") or ""
    name = getattr(result, "name", "") or ""
    return bool(tool and name and tool != name)


# ── M4 capability-claim gate: checkable claims about OUR system are verified ──
# against ground truth before delivery (PI-Z23 b — the `pkm add` invention class).
#
# A CLAIM gate, not a topic gate (anti-lobotomy): the model keeps the WHOLE
# conversational surface; only a claim that INVOKES a pkm subcommand which does not
# exist is caught and re-grounded against the real parser surface. The valid set is
# DERIVED from data/capability-surface.json (introspected pkm argparse + intergen
# ToolRegistry) — no hand-kept copy to drift out of sync with the real parser
# (the drift finding).
#
# GROUND TRUTH ABSENT = FAIL LOUD, never silent (fail-loud rule, 2026-07-07; the
# installed-box no-data observation proved the failure mode is real). A missing /
# unreadable surface does NOT let the gate wave every draft through green — a silent
# no-op gate is a stub-shaped lie. Instead screen_capability_claim returns the
# distinct "unavailable" verdict so the router (a) emits a decision/capability_screen
# WARN row EVERY turn (the degradation is never silent) and (b) will not deliver an
# UNVERIFIABLE `pkm <sub>` claim as if verified — it serves the honest-under-
# uncertainty fallback. Dispatch stays LOCKED regardless; this is the grounding layer.
_CAP_SURFACE_PATH = Path(__file__).with_name("data") / "capability-surface.json"


@functools.lru_cache(maxsize=1)
def _pkm_surface() -> tuple[frozenset[str], tuple[str, ...]]:
    """(valid_names, primary_subcommands_sorted) from the surface artifact.
    valid_names includes aliases (for matching); primary is the subcommand keys
    (for the corrective note). Empty on a missing/broken artifact."""
    try:
        surf = json.loads(_CAP_SURFACE_PATH.read_text())
    except (OSError, ValueError) as e:
        # Ruling 2: ground truth absent is a LOUD degradation, not a silent no-op.
        # lru_cache means this journal breadcrumb fires once per process; the
        # per-turn glass WARN (router capability_screen "unavailable") is the SSoT.
        logger.warning("capability-surface.json unreadable (%s) — capability gate "
                       "DEGRADED: pkm claims cannot be verified until it ships at "
                       "%s", e, _CAP_SURFACE_PATH)
        return frozenset(), ()
    subs = surf.get("pkm", {}).get("subcommands", {})
    names: set[str] = set()
    for name, spec in subs.items():
        names.add(name)
        names.update(spec.get("aliases", []))
    if not names:
        logger.warning("capability-surface.json at %s has no pkm subcommands — "
                       "capability gate DEGRADED (unverifiable)", _CAP_SURFACE_PATH)
    return frozenset(names), tuple(sorted(subs.keys()))


# A `pkm <subcommand>` INVOCATION in the draft — high-precision so prose ("the pkm
# package manager") and package-name positions never match: only a backtick code
# span (`pkm add …`) or an imperative lead-in (run/use/type/try pkm add …). The
# subcommand is the first non-flag token after `pkm`; leading global flags are
# skipped.
_PKM_INVOKE_RE = re.compile(
    r"(?:`\s*|(?:\b(?:run|use|type|enter|execute|try|via|invoke|just\s+run|"
    r"command\s+is|command:)\s+))"
    r"pkm\s+(?:-{1,2}[a-z][\w-]*\s+)*([a-z][a-z0-9-]*)",
    re.IGNORECASE)
# Honest correction / negation guard: the model naming an invalid subcommand while
# DENYING it ("there is no `pkm add`", "not `pkm add` — use `pkm install`") is
# correct behavior and must never trip the gate (anti-lobotomy).
_CAP_NEGATORS = re.compile(
    r"\b(no|not|never|isn['’]t|aren['’]t|instead\s+of|rather\s+than|unlike|"
    r"avoid|there\s+is\s+no|there['’]s\s+no|no\s+such|don['’]t|doesn['’]t|"
    r"wouldn['’]t|can['’]t|cannot)\b", re.IGNORECASE)


def _find_pkm_invocation(text: str) -> tuple[str, str] | None:
    """First non-negated `pkm <subcommand>` invocation in text as (sub, "pkm sub"),
    or None. Validity is NOT judged here — the caller compares against the surface
    (fabrication) or, when the surface is missing, treats any hit as unverifiable.
    A negated/correcting window ("there is no `pkm add`") is skipped (anti-lobotomy)."""
    for m in _PKM_INVOKE_RE.finditer(text):
        window = text[max(0, m.start() - 48):m.start()]
        if _CAP_NEGATORS.search(window):
            continue
        sub = m.group(1).lower()
        return sub, f"pkm {sub}"
    return None


def screen_capability_claim(draft: str) -> tuple[str, str | None]:
    """M4 capability-claim gate. Three verdicts:
      ("clean", None)         — surface present; no fabricated pkm invocation.
      ("violation", "pkm X")  — surface present; X is not a real subcommand.
      ("unavailable", marker) — ground-truth surface MISSING/unreadable (Ruling 2:
                                the gate NEVER silently no-ops). marker is the
                                unverifiable "pkm X" phrase if the draft made one,
                                else None. The caller WARN-logs every turn and, for a
                                marker'd claim, serves the honest-under-uncertainty
                                fallback rather than deliver an unverified claim.
    The caller regenerates once (violation) with the real surface grounded in, else
    serves the deterministic honest fallback."""
    text = draft or ""
    hit = _find_pkm_invocation(text)
    valid, _ = _pkm_surface()
    if not valid:
        return ("unavailable", hit[1] if hit else None)
    if hit and hit[0] not in valid:
        return ("violation", hit[1])
    return ("clean", None)


def capability_grounding_note(marker: str | None = None) -> str:
    """Corrective note for regeneration: grounds the model in the REAL pkm
    subcommand surface so it drops the invented command. Derived from the surface
    (no hand-kept list)."""
    _, primary = _pkm_surface()
    listed = ", ".join(primary) if primary else (
        "install, remove, list, search, info, update, upgrade, verify")
    named = f" (`{marker}` is not one of them)" if marker else ""
    return ("InterGenOS's package manager, pkm, has a FIXED set of subcommands and "
            f"no others{named}. The real subcommands are: {listed}. To install "
            "software the command is `pkm install <package>`. Correct your answer "
            "to use only real pkm subcommands, and if the user is asking about "
            "something pkm does not do (e.g. a hardware change), say so plainly "
            "instead of inventing a command.")


def honest_capability_fallback(marker: str | None = None) -> str:
    """Deterministic non-fabricating reply if the model still invents a pkm
    subcommand after one corrective regeneration. Honesty over helpfulness."""
    _, primary = _pkm_surface()
    listed = ", ".join(primary) if primary else (
        "install, remove, list, search, info, update, upgrade, verify")
    return ("To be accurate: InterGenOS's package manager is pkm, and it has no "
            f"such command. Its real subcommands are: {listed}. To install "
            "software, use `pkm install <package>`.")


def capability_unverified_fallback(marker: str | None = None) -> str:
    """Ruling 2 degraded path: the capability ground-truth surface
    (data/capability-surface.json) is missing, so a `pkm <subcommand>` claim could
    not be verified either way. Honest UNDER UNCERTAINTY — assert neither existence
    nor non-existence; point the user at the authoritative source."""
    cmd = marker or "that pkm command"
    return ("I can't verify InterGenOS's exact pkm command surface right now — my "
            f"capability reference isn't loaded — so I won't claim `{cmd}` works "
            "without checking. Please confirm with `pkm --help`, which lists the "
            "real subcommands.")


def answer_command_capability_question(token: str) -> tuple[str, str | None]:
    """M8 wave 4: answer a how-to / capability QUESTION that names a `pkm <token>`
    command, GROUNDED against the same M4 surface (data/capability-surface.json) the
    claim gate uses — never a hand-kept list, never a misparse into a fabricated
    `pkm install <token>`, never absorbed as a preference. This is the UPSTREAM
    companion to screen_capability_claim: the gate catches a fabricated subcommand in
    a DELIVERED draft, but a question like "how do I use pkm add" is misrouted (to the
    explain path, which invented `pkm install to`, or to memory, which absorbed it as
    "you prefer pkm audit") BEFORE any draft is screened. Answering the question here,
    from ground truth, kills the misparse at the source.

    Returns (status, answer):
      ("exists", None)      — token is a REAL subcommand/alias; the caller keeps its
                              own teaching/explain path (this leg changes nothing for
                              valid commands).
      ("absent", text)      — token is NOT a real subcommand (e.g. add, audit); the
                              honest answer names the real subcommands + `pkm install`
                              and says there is no such command. NEVER emits
                              `pkm install <token>`.
      ("unavailable", text) — the ground-truth surface is missing/unreadable (Ruling 2
                              fail-loud); honest under uncertainty, asserts nothing.
    """
    valid, primary = _pkm_surface()
    if not valid:
        return ("unavailable", capability_unverified_fallback(f"pkm {token}"))
    if token in valid:
        return ("exists", None)
    listed = ", ".join(primary)
    answer = (
        f"InterGenOS's package manager is pkm, and there's no `pkm {token}` command. "
        f"Its real subcommands are: {listed}. To install a package, use "
        "`pkm install <package>` (for example, `pkm install firefox`); to remove one, "
        "`pkm remove <package>`. See `pkm --help` for the full list.")
    return ("absent", answer)


def get_blocked_response(command: str) -> str:
    """Get a personality-infused blocked response for a dangerous command."""
    cmd = os.path.basename(command.strip().split()[0]) if command.strip() else ""

    # Check for prompt injection patterns
    if any(p in command.lower() for p in ["[system]", "ignore your", "new instructions",
                                           "you are now", "admin mode"]):
        return random.choice(_BLOCKED_RESPONSES["_injection"])

    # Check for fork bomb
    if ":()" in command or ":|:" in command:
        return random.choice(_BLOCKED_RESPONSES[":(){ :|:& };:"])

    # L2 anti-fabrication: wrong package manager -> redirect to pkm, echoing the
    # intended action/packages so the model (and user) sees the correct command.
    if cmd in WRONG_PKG_MANAGERS:
        toks = command.strip().split()
        verb = _PKM_VERB.get(toks[1].lower()) if len(toks) > 1 else None
        pkgs = [t for t in toks[2:] if not t.startswith("-")] if len(toks) > 2 else []
        if verb and pkgs:
            return f"This system uses pkm, not {cmd}. Try `pkm {verb} {' '.join(pkgs)}`."
        if verb:
            return f"This system uses pkm, not {cmd}. Try `pkm {verb}`."
        return (f"This system's package manager is pkm, not {cmd}. "
                "See `pkm --help` (install / remove / search / list / info).")

    # F-038: iproute2-netlink tools can't run in the hardened assistant — their
    # AF_NETLINK socket is denied, so executing one would crash the helper
    # (SIGSYS) rather than return anything. Redirect to a netlink-free source.
    if cmd in _NETLINK_COMMANDS:
        return (
            f"`{cmd}` isn't available to the hardened assistant — it needs a "
            "netlink socket the sandbox denies, so running it would crash the "
            "helper rather than answer. For interface and address info, read "
            "/sys/class/net (e.g. `ls /sys/class/net`, "
            "`cat /sys/class/net/<iface>/address`, "
            "`cat /sys/class/net/<iface>/operstate`), or run the command "
            "yourself in a terminal."
        )

    # Match by base command
    if cmd in _BLOCKED_RESPONSES:
        return random.choice(_BLOCKED_RESPONSES[cmd])

    return random.choice(_BLOCKED_RESPONSES["_default"])


def sanitize_output(output: str, max_lines: int = 200,
                    max_chars: int = 8000) -> str:
    """Sanitize command output for LLM consumption.

    Strips ANSI escape codes and truncates long output.
    """
    output = re.sub(r"\x1b\[[0-9;]*[a-zA-Z]", "", output)
    output = re.sub(r"\x1b\][^\x07]*\x07", "", output)

    lines = output.splitlines()
    if len(lines) > max_lines:
        output = "\n".join(lines[:max_lines])
        output += f"\n\n[Output truncated — {len(lines)} lines total, showing first {max_lines}]"

    if len(output) > max_chars:
        output = output[:max_chars]
        output += "\n\n[Output truncated at character limit]"

    return output
