name: pinentry
version: "1.3.2"
release: 1
description: PIN/passphrase entry dialog
license: GPL-2.0-or-later
homepage: https://www.gnupg.org/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://www.gnupg.org/ftp/gcrypt/pinentry/pinentry-${version}.tar.bz2
  sha256: 8e986ed88561b4da6e9efe0c54fa4ca8923035c99264df0b0464497c5fb94e9e
dependencies:
  build:
  - libassuan
  - libgpg-error
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --enable-pinentry-tty
