# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
"""Bootloader installation for InterGenOS installer.

Two paths:
- BIOS legacy: install GRUB to MBR/GPT bios_grub partition (no Secure Boot).
- EFI: install signed boot chain (shim + GRUB signed with MOK + signed kernel).

The signed boot chain layout on the ESP:
  /boot/efi/EFI/InterGenOS/
    shimx64.efi       — Microsoft-signed shim (from shim-signed package)
    grubx64.efi       — Our GRUB, signed with the MOK private key
    mmx64.efi         — MokManager (from shim-signed; for first-boot enrollment)
    grub.cfg          — Generated by grub-mkconfig with os-prober enabled

Shim is registered as the primary UEFI boot entry. On boot:
  shim verifies grubx64.efi against the MOK enrolled at first boot
  (or against the embedded vendor cert if shim is from Fedora's piggyback build)
  -> GRUB loads, verifies kernel signature
  -> kernel boots, MODULE_SIG_FORCE=y rejects unsigned modules
"""

import logging
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from . import trace
from .hooks import (
    mount_efivars,
    unmount_efivars,
)
from .mok import sign_efi_binary

# Host-side path: shipped on every InterGenOS live ISO. Belt-suspenders
# below copies from HERE (host) to <target>/boot/grub/fonts/ so the
# font lands regardless of whether the target's grub package archive
# was rebuilt with the do_install do_install changes that ship
# /usr/share/grub/unicode.pf2 on the target itself.
HOST_GRUB_UNICODE_PF2 = Path("/usr/share/grub/unicode.pf2")

logger = logging.getLogger(__name__)


# Where shim-signed package installs its artifacts (provided by the package)
SHIM_SOURCE_DIR = "/usr/share/shim-signed"
SHIM_BINARY = "shimx64.efi"
MOKMANAGER_BINARY = "mmx64.efi"

# Where we write the signed boot chain on the ESP
ESP_BOOT_DIR = "/boot/efi/EFI/InterGenOS"
GRUB_BINARY = "grubx64.efi"
BOOTLOADER_ID = "InterGenOS"
GRUB_FORMAT = "x86_64-efi"

# Where the install-time answer to "should InterGenOS be the default boot
# target?" is recorded on the installed system. The boot-time checker
# (intergenos-bootorder-check, shipped by the forge package) reads it and
# repairs BootOrder only when this says the machine is meant to boot
# InterGenOS by default — so a user who deliberately kept another OS as the
# default is never overridden. Path is relative to the install target.
BOOT_DEFAULT_INTENT_REL = "etc/intergenos/boot-default.conf"

# EFI core-image module set. Lifted to a constant so the grub-install call and
# the grub-mkimage --sbat overlay (below) embed an identical capability set.
# This is the historical grub-install --modules list, verbatim.
GRUB_EFI_MODULES = (
    "all_video boot btrfs cat chain configfile echo efifwsetup efinet ext2 "
    "fat font gettext gfxmenu gfxterm gzio halt hfsplus iso9660 jpeg loadenv "
    "loopback linux ls lsefi lsefimmap lsefisystab lssal memdisk minicmd "
    "normal part_apple part_msdos part_gpt password_pbkdf2 png reboot regexp "
    "search search_fs_uuid search_fs_file search_label sleep smbios squash4 "
    "test true video xfs zfs zfscrypt zfsinfo"
)
# gettext + regexp (added 2026-07-19): the grub-mkconfig-generated ESP
# grub.cfg insmods both at runtime (gettext from 00_header's locale block;
# regexp from the resolution-matched background-PNG selector). Under Secure
# Boot, shim_lock categorically refuses module file-loads, so every insmod of
# a module absent from this baked list prints "prohibited by secure boot
# policy" at boot — and the regexp miss additionally made the background
# selector fall back silently on installed systems. The ISO's standalone
# grub already bakes regexp for the same selector; this restores parity.
# Found on the first ge9b-05 Secure-Boot boot, 2026-07-19.

# SBAT metadata embedded into the plain-EFI grub PE via grub-mkimage --sbat.
# Fedora's MS-signed shim 16.1 enforces SBAT and rejects a grub binary that
# carries no .sbat section (Verification Failed 0x1A). MUST stay byte-identical
# to the canonical packages/core/grub/sbat.csv — the file the *ISO* grub embeds
# via grub-mkstandalone --sbat — so installed-grub and ISO-grub carry the same
# SBAT generations. Enforced by tests/installer/test_grub_sbat_csv_matches.py
# (a byte-equality gate makes this tested duplicate's drift un-mergeable).
GRUB_SBAT_CSV = (
    "sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md\n"
    "grub,5,Free Software Foundation,grub,2.14,https://www.gnu.org/software/grub/\n"
    "grub.intergenos,1,InterGenOS Project,grub2,2.14-1.igos,"
    "https://github.com/InterGenJLU/intergenos\n"
)


def verify_shim_assets_present():
    """Pre-flight check: shim-signed binaries must exist in the live ISO.

    Called before partition_disk() on EFI installs (C-003 audit row;
    T0-2 closure dispatch 2026-05-18T20:25:59Z). Fails closed so a
    regression in the live-ISO build pipeline (e.g. shim-signed package
    not wired through chroot-build-core-extra.sh — A-001) is caught
    BEFORE the destructive partition write rather than after, when the
    target disk is already modified.

    Raises:
        RuntimeError if shimx64.efi or mmx64.efi are missing from
        SHIM_SOURCE_DIR.
    """
    missing = []
    for binary in (SHIM_BINARY, MOKMANAGER_BINARY):
        if not Path(SHIM_SOURCE_DIR, binary).is_file():
            missing.append(f"{SHIM_SOURCE_DIR}/{binary}")
    if missing:
        raise RuntimeError(
            "shim-signed binaries missing from live ISO: "
            + ", ".join(missing)
            + ". The shim-signed package is not wired into this build. "
            "Aborting BEFORE partitioning to preserve disk state. "
            "Re-run install on a build where the shim-signed package "
            "is wired through phase_image (audit row A-001)."
        )


# Host-side paths of the four kernel-lifecycle helpers on the live ISO.
# Since packages/core/linux-kernel r4 these are PACKAGE-OWNED — the kernel
# package installs them to /usr/lib/intergen/ and its verify_paths prove
# presence at the squashfs gate (finding #4: ge9b-01's live root lacked
# all four because the old chroot-phase staging was skipped by a resume
# topology). The target install therefore receives them from the package
# during PHASE_PACKAGES; the stage_uki_prereqs() copies below remain as
# belt-and-suspenders (the microcode helper is also EXECUTED host-side
# here, before the target's package set exists). A missing host copy is
# a live-media build regression — logged AND trace-evented so it appears
# in the install's forensic trace, not just the logger.
HOST_MICROCODE_HELPER = Path("/usr/lib/intergen/build-microcode-cpio.sh")

# FDE initramfs builder + its runtime entry point. Without these on the
# target, a LUKS install reaches the kernel hook's LUKS branch with
# build-fde-initramfs.sh absent and silently falls through to the stub
# initramfs, leaving the encrypted root unbootable. (Gap B Phase-D.)
HOST_FDE_BUILDER = Path("/usr/lib/intergen/build-fde-initramfs.sh")
HOST_FDE_INIT = Path("/usr/lib/intergen/fde-init.sh")

# Keep-N kernel retention helper. Without it the linux-kernel post-install
# hook logs "kernel retention helper absent" and never prunes superseded
# kernels, eventually exhausting /boot. (INTERNVL-PI-B.)
HOST_KERNEL_PRUNE = Path("/usr/lib/intergen/prune-old-kernels.sh")

# Minimum plausible size (bytes) for a real FDE initramfs section in the UKI.
# The plain-install stub is an empty gzipped cpio (~50 bytes, plus microcode
# cpios); a real FDE initramfs (busybox + cryptsetup-static + dm_crypt + storage
# modules) is multiple MB. 1 MiB cleanly separates stub from real.
FDE_INITRD_MIN_BYTES = 1 << 20


def stage_uki_prereqs(target):
    """Stage UKI build prerequisites onto /mnt/target BEFORE PHASE_PACKAGES.

    D-005 UKI primary path. The linux-kernel package's post_install hook
    (packages/core/linux-kernel/hooks/post-install.sh — runs inside the
    chroot during PHASE_PACKAGES) bundles five sections into the UKI:

        .linux    — the kernel image (always present)
        .cmdline  — sourced from /etc/kernel/cmdline (pre-staged by
                    install.py at PHASE_VIRTUAL_FS+ via
                    config.generate_kernel_cmdline)
        .osrel    — auto-generated by ukify from /etc/os-release
        .initrd   — bundled if /boot/initramfs.img exists
        .ucode    — bundled if /boot/{intel,amd}-ucode.img exist

    Without prereq staging, .initrd and .ucode are silently absent
    because their source files don't exist on /mnt/target until much
    later (or never on plain installs). Surfaced 2026-05-27 install #28
    trace: UKI shipped without .initrd or .ucode sections, anomaly A.

    Three prereqs land here, in order:

      1. /usr/lib/intergen/build-microcode-cpio.sh   — copied from live
         ISO so the kernel hook can regenerate cpios on every
         `pkm upgrade linux-kernel`. Becomes a permanent part of the
         installed system, not a one-time install-time artifact.
      2. /boot/intel-ucode.img + /boot/amd-ucode.img — generated by
         running the helper against the live ISO's /lib/firmware (which
         the build-microcode-cpio.sh reads, NOT the target's). Output
         lands on the target's /boot/ for the hook's `[ -f ]` checks.
      3. /boot/initramfs.img — minimal empty newc cpio (gzipped, ~52
         bytes). The kernel-builtin storage drivers + PARTUUID + rootwait
         handle the actual root mount on plain installs; the initramfs
         is a stub so ukify's --initrd= contract is satisfied and the
         UKI gets a .initrd section. LUKS installs replace this stub
         with the FDE initramfs at the kernel hook level (see
         packages/core/linux-kernel/hooks/post-install.sh: Phase D).
    """
    target_path = Path(target)
    target_intergen_dir = target_path / "usr/lib/intergen"
    target_boot = target_path / "boot"
    target_boot.mkdir(parents=True, exist_ok=True)

    # 1. Stage the microcode helper onto target
    target_helper = target_intergen_dir / "build-microcode-cpio.sh"
    if HOST_MICROCODE_HELPER.is_file():
        target_intergen_dir.mkdir(parents=True, exist_ok=True)
        trace.traced_copy_file(
            HOST_MICROCODE_HELPER, target_helper,
            phase="virtual_fs",
            intent="stage build-microcode-cpio.sh onto target so kernel "
                   "post_install hook (Forge install + pkm upgrade) can "
                   "regenerate /boot/{intel,amd}-ucode.img"
        )
        target_helper.chmod(0o755)
    else:
        logger.warning(
            "host %s missing; UKIs will lack .ucode sections until the "
            "helper is staged. Live-media build regression — "
            "packages/core/linux-kernel (r4+) ships it.",
            HOST_MICROCODE_HELPER,
        )
        trace.trace_event(
            "uki_prereq_source_missing",
            path=str(HOST_MICROCODE_HELPER),
            consequence="UKIs lack .ucode sections; no early-load microcode",
        )

    # 1b. Stage the FDE initramfs builder + runtime entry point onto the target
    # (Gap B). Unlike the microcode helper these are NOT package-shipped, so
    # without this a LUKS install reaches the kernel hook's LUKS branch with
    # build-fde-initramfs.sh absent -> the hook falls through to the stub
    # initramfs and the encrypted root never unlocks. Always staged (harmless on
    # plain installs; also lets a future `pkm upgrade linux-kernel` regenerate
    # the cpio against the new kernel's modules).
    for src in (HOST_FDE_BUILDER, HOST_FDE_INIT):
        if src.is_file():
            target_intergen_dir.mkdir(parents=True, exist_ok=True)
            dst = target_intergen_dir / src.name
            trace.traced_copy_file(
                src, dst, phase="virtual_fs",
                intent=f"stage {src.name} onto target so the kernel hook builds "
                       "the real FDE initramfs (LUKS unlock)",
            )
            dst.chmod(0o755)
        else:
            logger.warning(
                "host %s missing — a LUKS install's UKI will ship the stub "
                "initramfs and fail to unlock at boot. Live-media build "
                "regression (packages/core/linux-kernel r4+ ships it).", src,
            )
            trace.trace_event(
                "uki_prereq_source_missing",
                path=str(src),
                consequence="LUKS install ships stub initramfs; encrypted "
                            "root unbootable (FDE Gap B)",
            )

    # 1c. Stage the keep-N kernel retention helper onto the target (INTERNVL-PI-B).
    # Like the FDE helpers it is staged into the live ISO but NOT package-shipped,
    # so without this copy the linux-kernel post-install hook logs the helper as
    # absent and silently retains every old kernel (eventual /boot exhaustion) on
    # both Forge install and every future `pkm upgrade linux-kernel`.
    if HOST_KERNEL_PRUNE.is_file():
        target_intergen_dir.mkdir(parents=True, exist_ok=True)
        dst = target_intergen_dir / HOST_KERNEL_PRUNE.name
        trace.traced_copy_file(
            HOST_KERNEL_PRUNE, dst, phase="virtual_fs",
            intent="stage prune-old-kernels.sh onto target so the kernel "
                   "post-install hook prunes superseded kernels (keep-N "
                   "retention) on Forge install + every pkm upgrade linux-kernel",
        )
        dst.chmod(0o755)
    else:
        logger.warning(
            "host %s missing — the kernel hook will log the retention helper as "
            "absent and never prune old kernels. Live-media build regression "
            "(packages/core/linux-kernel r4+ ships it).", HOST_KERNEL_PRUNE,
        )
        trace.trace_event(
            "uki_prereq_source_missing",
            path=str(HOST_KERNEL_PRUNE),
            consequence="no keep-N kernel pruning; eventual /boot exhaustion",
        )

    # 2. Generate the microcode cpios on the target's /boot. Run the
    # host-side helper (NOT chroot exec) because the host live ISO has
    # iucode_tool + /lib/firmware/intel-ucode + /lib/firmware/amd-ucode,
    # while the target chroot at this point only has minimal contents.
    if HOST_MICROCODE_HELPER.is_file():
        env = {**os.environ, "OUTPUT_DIR": str(target_boot)}
        result = trace.traced_run(
            ["bash", str(HOST_MICROCODE_HELPER)],
            env=env,
            phase="virtual_fs",
            intent="generate /boot/{intel,amd}-ucode.img on target for "
                   "kernel hook UKI .ucode embedding",
        )
        if result.returncode != 0:
            logger.warning(
                "build-microcode-cpio.sh rc=%d: %s — UKI .ucode sections "
                "may be missing", result.returncode, result.stderr.strip(),
            )

    # 3. Minimal initramfs.img stub. Empty newc cpio piped through gzip
    # is the smallest valid cpio archive; the kernel's early-userspace
    # finds no /init and proceeds to mount root per cmdline. ukify
    # accepts it as --initrd= input and produces a .initrd section in
    # the UKI containing the stub bytes. LUKS installs overwrite this
    # with the FDE initramfs at hook fire time.
    initramfs = target_boot / "initramfs.img"
    if not initramfs.exists():
        result = trace.traced_run(
            ["bash", "-c",
             f"printf '' | cpio -o -H newc 2>/dev/null | "
             f"gzip > {initramfs}"],
            phase="virtual_fs",
            intent="generate minimal /boot/initramfs.img stub so kernel "
                   "hook's ukify --initrd= contract is met (plain install; "
                   "LUKS installs replace this with the FDE initramfs)",
        )
        if result.returncode != 0:
            logger.warning(
                "minimal initramfs.img generation rc=%d: %s",
                result.returncode, result.stderr.strip(),
            )


# Path on the target where the kernel post_install hook writes its
# diagnostic log. ingest_kernel_hook_log() reads this after PHASE_PACKAGES
# and emits its contents as structured trace events so the Forge install
# log captures the hook's ukify output verbatim.
KERNEL_HOOK_LOG = Path("var/log/intergen-kernel-postinstall.log")


def ingest_kernel_hook_log(target):
    """Emit `kernel_hook_log_*` trace events from the kernel hook's logfile.

    The linux-kernel post_install hook runs inside the chroot during
    PHASE_PACKAGES. Its stdout/stderr is captured by pkm into the
    package_install event's `message` field, BUT only the first hook's
    one-line "OK" summary is captured — the ukify invocation's output
    (cmdline + ukify stdout + UKI section audit) is written to the
    hook's own logfile and never reaches Forge's trace.

    This helper, called from install.py after PHASE_PACKAGES completes,
    reads the logfile and emits its contents as structured trace events.
    Result: the Forge install log now shows exactly which ukify args
    fired, what ukify produced, and which UKI sections were embedded.
    Surfaced 2026-05-27 install #28 anomaly A: UKI missing sections but
    no trace surfaced why because hook output was swallowed.

    Idempotent and fail-open: missing logfile or read failure emits a
    sentinel event and returns; never raises into the install pipeline.
    """
    logfile = Path(target) / KERNEL_HOOK_LOG
    if not logfile.exists():
        trace.trace_event("kernel_hook_log_absent", path=str(logfile))
        return

    try:
        content = logfile.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        trace.trace_event(
            "kernel_hook_log_read_failed",
            path=str(logfile), error=str(exc),
        )
        return

    lines = content.splitlines()
    trace.trace_event(
        "kernel_hook_log_begin",
        path=str(logfile),
        size_bytes=len(content),
        line_count=len(lines),
    )
    for line in lines:
        trace.trace_event("kernel_hook_log_line", text=line)
    trace.trace_event("kernel_hook_log_end", path=str(logfile))


def rebuild_fde_uki(target, partitions):
    """Rebuild the kernel UKI with the REAL FDE initramfs, after crypttab exists.

    Gap B (FDE Phase-D completion). The linux-kernel post_install hook builds the
    UKI during PHASE_PACKAGES, but /etc/crypttab is not written until PHASE_CONFIG
    — so on a LUKS install the first UKI ships the ~50-byte STUB initramfs
    (IS_LUKS_INSTALL=no at hook-fire time) and cannot unlock the root at boot.

    Re-running the hook here in PHASE_BOOTLOADER — AFTER config.generate_crypttab
    wrote /etc/crypttab AND stage_uki_prereqs staged build-fde-initramfs.sh +
    fde-init.sh — makes the hook take its LUKS branch: it builds the real FDE
    initramfs (fde-init.sh + busybox.static + cryptsetup-static + dm_crypt +
    storage drivers) and rebuilds + MOK-signs the UKI bundling it. The hook owns
    all UKI-build logic; this only re-invokes it at the right time (no duplicated
    logic), then VERIFIES the rebuilt UKI carries a real (non-stub) initramfs.

    LUKS installs only (no-op otherwise). Runs before the PHASE_HOOKS checksum
    reconcile so the rebuilt UKI/kernel state is reconciled. Fail-closed: a LUKS
    UKI that can't unlock is worse than a halted install, so any failure raises
    here (where the cause is clear) rather than at the user's first boot.
    """
    if not partitions.get("luks_enabled"):
        return

    hook_rel = "var/lib/pkm/hooks/linux-kernel/post-install"
    if not (Path(target) / hook_rel).is_file():
        raise trace.install_failure(
            where="bootloader.py:rebuild_fde_uki",
            why=(f"LUKS install but the kernel post-install hook (/{hook_rel}) "
                 "is missing on the target, so the FDE UKI cannot be rebuilt — "
                 "the encrypted root would never unlock at boot. The "
                 "linux-kernel package must ship this hook."),
            extra={"hook": hook_rel},
        )

    rc, _, stderr = trace.traced_run_chroot(target,
        "PKM_PACKAGE_NAME=linux-kernel PKM_PACKAGE_VERSION=fde-rebuild "
        f"bash /{hook_rel}",
        phase="bootloader",
        intent="re-run linux-kernel post-install hook after /etc/crypttab exists "
               "so the UKI bundles the real FDE initramfs (Gap B Phase-D)",
    )
    # Surface the hook's own ukify/FDE log into the Forge trace either way.
    ingest_kernel_hook_log(target)
    if rc != 0:
        raise RuntimeError(
            f"FDE UKI rebuild (kernel hook re-run) failed rc={rc}: {stderr}"
        )

    # Verify the rebuilt UKI actually carries a real FDE initramfs, not the stub.
    uki_dir = Path(target) / "boot/efi/EFI/Linux"
    ukis = sorted(uki_dir.glob("intergenos-*.efi")) if uki_dir.is_dir() else []
    if not ukis:
        raise trace.install_failure(
            where="bootloader.py:rebuild_fde_uki",
            why=("LUKS install: no UKI at /boot/efi/EFI/Linux after the FDE "
                 "rebuild — the encrypted root cannot boot."),
            extra={"uki_dir": str(uki_dir)},
        )
    uki = ukis[-1]
    rc, out, _ = trace.traced_run_chroot(target,
        f"objcopy -O binary --only-section=.initrd "
        f"/boot/efi/EFI/Linux/{uki.name} /tmp/igos-fde-initrd-check && "
        "stat -c %s /tmp/igos-fde-initrd-check; "
        "rm -f /tmp/igos-fde-initrd-check",
        phase="bootloader",
        intent="verify the rebuilt LUKS UKI carries a real (non-stub) FDE initramfs",
    )
    try:
        initrd_bytes = int(out.strip().splitlines()[-1])
    except (ValueError, IndexError):
        initrd_bytes = -1
    if initrd_bytes < FDE_INITRD_MIN_BYTES:
        raise trace.install_failure(
            where="bootloader.py:rebuild_fde_uki",
            why=(f"LUKS install: the rebuilt UKI ({uki.name}) still carries a "
                 f"stub/empty initramfs (.initrd={initrd_bytes} bytes, need "
                 f">={FDE_INITRD_MIN_BYTES}). The FDE initramfs build did not "
                 "run — check build-fde-initramfs.sh + cryptsetup-static + "
                 "busybox.static + /etc/crypttab on the target. The encrypted "
                 "root would not unlock at boot; halting the install here."),
            extra={"uki": uki.name, "initrd_bytes": initrd_bytes},
        )
    logger.info("FDE UKI rebuilt with real initramfs (%d bytes): %s",
                initrd_bytes, uki.name)


def install_bootloader(target, disk, partitions, mok_keypair=None,
                       detect_other_oses=True, make_default_boot=True):
    """Install bootloader on the target system.

    Args:
        target: target root path
        disk: disk device (e.g., /dev/sda or /dev/nvme0n1)
        partitions: dict from disks.partition_disk()
        mok_keypair: dict from mok.generate_mok_keypair() with key_path/cert_path.
                     Required for EFI installs (signed boot chain).
                     Ignored for BIOS installs.
        detect_other_oses: Option C 2026-05-24 — user's install-time
                     choice on whether GRUB should run os-prober to
                     detect other OSes (Windows alongside install, other
                     Linux distros on adjacent partitions). The same
                     value is written permanently to /etc/default/grub
                     by config.generate_grub_defaults so kernel updates
                     reproduce the install-time setting. Default True.
        make_default_boot: D1 / work-plan 1.25 — user's install-time choice
                     on whether InterGenOS should become the default UEFI
                     boot target. Only consulted on EFI installs that detect
                     a foreign installed-OS boot entry; a single-OS install
                     keeps the efibootmgr --create prepend regardless (nothing
                     to respect). Default True preserves the historical prepend
                     for callers that don't thread the choice (e.g. BIOS, tests).

    Raises:
        RuntimeError if any step fails.
        ValueError if EFI install requested without mok_keypair.
    """
    target = str(target)
    efi = partitions.get("efi", False)

    if efi and mok_keypair is None:
        raise ValueError(
            "EFI install requires mok_keypair from mok.generate_mok_keypair() "
            "to sign the GRUB binary"
        )

    # C-006: orchestrator (install.py PHASE_VIRTUAL_FS) owns virtual_fs
    # lifecycle. This function runs between PHASE_VIRTUAL_FS and
    # PHASE_CLEANUP so /dev /proc /sys /run /dev/pts are already bind-
    # mounted into target; re-mounting here stacks them and leaks on
    # cleanup (unmount only removes the top layer).
    if efi:
        _install_signed_efi_chain(target, partitions, mok_keypair,
                                  make_default_boot=make_default_boot)
    else:
        _install_bios_grub(target, disk)

    # Generate GRUB config (both modes).
    # The one-shot env-var here matches what config.generate_grub_defaults
    # wrote to /etc/default/grub. Without the env-var, this first
    # grub-mkconfig would read the just-written file and produce the
    # same result; the env-var is belt-and-suspenders for the unusual
    # case where this call somehow precedes the config write. Either
    # way: install-time setting + every-kernel-update setting are now
    # consistent (was a real defect pre-Option-C: install-time runs
    # with =false override, post-install kernel updates run with the
    # file's hardcoded =false → Windows entry persisted as expected;
    # but if the file had said =true, Windows would have vanished on
    # the first kernel update. Threading detect_other_oses through both
    # paths eliminates that class of asymmetry).
    os_prober_value = "false" if detect_other_oses else "true"
    # EFI installs: the menu grub.cfg lives on the unencrypted ESP
    # (/EFI/InterGenOS/grub.cfg), NOT /boot/grub on the root fs. On FDE installs
    # the root fs is LUKS-encrypted and the installed grub (no GRUB argon2id
    # support) cannot read it — so grub's config + assets must live on the ESP.
    # The core image's prefix points at the ESP (_grub_mkimage_sbat_efi) and
    # _stage_grub_assets_to_esp (below) copies the font/theme/module dir there,
    # so grub touches NOTHING on the root fs. The UKI is already on the ESP
    # (/EFI/Linux) and 06_uki chainloads it ESP-relative. BIOS keeps /boot/grub.
    # grub-mkconfig (os-prober + 06_uki + theme) remains the single menu source;
    # only its output location moves. (Plain installs use the same ESP path —
    # uniform, and re-validated alongside FDE.)
    grub_cfg_out = (
        "/boot/efi/EFI/InterGenOS/grub.cfg" if efi else "/boot/grub/grub.cfg"
    )
    rc, _, stderr = trace.traced_run_chroot(target,
        f"GRUB_DISABLE_OS_PROBER={os_prober_value} grub-mkconfig -o {grub_cfg_out}"
    )
    if rc != 0:
        raise RuntimeError(f"grub-mkconfig failed: {stderr}")

    # grub-mkconfig's 00_header emits `set theme=` ONLY when [ -f "$GRUB_THEME" ]
    # holds at mkconfig time. On an EFI/FDE install GRUB_THEME is the ESP-relative
    # /EFI/InterGenOS/themes/intergenos/theme.txt (config.py), which does NOT
    # resolve here in the chroot — so 00_header silently drops the directive and
    # the installed menu renders unthemed (GBC004.3 A12, 2026-06-22). Inject a
    # RUNTIME-guarded `set theme=` (grub evaluates -e at boot against the staged
    # ESP theme), mirroring the working installer/iso/grub/grub.cfg.
    _inject_grub_theme(grub_cfg_out, target)

    # Belt-and-suspenders: ensure /boot/grub/fonts/unicode.pf2 exists.
    # The generated grub.cfg unconditionally calls `terminal_output
    # gfxterm` after an `if loadfont unicode; then insmod gfxterm; fi`
    # block. If unicode.pf2 is absent, gfxterm activates without a
    # font and renders every character as the missing-glyph placeholder
    # — on x86_64 EFI gfxterm this manifests as a whole screen of "?"-
    # in-tofu-boxes (loadfont silently failed and gfxterm couldn't
    # resolve any glyphs), making the menu completely unreadable.
    # Surfaced 2026-05-26 install attempt #21 first-boot triage.
    #
    # Refactor 2026-05-27: copy from HOST (live ISO) not TARGET (chroot).
    # The earlier chroot belt-suspenders checked target's
    # /usr/share/grub/unicode.pf2 — but the target's grub package
    # archive may not ship the font (the do_install changes in 73011b57
    # only land if the grub archive was rebuilt). Install #23 hit
    # exactly this gap: chroot test -f failed, install skipped, fonts
    # dir empty, tofu boxes. Host-side copy works regardless of grub
    # package state because the live ISO always ships unicode.pf2 at
    # /usr/share/grub/.
    if HOST_GRUB_UNICODE_PF2.exists():
        target_font = Path(target) / "boot/grub/fonts/unicode.pf2"
        trace.traced_copy_file(
            HOST_GRUB_UNICODE_PF2, target_font,
            phase="bootloader",
            intent="ship unicode.pf2 to target /boot/grub/fonts/ so "
                   "GRUB loadfont succeeds + gfxterm renders ASCII",
        )
        target_font.chmod(0o644)
    else:
        # Should be impossible on a real live ISO; raise so the failure
        # surfaces here (where the cause is clear) instead of at first
        # boot where the operator sees only a screen of "?" tofu boxes
        # and no useful diagnostic.
        raise trace.install_failure(
            where="bootloader.py:install_bootloader / unicode.pf2 belt-suspenders",
            why=(f"host {HOST_GRUB_UNICODE_PF2} missing. Live ISO build "
                 "must ship grub package + grub-mkfont-generated font. "
                 "Without this, GRUB at first boot renders the whole "
                 "menu as missing-glyph tofu boxes (loadfont silently "
                 "fails, gfxterm activates without a font)."),
            extra={"host_path": str(HOST_GRUB_UNICODE_PF2)},
        )

    # EFI installs: replicate grub's runtime assets onto the unencrypted ESP so
    # the ESP-prefixed core image loads them without touching the (FDE-encrypted)
    # root fs. Runs after grub-install populated /boot/grub/x86_64-efi and the
    # font belt-suspenders guaranteed /boot/grub/fonts/unicode.pf2.
    if efi:
        _stage_grub_assets_to_esp(target)


def _install_signed_efi_chain(target, partitions, mok_keypair,
                              make_default_boot=True):
    """EFI install with signed boot chain (shim + signed GRUB).

    make_default_boot: D1 / work-plan 1.25 — see install_bootloader. Governs
    whether InterGenOS keeps efibootmgr --create's default-boot prepend when a
    foreign installed-OS entry is present.
    """
    esp_mount = f"{target}/boot/efi"
    Path(esp_mount).mkdir(parents=True, exist_ok=True)

    # Mount ESP if not already mounted
    if partitions.get("esp"):
        subprocess.run(
            f"mountpoint -q {esp_mount} || mount {partitions['esp']} {esp_mount}",
            shell=True, capture_output=True
        )

    # Install GRUB to a staging location (we'll sign and copy to ESP manually).
    # --no-nvram: we register the boot entry via efibootmgr against shim, not GRUB.
    # --modules: include modules needed for our boot (ext4, normal, etc.).
    #
    # --boot-directory MUST point at the unencrypted ESP, not its default /boot.
    # On an FDE install /boot lives on the LUKS-encrypted root, so grub-install's
    # internal grub-probe walks the dm-crypt mapping (named `cryptroot`) and
    # misclassifies it as an LVM volume group — aborting rc=1 with
    # "Volume group 'cryptroot' not found / disk 'lvm/cryptroot' not found"
    # BEFORE any ESP logic runs (FDE GAP, A12 GBC004.2 2026-06-21). Pointing
    # --boot-directory at /boot/efi probes the FAT ESP instead (probe-safe) and
    # is design-consistent with the ESP-resident grub layout below: grub reads
    # its config + assets from the unencrypted ESP, never the encrypted root.
    # grub-install then lands its runtime dir (modules + grubenv) at
    # /boot/efi/grub/<fmt>; _stage_grub_assets_to_esp copies those modules to the
    # core image's ESP prefix (/EFI/InterGenOS/<fmt>). Uniform for plain + FDE;
    # the grub-mkimage SBAT overwrite below points the prefix at the ESP either
    # way. Proven end-to-end on the A12 (HP/AMD, plain-LUKS) 2026-06-21.
    rc, _, stderr = trace.traced_run_chroot(target,
        "grub-install --target=x86_64-efi "
        "--efi-directory=/boot/efi "
        "--boot-directory=/boot/efi "
        f"--bootloader-id={BOOTLOADER_ID} "
        "--no-nvram "
        f"--modules='{GRUB_EFI_MODULES}'",
        phase="bootloader",
        intent="grub-install: stage EFI image + populate /boot/efi/grub modules "
               "(--boot-directory=ESP so grub-probe stays off the encrypted "
               "root on FDE installs)",
    )
    if rc != 0:
        raise RuntimeError(f"grub-install staging failed: {stderr}")

    # SecureBoot/SBAT (2026-06-21): grub-install in GRUB 2.14 cannot embed SBAT,
    # and Fedora's MS-signed shim 16.1 ENFORCES it — so the grubx64.efi
    # grub-install just produced (no .sbat section) is rejected with
    # "Verification Failed (0x1A)". shim verifies grub's SBAT BEFORE grub does
    # any disk I/O, so this applies to EVERY EFI install — we OVERWRITE
    # grub-install's binary with a grub-mkimage --sbat build unconditionally.
    # grub-mkimage is the only correct path: adding .sbat post-hoc with objcopy
    # corrupts the PE → shim 0x3 Unsupported. The existing MOK-sign + EFI/BOOT
    # mirror below carry the SBAT binary through. Validated end-to-end under
    # enforced SB on a plain ext4 install (2026-06-21, VMware).
    _grub_mkimage_sbat_efi(target, partitions)

    # Sign the staged GRUB binary with the MOK key
    grub_efi_chroot_path = f"{ESP_BOOT_DIR}/{GRUB_BINARY}"
    sign_efi_binary(
        target,
        binary_path=grub_efi_chroot_path,
        key_path=mok_keypair["key_path"],
        cert_path=mok_keypair["cert_path"],
    )

    # Copy shim + MokManager from shim-signed package to ESP
    rc, _, stderr = trace.traced_run_chroot(target,
        f"mkdir -p {ESP_BOOT_DIR} && "
        f"cp {SHIM_SOURCE_DIR}/{SHIM_BINARY} {ESP_BOOT_DIR}/ && "
        f"cp {SHIM_SOURCE_DIR}/{MOKMANAGER_BINARY} {ESP_BOOT_DIR}/"
    )
    if rc != 0:
        raise RuntimeError(f"shim staging to ESP failed: {stderr}")

    # Fallback auto-discovery path: some older UEFI firmware only looks at
    # /EFI/BOOT/bootx64.efi when no matching UEFI boot variable is registered.
    # Mirror the MS-signed shim, the MOK-signed GRUB, AND MokManager there so
    # the chain is self-contained — shim stays signed by MS so SecureBoot
    # validation passes, and it finds grubx64.efi in the same directory.
    # MokManager is NOT optional here: shim only looks for mmx64.efi in the
    # directory it was launched from, and with a MokNew enrollment pending a
    # shim that cannot find it HARD-FAILS ("MOK Manager not found") — the
    # ge9b-04 dogfood box bootlooped on its first SB reboot exactly because
    # its firmware takes this fallback path on default boot and only
    # shim+grub were mirrored (PI-ge9b04-A, installed-side leg).
    rc, _, stderr = trace.traced_run_chroot(target,
        f"mkdir -p /boot/efi/EFI/BOOT && "
        f"cp {ESP_BOOT_DIR}/{SHIM_BINARY} /boot/efi/EFI/BOOT/bootx64.efi && "
        f"cp {ESP_BOOT_DIR}/{GRUB_BINARY} /boot/efi/EFI/BOOT/{GRUB_BINARY} && "
        f"cp {ESP_BOOT_DIR}/{MOKMANAGER_BINARY} /boot/efi/EFI/BOOT/{MOKMANAGER_BINARY}"
    )
    if rc != 0:
        raise RuntimeError(f"EFI/BOOT fallback staging failed: {stderr}")

    # Sign every /boot/vmlinuz-* kernel image with the MOK. This closes
    # the middle link in the v2 playbook's 3-check signature chain:
    #   shim → GRUB (signed above)
    #   GRUB → kernel (signed here)
    #   kernel → modules (MODULE_SIG_FORCE ephemeral sig at build time)
    # Without this, GRUB with check_signatures=enforce refuses to load
    # the kernel. Even with check_signatures=off, leaving the kernel
    # unsigned means we don't detect tampered kernel images.
    #
    # Safety notes:
    #   - sbverify --list pre-check makes the loop idempotent on install
    #     retry — already-signed kernels are skipped rather than re-signed
    #     (behavior of re-signing varies across sbsigntools versions:
    #     some replace the signature, some append, some refuse).
    #   - sbsign writes to $k.new then renames — explicit atomicity
    #     regardless of sbsigntools version. A crash mid-write leaves
    #     the pre-signed kernel intact, not a truncated binary.
    rc, _, stderr = trace.traced_run_chroot(target,
        f"for k in /boot/vmlinuz-*; do "
        f"  [ -f \"$k\" ] || continue; "
        f"  if sbverify --cert {mok_keypair['cert_path']} \"$k\" >/dev/null 2>&1; then "
        f"    echo \"skipping $k (already signed with MOK)\"; "
        f"    continue; "
        f"  fi; "
        f"  sbsign --key {mok_keypair['key_path']} "
        f"--cert {mok_keypair['cert_path']} "
        f"--output \"$k.new\" \"$k\" || exit 1; "
        f"  mv \"$k.new\" \"$k\" || exit 1; "
        f"done"
    )
    if rc != 0:
        raise RuntimeError(f"kernel image signing failed: {stderr}")

    # Register shim as the primary UEFI boot entry via efibootmgr.
    # The disk + partition number come from partitions['esp'].
    #
    # efibootmgr requires /sys/firmware/efi/efivars inside the chroot to
    # write firmware boot variables. The host-booted-EFI case (USB installer)
    # has efivars available; bind-mount it in. The build-VM case (no UEFI
    # firmware) falls back to the soft-warn path with user-recovery guidance.
    esp_dev = partitions.get("esp", "")
    disk_dev, part_num = _split_partition(esp_dev)

    efivars_ok = mount_efivars(target)
    try:
        # D1 / work-plan 1.25: snapshot foreign installed-OS entries BEFORE our
        # cleanup+create so we know whether this machine already had another OS
        # as a boot target. On a multi-OS machine efibootmgr --create's
        # unconditional BootOrder prepend silently makes InterGenOS the default
        # — a user-control violation — so we consult the user's choice below.
        _pre_order, _pre_entries = _parse_efibootmgr_output(
            trace.traced_run_chroot(target, "efibootmgr")[1]
        )
        foreign_before = _foreign_os_bootnums(_pre_entries, BOOTLOADER_ID)

        # Cleanup BEFORE --create so re-installs onto the same machine
        # don't accumulate stale "InterGenOS" entries in NVRAM. 2026-05-27
        # install #28 trace showed five stale Boot000{2,3,4,5} entries
        # from prior installs alongside the newly-created Boot0006 — each
        # install added one without removing duplicates (anomaly D).
        _cleanup_stale_efi_entries(target, BOOTLOADER_ID)

        rc, _, stderr = trace.traced_run_chroot(target,
            f"efibootmgr --create --disk {disk_dev} --part {part_num} "
            f"--label '{BOOTLOADER_ID}' "
            f"--loader '\\EFI\\InterGenOS\\{SHIM_BINARY}'"
        )

        # Honor the default-boot-target choice (only reorders when a foreign OS
        # entry existed AND the user declined; otherwise keeps the prepend).
        if rc == 0:
            _apply_default_boot_choice(target, make_default_boot, foreign_before)
            # Read NVRAM back and record what the firmware actually holds.
            # Everything above states an INTENT; until this read, nothing
            # checked that the intent survived the write.
            _verify_bootorder_end_state(
                target, expect_default=(make_default_boot or not foreign_before)
            )
        # Record the intent on the target regardless of the efibootmgr rc: the
        # boot-time checker needs to know what this install meant even when
        # NVRAM could not be written here (the fallback path below).
        _write_boot_default_intent(
            target,
            expect_default=(make_default_boot or not foreign_before),
            foreign_before=foreign_before,
        )
    finally:
        if efivars_ok:
            unmount_efivars(target)

    if rc != 0:
        # Two legitimate failure modes here:
        #   (1) Host has no EFI firmware (build VM). efivars_ok is False above;
        #       user must rely on /EFI/BOOT/bootx64.efi auto-discovery.
        #   (2) Host IS EFI but efibootmgr still failed (read-only efivars,
        #       firmware bug, etc.). User can retry manually post-boot.
        #
        # Fallback path: /EFI/BOOT/bootx64.efi auto-discovery works on most
        # firmware. On older/custom firmware that doesn't auto-discover,
        # the logged command below lets the user register by hand.
        host_efi_note = (
            "host has no EFI firmware — expected in build VM"
            if not efivars_ok
            else "host is EFI but efibootmgr still failed"
        )
        logger.warning(
            "efibootmgr registration failed (rc=%d, %s): %s. "
            "UEFI boot order NOT updated by installer. The EFI/BOOT/bootx64.efi "
            "fallback still allows auto-discovery on next boot. "
            "To register manually post-install: sudo efibootmgr --create "
            "--disk %s --part %d --label '%s' --loader '\\EFI\\InterGenOS\\%s'",
            rc, host_efi_note, stderr.strip(),
            disk_dev, part_num, BOOTLOADER_ID, SHIM_BINARY,
        )


def _grub_mkimage_sbat_efi(target, partitions):
    """Rebuild grubx64.efi with grub-mkimage --sbat + an ESP-resident prefix.

    Two jobs, both required for a Secure-Boot- and FDE-capable boot:

    1. SBAT: grub-install (GRUB 2.14) cannot embed an SBAT section, which shim
       16.1 enforces (rejects with 0x1A). This OVERWRITES grub-install's
       SBAT-less grubx64.efi with a grub-mkimage --sbat build. grub-mkimage is
       the only correct path — adding .sbat post-hoc with objcopy corrupts the
       PE (shim 0x3). Validated end-to-end on a plain ext4 install (2026-06-21).

    2. ESP-resident prefix: the embedded config locates the ESP by filesystem
       UUID, sets grub's root + prefix to our ESP dir, and loads the menu
       grub.cfg from the ESP (/EFI/InterGenOS/grub.cfg). This is what lets FDE
       installs boot: the InterGenOS layout has no separate /boot, so /boot/grub
       is on the LUKS-encrypted root, and GRUB (no argon2id support) cannot read
       it. With the prefix + grub.cfg + assets all on the unencrypted ESP
       (staged by _stage_grub_assets_to_esp) and the UKI already on the ESP
       (chainloaded by /etc/grub.d/06_uki), grub never touches the encrypted
       root. Uniform for plain + FDE; install-alongside-safe (UUID, not a baked
       partition number).

    Fails closed if the ESP UUID can't be resolved — never silently ship a grub
    with an unresolvable prefix (would yield an unbootable system).
    """
    esp_dev = partitions.get("esp")
    if not esp_dev:
        raise RuntimeError(
            "grub-mkimage SBAT: no 'esp' device in the partition layout"
        )

    blk = subprocess.run(
        ["blkid", "-s", "UUID", "-o", "value", esp_dev],
        capture_output=True, text=True,
    )
    esp_uuid = blk.stdout.strip() if blk.returncode == 0 else ""
    if not esp_uuid:
        raise RuntimeError(
            f"grub-mkimage SBAT: could not resolve the ESP fs UUID for "
            f"{esp_dev} (blkid rc={blk.returncode}). Refusing to build a grub "
            "image with an unresolvable prefix — would yield an unbootable "
            "system. Aborting before signing."
        )

    # Embedded early config (baked into the signed PE): locate the ESP by its
    # FAT fs UUID, point grub's root + prefix at our ESP dir, and load the menu
    # grub.cfg from there. Nothing here reads the (FDE-encrypted) root fs.
    load_cfg = (
        f"search --no-floppy --fs-uuid --set=root {esp_uuid}\n"
        f"set prefix=($root)/EFI/{BOOTLOADER_ID}\n"
        f"configfile ($root)/EFI/{BOOTLOADER_ID}/grub.cfg\n"
    )
    trace.traced_write_file(
        Path(target) / "tmp/igos-grub-load.cfg", load_cfg,
        phase="bootloader",
        intent="grub-mkimage early config: locate ESP by UUID, set prefix, "
               "configfile the ESP grub.cfg",
    )
    trace.traced_write_file(
        Path(target) / "tmp/igos-grub-sbat.csv", GRUB_SBAT_CSV,
        phase="bootloader",
        intent="SBAT metadata for grub-mkimage (shim 16.1 enforces SBAT)",
    )

    rc, _, stderr = trace.traced_run_chroot(target,
        f"mkdir -p {ESP_BOOT_DIR} && "
        f"grub-mkimage -O {GRUB_FORMAT} -o {ESP_BOOT_DIR}/{GRUB_BINARY} "
        f"-p /EFI/{BOOTLOADER_ID} -c /tmp/igos-grub-load.cfg "
        "--sbat /tmp/igos-grub-sbat.csv "
        f"{GRUB_EFI_MODULES}",
        phase="bootloader",
        intent="build SecureBoot-correct grubx64.efi with embedded SBAT "
               "(overwrites grub-install's SBAT-less image)",
    )
    if rc != 0:
        raise RuntimeError(f"grub-mkimage (SBAT) failed: {stderr}")

    # Fail-closed verify: the .sbat section MUST be present + non-empty, else
    # shim would reject the (about-to-be-MOK-signed) binary at boot with 0x1A.
    rc, _, stderr = trace.traced_run_chroot(target,
        f"objcopy -O binary --only-section=.sbat {ESP_BOOT_DIR}/{GRUB_BINARY} "
        "/tmp/igos-grub-sbat-check && test -s /tmp/igos-grub-sbat-check",
        phase="bootloader",
        intent="fail-closed verify: .sbat section present + non-empty in grubx64.efi",
    )
    if rc != 0:
        raise RuntimeError(
            "grub-mkimage produced a grubx64.efi with no/empty .sbat section "
            f"(verify rc={rc}). shim 16.1 would reject it at boot (0x1A "
            "Verification Failed). Aborting before signing."
        )


def _stage_grub_assets_to_esp(target):
    """Copy grub's runtime assets onto the ESP so an ESP-prefixed grub loads
    them without reading the (FDE-encrypted) root fs.

    Mirrors the ISO's ESP layout (/EFI/InterGenOS/{fonts,themes,x86_64-efi}).
    Three asset classes:
      - the console font (unicode.pf2) — for a readable gfxterm menu;
      - the theme dir (theme.txt + its relative backgrounds/) — the menu theme;
      - the x86_64-efi module dir — so any on-demand `insmod` in grub.cfg loads
        from the ESP, not /boot/grub on the encrypted root.
    The menu grub.cfg (grub-mkconfig output) and the UKI (/EFI/Linux, chainloaded
    by /etc/grub.d/06_uki) already live on the ESP, so with these staged grub
    never touches the root fs. Source paths are on the target root, mounted +
    readable at install time.
    """
    esp_dir = Path(target) / "boot/efi/EFI" / BOOTLOADER_ID

    # Font: stage from the HOST live ISO (guaranteed present — the
    # install_bootloader belt-suspenders raises if it is not), independent of
    # whether the target grub package shipped it.
    if HOST_GRUB_UNICODE_PF2.exists():
        (esp_dir / "fonts").mkdir(parents=True, exist_ok=True)
        trace.traced_copy_file(
            HOST_GRUB_UNICODE_PF2, esp_dir / "fonts" / "unicode.pf2",
            phase="bootloader",
            intent="stage grub console font on ESP (readable menu on FDE)",
        )

    # Theme dir (theme.txt + its relative backgrounds/) — self-contained, so the
    # theme's relative desktop-image resolves within the copied tree on the ESP.
    src_theme = Path(target) / "boot/grub/themes" / BOOTLOADER_ID.lower()
    if src_theme.is_dir():
        dst_theme = esp_dir / "themes" / BOOTLOADER_ID.lower()
        dst_theme.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(src_theme, dst_theme, dirs_exist_ok=True)
        logger.info("Staged grub theme to ESP: %s", dst_theme)

    # grub module dir — so an on-demand insmod (e.g. os-prober's ntfs for a
    # Windows dual-boot entry) resolves from the ESP prefix (/EFI/InterGenOS/<fmt>)
    # rather than the encrypted root. The core image already bakes in the common
    # module set; this covers the on-demand tail.
    #
    # grub-install now runs with --boot-directory=/boot/efi (so grub-probe stays
    # off the encrypted root — see _install_signed_efi_chain), which lands the
    # module dir at /boot/efi/grub/<fmt>. Fall back to the legacy /boot/grub/<fmt>
    # location for resilience across grub-install layouts so the ESP prefix is
    # never silently left without its module set.
    src_mods = Path(target) / "boot/efi/grub" / GRUB_FORMAT
    if not src_mods.is_dir():
        src_mods = Path(target) / "boot/grub" / GRUB_FORMAT
    if src_mods.is_dir():
        dst_mods = esp_dir / GRUB_FORMAT
        shutil.copytree(src_mods, dst_mods, dirs_exist_ok=True)
        logger.info("Staged grub %s modules to ESP: %s", GRUB_FORMAT, dst_mods)


def _inject_grub_theme(grub_cfg_chroot_path, target):
    """Inject a runtime-guarded `set theme=` into the generated grub.cfg.

    grub-mkconfig's 00_header emits `set theme=` only when [ -f "$GRUB_THEME" ]
    holds at mkconfig time. On EFI/FDE installs GRUB_THEME is ESP-relative
    (/EFI/InterGenOS/themes/intergenos/theme.txt) and does not resolve in the
    chroot, so the directive is dropped and the menu renders unthemed. Emit a
    runtime-guarded block instead — grub evaluates `-e` at boot against the
    staged ESP theme (BIOS path kept as the fallback) — mirroring the working
    installer/iso/grub/grub.cfg. Inserted right after `terminal_output gfxterm`
    so the theme is set before the menu renders. Idempotent. Validated on the
    A12 FDE install 2026-06-22 (GBC004.3).
    """
    cfg = Path(target) / grub_cfg_chroot_path.lstrip("/")
    if not cfg.is_file():
        logger.warning("grub theme inject: %s not found; skipping", cfg)
        return
    text = cfg.read_text()
    if "InterGenOS theme (Forge-injected)" in text:
        return
    block = (
        "\n### InterGenOS theme (Forge-injected) — 00_header's [ -f GRUB_THEME ]\n"
        "### check fails on the ESP-relative theme path at chroot mkconfig time,\n"
        "### so emit a runtime-guarded set theme= here (mirrors the ISO grub.cfg).\n"
        "insmod gfxmenu\n"
        "if [ -e /EFI/InterGenOS/themes/intergenos/theme.txt ]; then\n"
        "    set theme=/EFI/InterGenOS/themes/intergenos/theme.txt\n"
        "elif [ -e /boot/grub/themes/intergenos/theme.txt ]; then\n"
        "    set theme=/boot/grub/themes/intergenos/theme.txt\n"
        "fi\n"
    )
    marker = "terminal_output gfxterm\n"
    if marker in text:
        text = text.replace(marker, marker + block, 1)
    else:
        text = text + block
    cfg.write_text(text)
    logger.info("Injected runtime-guarded grub theme directive into %s", cfg)


def _install_bios_grub(target, disk):
    """BIOS legacy install (no Secure Boot)."""
    rc, _, stderr = trace.traced_run_chroot(target,
        f"grub-install --target=i386-pc {disk}"
    )
    if rc != 0:
        raise RuntimeError(f"grub-install (BIOS) failed: {stderr}")


# `efibootmgr` plain-output format. Each entry is:
#   Boot<HHHH><star_or_space> <label><TAB-OR-2+SPACES><path>
# Active entries have `*` after the bootnum; inactive have a space.
# Real efibootmgr 18+ uses a tab between label and path; older versions
# and some test fixtures use 2-or-more spaces. The label terminator
# accepts either form for resilience. Label runs until the terminator;
# path runs to end-of-line.
_EFIBOOTMGR_LINE_RE = re.compile(
    r"^Boot([0-9A-Fa-f]{4})[*\s]\s+(.+?)(?:\t|  +|$)"
)

# Fuller entry parse for the default-boot-target decision (D1 / work-plan 1.25):
# captures the active flag (`*`) and the trailing device path in addition to the
# bootnum + label. The path is what lets us tell an installed-OS entry (lives on
# a hard-disk partition -> `HD(...)` in the path) apart from firmware-synthesized
# removable/network/setup entries (`USB(...)`, `MAC(...)`, `Fv(...)`), so a
# single-OS machine's stock NVRAM noise never reads as "another OS is present".
_EFIBOOTMGR_ENTRY_RE = re.compile(
    r"^Boot([0-9A-Fa-f]{4})(\*?)\s+(.+?)(?:(?:\t|  +)(.*))?$"
)
_EFIBOOTMGR_ORDER_RE = re.compile(r"^BootOrder:\s*(.+)$")


def _parse_efibootmgr_output(stdout):
    """Parse `efibootmgr` plain output into (boot_order, entries).

    boot_order: list of bootnum strings in BootOrder, or [] if no BootOrder line.
    entries: {bootnum: (active: bool, label: str, path: str)}.
    """
    order = []
    entries = {}
    for line in stdout.splitlines():
        mo = _EFIBOOTMGR_ORDER_RE.match(line)
        if mo:
            order = [b.strip() for b in mo.group(1).split(",") if b.strip()]
            continue
        me = _EFIBOOTMGR_ENTRY_RE.match(line)
        if me:
            bootnum, star, label, path = me.groups()
            entries[bootnum] = (star == "*", label.strip(), (path or "").strip())
    return order, entries


# Device-path nodes that mark a boot entry as REMOVABLE/ephemeral media, not
# an installed-on-disk OS. A USB stick's firmware-synthesized entry can carry
# a trailing HD(...) partition node (ASRock X870, ge9b-04 dogfood install:
# `...USB(1,0)/USB(0,0)/HD(2,GPT,...)` for the install stick itself), so the
# bare HD(...) test misclassified the install medium as a foreign OS
# (PI-ge9b04-B). Any of these nodes ANYWHERE in the path disqualifies the
# entry — the partition node's presence does not make removable media an
# installed OS.
_REMOVABLE_PATH_NODES = ("USB(", "USBClass(", "USBWWID(", "SD(", "eMMC(",
                         "CDROM(")


def _foreign_os_bootnums(entries, our_label):
    """Bootnums of ACTIVE, installed-on-disk boot entries that are not ours.

    An installed OS registers a boot entry whose device path is a hard-disk
    partition (`HD(...)`). Firmware-synthesized removable/network/setup entries
    are excluded — but NOT by assuming they lack `HD(...)`: removable-media
    entries can carry a partition node at the tail (see _REMOVABLE_PATH_NODES),
    so any removable node in the path disqualifies the entry first. This keeps
    the set to "another operating system is installed here" — the only case
    where making InterGenOS the default silently displaces a real prior
    default (the D1 user-control concern).
    """
    out = []
    for bootnum, (active, label, path) in entries.items():
        if not active or label == our_label:
            continue
        if any(node in path for node in _REMOVABLE_PATH_NODES):
            continue
        if "HD(" in path:
            out.append(bootnum)
    return out


def has_other_os_boot_entries():
    """Confirm-time probe (live host, not chroot): does UEFI NVRAM already hold
    another installed OS's boot entry?

    Returns True (a foreign on-disk OS entry is present -> the frontend asks
    whether InterGenOS should become the default), False (none — single-OS, keep
    the current prepend, no ask), or None (not EFI / efibootmgr unavailable /
    unreadable — undeterminable, so the frontend asks nothing and the backend
    keeps its safe default of prepending). Mirrors secureboot.is_secure_boot_
    enabled()'s tri-state None-means-unknown contract.
    """
    try:
        res = subprocess.run(
            ["efibootmgr"], capture_output=True, text=True,
        )
    except (FileNotFoundError, OSError):
        return None
    if res.returncode != 0:
        return None
    _order, entries = _parse_efibootmgr_output(res.stdout)
    return bool(_foreign_os_bootnums(entries, BOOTLOADER_ID))


def _apply_default_boot_choice(target, make_default_boot, foreign_before):
    """Honor the user's default-boot-target choice after efibootmgr --create.

    --create prepends the new InterGenOS entry to BootOrder, making it the
    machine default. That is correct for a single-OS install (nothing to
    respect) and when the user asked for it, but on multi-OS metal a user who
    declined must keep their prior default. When foreign OS entries existed
    before install AND make_default_boot is False, move InterGenOS to the END of
    BootOrder so the previously-first (foreign) entry stays the default. Always
    emits a trace line recording the decision.

    Fail-open: if the post-create NVRAM state can't be read or InterGenOS isn't
    already first, leave BootOrder as --create left it (never strand the machine
    trying to be polite).
    """
    if not foreign_before or make_default_boot:
        trace.trace_event(
            "efibootmgr_default_boot_target",
            make_default=make_default_boot,
            foreign_entries_present=bool(foreign_before),
            action="kept efibootmgr --create prepend (InterGenOS is the default)",
            intent="single-OS install or user asked to be the default boot "
                   "target -> InterGenOS stays first in BootOrder (D1/1.25)",
        )
        return

    order, entries = _parse_efibootmgr_output(
        trace.traced_run_chroot(target, "efibootmgr")[1]
    )
    our = next(
        (b for b, (_a, label, _p) in entries.items() if label == BOOTLOADER_ID),
        None,
    )
    if our is None or not order or order[0] != our:
        trace.trace_event(
            "efibootmgr_default_boot_target",
            make_default=False,
            foreign_entries_present=True,
            action="left BootOrder unchanged (InterGenOS not first, or order "
                   "unreadable — nothing to demote)",
            intent="user declined default but the post-create order did not "
                   "need adjusting / could not be read (fail-open)",
        )
        return

    new_order = [b for b in order if b != our] + [our]
    trace.traced_run_chroot(target, f"efibootmgr -o {','.join(new_order)}")
    trace.trace_event(
        "efibootmgr_default_boot_target",
        make_default=False,
        foreign_entries_present=True,
        action=f"demoted InterGenOS to last in BootOrder ({','.join(new_order)})",
        intent="user declined making InterGenOS the default on a multi-OS "
               "machine -> prior default preserved as first (D1/1.25, Prime "
               "Directive: do not silently take over the machine's boot default)",
    )


def _verify_bootorder_end_state(target, expect_default):
    """Read NVRAM back after the boot-entry write and record what it holds.

    Everything before this point states an intent: `efibootmgr --create`
    prepends our entry, and _apply_default_boot_choice reorders when the user
    declined. Neither result was ever read back, so a firmware that accepts
    the write and then presents a different BootOrder went unnoticed — which
    is exactly what a UEFI 2.110 AMI board did on 2026-07-31: the install
    trace showed InterGenOS first, and the installed system came up with
    `BootOrder: 0001,0000`, 0001 being the firmware's own "UEFI OS" entry for
    \\EFI\\BOOT\\BOOTX64.EFI on the same ESP. Both entries reach the same
    partition, so the machine boots — through the removable-media fallback
    loader instead of the registered one.

    This is a report, not a gate: the install must not fail because a
    firmware reorders NVRAM, and the boot-time checker
    (intergenos-bootorder-check) is what repairs it on the installed system.
    What this adds is the checked fact — the trace now carries the observed
    end state instead of an assumption.
    """
    rc, stdout, _stderr = trace.traced_run_chroot(target, "efibootmgr")
    if rc != 0:
        trace.trace_event(
            "efibootmgr_bootorder_verified",
            verified=False,
            reason="post-write efibootmgr read failed",
            rc=rc,
            intent="read NVRAM back after registering the boot entry; the "
                   "read itself failed, so the end state is undetermined "
                   "(not a pass and not a failure)",
        )
        return

    order, entries = _parse_efibootmgr_output(stdout)
    ours = [b for b, (_a, label, _p) in entries.items()
            if label == BOOTLOADER_ID]
    first_is_ours = bool(order) and order[0] in ours
    trace.trace_event(
        "efibootmgr_bootorder_verified",
        verified=True,
        boot_order=",".join(order),
        our_bootnums=",".join(sorted(ours)),
        expected_first=bool(expect_default),
        observed_first_is_ours=first_is_ours,
        matches_intent=(first_is_ours == bool(expect_default)),
        intent="record the BootOrder the firmware actually holds after the "
               "boot-entry write, so a firmware that reorders NVRAM is "
               "visible in the install trace rather than discovered later "
               "on the booted system",
    )


def _write_boot_default_intent(target, expect_default, foreign_before):
    """Record on the target whether InterGenOS is meant to boot by default.

    The boot-time checker reads this file. Without it the checker cannot
    tell "the firmware demoted us" from "the user chose another OS as the
    default", and repairing the second case would take the machine over
    behind the user's back.

    Written for every EFI install, including one whose efibootmgr call
    failed — the intent is what this install meant, independent of whether
    NVRAM accepted it.
    """
    path = Path(target) / BOOT_DEFAULT_INTENT_REL
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# /etc/intergenos/boot-default.conf — InterGenOS\n"
            "# Written by the installer. Read by "
            "intergenos-bootorder-check.service.\n"
            "# default_boot_target=yes  -> the checker restores InterGenOS to\n"
            "#   the front of BootOrder when firmware moves it.\n"
            "# default_boot_target=no   -> the user kept another operating\n"
            "#   system as the default; the checker only reports.\n"
            f"default_boot_target={'yes' if expect_default else 'no'}\n"
            f"boot_entry_label={BOOTLOADER_ID}\n"
            f"foreign_os_entries_at_install={len(foreign_before)}\n"
        )
        path.chmod(0o644)
    except OSError as exc:
        # Never fail an install over the record file; the checker treats an
        # absent file as "no recorded intent" and takes no action.
        trace.trace_event(
            "boot_default_intent_write_failed",
            path=str(path), error=str(exc),
            intent="record the default-boot-target decision for the boot-time "
                   "checker; the write failed, so the checker will find no "
                   "recorded intent and will only report",
        )
        logger.warning("could not write %s: %s", path, exc)
        return

    trace.trace_event(
        "boot_default_intent_recorded",
        path=f"/{BOOT_DEFAULT_INTENT_REL}",
        default_boot_target=("yes" if expect_default else "no"),
        foreign_os_entries_at_install=len(foreign_before),
        intent="record the install-time default-boot-target decision so the "
               "boot-time BootOrder checker repairs only what this install "
               "actually intended",
    )


def _cleanup_stale_efi_entries(target, label):
    """Delete every existing UEFI boot entry matching `label` before --create.

    Re-installing InterGenOS onto the same machine repeatedly accumulates
    stale `InterGenOS` entries in NVRAM — each install's `efibootmgr
    --create` adds a fresh entry without removing prior ones that point
    at GPT partition UUIDs of older installs. 2026-05-27 install #28
    trace surfaced five stale entries Boot000{2,3,4,5} alongside the
    newly-created Boot0006.

    Strategy: list current entries, find every BootNNNN* whose label
    matches `label` exactly, and `efibootmgr -b NNNN -B` each one.
    Then the caller's --create produces a single clean entry.

    Fail-open: if efibootmgr can't list (no efivars, read-only, etc.),
    skip cleanup — the subsequent --create will surface the underlying
    error with full context.
    """
    rc, stdout, _ = trace.traced_run_chroot(target, "efibootmgr")
    if rc != 0:
        # efibootmgr unavailable — likely no efivars (build VM) or
        # firmware-read failure. Let the --create that follows surface
        # the real error.
        return

    stale_bootnums = []
    for line in stdout.splitlines():
        m = _EFIBOOTMGR_LINE_RE.match(line)
        if m and m.group(2).strip() == label:
            stale_bootnums.append(m.group(1))

    if not stale_bootnums:
        return

    trace.trace_event(
        "efibootmgr_cleanup_stale",
        label=label,
        bootnums=stale_bootnums,
        count=len(stale_bootnums),
        intent="delete stale NVRAM entries with matching label before "
               "efibootmgr --create so re-installs don't accumulate "
               "duplicates (2026-05-27 install #28 anomaly D)",
    )

    for bootnum in stale_bootnums:
        trace.traced_run_chroot(
            target, f"efibootmgr -b {bootnum} -B",
        )


def _split_partition(part_dev):
    """Split a partition device path into disk + partition number.

    Examples:
        /dev/sda1       -> ('/dev/sda', 1)
        /dev/nvme0n1p2  -> ('/dev/nvme0n1', 2)
        /dev/mmcblk0p3  -> ('/dev/mmcblk0', 3)
    """
    if "nvme" in part_dev or "mmcblk" in part_dev:
        # NVMe/MMC use 'p' separator before partition number
        idx = part_dev.rfind("p")
        return part_dev[:idx], int(part_dev[idx + 1:])
    else:
        # SATA/SCSI use bare digit suffix
        i = len(part_dev)
        while i > 0 and part_dev[i - 1].isdigit():
            i -= 1
        return part_dev[:i], int(part_dev[i:])


# Backwards-compat alias for callers still using the old name
install_grub = install_bootloader
