"""Bootloader installation for InterGenOS installer.

Two paths:
- BIOS legacy: install GRUB to MBR/GPT bios_grub partition (no Secure Boot).
- EFI: install signed boot chain (shim + GRUB signed with MOK + signed kernel).

The signed boot chain layout on the ESP:
  /boot/efi/EFI/intergenos/
    shimx64.efi       — Microsoft-signed shim (from shim-signed package)
    grubx64.efi       — Our GRUB, signed with the MOK private key
    mmx64.efi         — MokManager (from shim-signed; for first-boot enrollment)
    grub.cfg          — Generated by grub-mkconfig with os-prober enabled

Shim is registered as the primary UEFI boot entry. On boot:
  shim verifies grubx64.efi against the MOK enrolled at first boot
  (or against the embedded vendor cert if shim is from Fedora's piggyback build)
  -> GRUB loads, verifies kernel signature
  -> kernel boots, MODULE_SIG_FORCE=y rejects unsigned modules
"""

import logging
import subprocess
from pathlib import Path

from .hooks import (
    run_chroot,
    mount_efivars,
    unmount_efivars,
)
from .mok import sign_efi_binary

logger = logging.getLogger(__name__)


# Where shim-signed package installs its artifacts (provided by the package)
SHIM_SOURCE_DIR = "/usr/share/shim-signed"
SHIM_BINARY = "shimx64.efi"
MOKMANAGER_BINARY = "mmx64.efi"

# Where we write the signed boot chain on the ESP
ESP_BOOT_DIR = "/boot/efi/EFI/intergenos"
GRUB_BINARY = "grubx64.efi"
BOOTLOADER_ID = "InterGenOS"


def verify_shim_assets_present():
    """Pre-flight check: shim-signed binaries must exist in the live ISO.

    Called before partition_disk() on EFI installs (C-003 audit row;
    T0-2 closure dispatch 2026-05-18T20:25:59Z). Fails closed so a
    regression in the live-ISO build pipeline (e.g. shim-signed package
    not wired through chroot-build-core-extra.sh — A-001) is caught
    BEFORE the destructive partition write rather than after, when the
    target disk is already modified.

    Raises:
        RuntimeError if shimx64.efi or mmx64.efi are missing from
        SHIM_SOURCE_DIR.
    """
    missing = []
    for binary in (SHIM_BINARY, MOKMANAGER_BINARY):
        if not Path(SHIM_SOURCE_DIR, binary).is_file():
            missing.append(f"{SHIM_SOURCE_DIR}/{binary}")
    if missing:
        raise RuntimeError(
            "shim-signed binaries missing from live ISO: "
            + ", ".join(missing)
            + ". The shim-signed package is not wired into this build. "
            "Aborting BEFORE partitioning to preserve disk state. "
            "Re-run install on a build where the shim-signed package "
            "is wired through phase_image (audit row A-001)."
        )


def install_bootloader(target, disk, partitions, mok_keypair=None):
    """Install bootloader on the target system.

    Args:
        target: target root path
        disk: disk device (e.g., /dev/sda or /dev/nvme0n1)
        partitions: dict from disks.partition_disk()
        mok_keypair: dict from mok.generate_mok_keypair() with key_path/cert_path.
                     Required for EFI installs (signed boot chain).
                     Ignored for BIOS installs.

    Raises:
        RuntimeError if any step fails.
        ValueError if EFI install requested without mok_keypair.
    """
    target = str(target)
    efi = partitions.get("efi", False)

    if efi and mok_keypair is None:
        raise ValueError(
            "EFI install requires mok_keypair from mok.generate_mok_keypair() "
            "to sign the GRUB binary"
        )

    # C-006: orchestrator (install.py PHASE_VIRTUAL_FS) owns virtual_fs
    # lifecycle. This function runs between PHASE_VIRTUAL_FS and
    # PHASE_CLEANUP so /dev /proc /sys /run /dev/pts are already bind-
    # mounted into target; re-mounting here stacks them and leaks on
    # cleanup (unmount only removes the top layer).
    if efi:
        _install_signed_efi_chain(target, partitions, mok_keypair)
    else:
        _install_bios_grub(target, disk)

    # Generate GRUB config (both modes)
    # os-prober enables detection of other OSes (Windows alongside install)
    rc, _, stderr = run_chroot(target,
        "GRUB_DISABLE_OS_PROBER=false grub-mkconfig -o /boot/grub/grub.cfg"
    )
    if rc != 0:
        raise RuntimeError(f"grub-mkconfig failed: {stderr}")


def _install_signed_efi_chain(target, partitions, mok_keypair):
    """EFI install with signed boot chain (shim + signed GRUB)."""
    esp_mount = f"{target}/boot/efi"
    Path(esp_mount).mkdir(parents=True, exist_ok=True)

    # Mount ESP if not already mounted
    if partitions.get("esp"):
        subprocess.run(
            f"mountpoint -q {esp_mount} || mount {partitions['esp']} {esp_mount}",
            shell=True, capture_output=True
        )

    # Install GRUB to a staging location (we'll sign and copy to ESP manually)
    # --no-nvram: we register the boot entry via efibootmgr against shim, not GRUB
    # --no-bootsector: don't write to disk MBR (we're EFI)
    # --modules: include modules needed for our boot (ext4, normal, etc.)
    rc, _, stderr = run_chroot(target,
        "grub-install --target=x86_64-efi "
        "--efi-directory=/boot/efi "
        f"--bootloader-id={BOOTLOADER_ID} "
        "--no-nvram "
        "--modules='all_video boot btrfs cat chain configfile echo efifwsetup "
        "efinet ext2 fat font gfxmenu gfxterm gzio halt hfsplus iso9660 jpeg "
        "loadenv loopback linux ls lsefi lsefimmap lsefisystab lssal "
        "memdisk minicmd normal part_apple part_msdos part_gpt password_pbkdf2 "
        "png reboot search search_fs_uuid search_fs_file search_label sleep "
        "smbios squash4 test true video xfs zfs zfscrypt zfsinfo'"
    )
    if rc != 0:
        raise RuntimeError(f"grub-install staging failed: {stderr}")

    # Sign the staged GRUB binary with the MOK key
    grub_efi_chroot_path = f"{ESP_BOOT_DIR}/{GRUB_BINARY}"
    sign_efi_binary(
        target,
        binary_path=grub_efi_chroot_path,
        key_path=mok_keypair["key_path"],
        cert_path=mok_keypair["cert_path"],
    )

    # Copy shim + MokManager from shim-signed package to ESP
    rc, _, stderr = run_chroot(target,
        f"mkdir -p {ESP_BOOT_DIR} && "
        f"cp {SHIM_SOURCE_DIR}/{SHIM_BINARY} {ESP_BOOT_DIR}/ && "
        f"cp {SHIM_SOURCE_DIR}/{MOKMANAGER_BINARY} {ESP_BOOT_DIR}/"
    )
    if rc != 0:
        raise RuntimeError(f"shim staging to ESP failed: {stderr}")

    # Fallback auto-discovery path: some older UEFI firmware only looks at
    # /EFI/BOOT/bootx64.efi when no matching UEFI boot variable is registered.
    # Mirror the MS-signed shim and the MOK-signed GRUB there so the chain
    # is self-contained — shim stays signed by MS so SecureBoot validation
    # passes, and it will find grubx64.efi in the same directory.
    rc, _, stderr = run_chroot(target,
        f"mkdir -p /boot/efi/EFI/BOOT && "
        f"cp {ESP_BOOT_DIR}/{SHIM_BINARY} /boot/efi/EFI/BOOT/bootx64.efi && "
        f"cp {ESP_BOOT_DIR}/{GRUB_BINARY} /boot/efi/EFI/BOOT/{GRUB_BINARY}"
    )
    if rc != 0:
        raise RuntimeError(f"EFI/BOOT fallback staging failed: {stderr}")

    # Sign every /boot/vmlinuz-* kernel image with the MOK. This closes
    # the middle link in the v2 playbook's 3-check signature chain:
    #   shim → GRUB (signed above)
    #   GRUB → kernel (signed here)
    #   kernel → modules (MODULE_SIG_FORCE ephemeral sig at build time)
    # Without this, GRUB with check_signatures=enforce refuses to load
    # the kernel. Even with check_signatures=off, leaving the kernel
    # unsigned means we don't detect tampered kernel images.
    #
    # Safety notes:
    #   - sbverify --list pre-check makes the loop idempotent on install
    #     retry — already-signed kernels are skipped rather than re-signed
    #     (behavior of re-signing varies across sbsigntools versions:
    #     some replace the signature, some append, some refuse).
    #   - sbsign writes to $k.new then renames — explicit atomicity
    #     regardless of sbsigntools version. A crash mid-write leaves
    #     the pre-signed kernel intact, not a truncated binary.
    rc, _, stderr = run_chroot(target,
        f"for k in /boot/vmlinuz-*; do "
        f"  [ -f \"$k\" ] || continue; "
        f"  if sbverify --cert {mok_keypair['cert_path']} \"$k\" >/dev/null 2>&1; then "
        f"    echo \"skipping $k (already signed with MOK)\"; "
        f"    continue; "
        f"  fi; "
        f"  sbsign --key {mok_keypair['key_path']} "
        f"--cert {mok_keypair['cert_path']} "
        f"--output \"$k.new\" \"$k\" || exit 1; "
        f"  mv \"$k.new\" \"$k\" || exit 1; "
        f"done"
    )
    if rc != 0:
        raise RuntimeError(f"kernel image signing failed: {stderr}")

    # Register shim as the primary UEFI boot entry via efibootmgr.
    # The disk + partition number come from partitions['esp'].
    #
    # efibootmgr requires /sys/firmware/efi/efivars inside the chroot to
    # write firmware boot variables. The host-booted-EFI case (USB installer)
    # has efivars available; bind-mount it in. The build-VM case (no UEFI
    # firmware) falls back to the soft-warn path with user-recovery guidance.
    esp_dev = partitions.get("esp", "")
    disk_dev, part_num = _split_partition(esp_dev)

    efivars_ok = mount_efivars(target)
    try:
        rc, _, stderr = run_chroot(target,
            f"efibootmgr --create --disk {disk_dev} --part {part_num} "
            f"--label '{BOOTLOADER_ID}' "
            f"--loader '\\EFI\\intergenos\\{SHIM_BINARY}'"
        )
    finally:
        if efivars_ok:
            unmount_efivars(target)

    if rc != 0:
        # Two legitimate failure modes here:
        #   (1) Host has no EFI firmware (build VM). efivars_ok is False above;
        #       user must rely on /EFI/BOOT/bootx64.efi auto-discovery.
        #   (2) Host IS EFI but efibootmgr still failed (read-only efivars,
        #       firmware bug, etc.). User can retry manually post-boot.
        #
        # Fallback path: /EFI/BOOT/bootx64.efi auto-discovery works on most
        # firmware. On older/custom firmware that doesn't auto-discover,
        # the logged command below lets the user register by hand.
        host_efi_note = (
            "host has no EFI firmware — expected in build VM"
            if not efivars_ok
            else "host is EFI but efibootmgr still failed"
        )
        logger.warning(
            "efibootmgr registration failed (rc=%d, %s): %s. "
            "UEFI boot order NOT updated by installer. The EFI/BOOT/bootx64.efi "
            "fallback still allows auto-discovery on next boot. "
            "To register manually post-install: sudo efibootmgr --create "
            "--disk %s --part %d --label '%s' --loader '\\EFI\\intergenos\\%s'",
            rc, host_efi_note, stderr.strip(),
            disk_dev, part_num, BOOTLOADER_ID, SHIM_BINARY,
        )


def _install_bios_grub(target, disk):
    """BIOS legacy install (no Secure Boot)."""
    rc, _, stderr = run_chroot(target,
        f"grub-install --target=i386-pc {disk}"
    )
    if rc != 0:
        raise RuntimeError(f"grub-install (BIOS) failed: {stderr}")


def _split_partition(part_dev):
    """Split a partition device path into disk + partition number.

    Examples:
        /dev/sda1       -> ('/dev/sda', 1)
        /dev/nvme0n1p2  -> ('/dev/nvme0n1', 2)
        /dev/mmcblk0p3  -> ('/dev/mmcblk0', 3)
    """
    if "nvme" in part_dev or "mmcblk" in part_dev:
        # NVMe/MMC use 'p' separator before partition number
        idx = part_dev.rfind("p")
        return part_dev[:idx], int(part_dev[idx + 1:])
    else:
        # SATA/SCSI use bare digit suffix
        i = len(part_dev)
        while i > 0 and part_dev[i - 1].isdigit():
            i -= 1
        return part_dev[:i], int(part_dev[i:])


# Backwards-compat alias for callers still using the old name
install_grub = install_bootloader
