"""System configuration generator for InterGenOS installer."""

import os
import subprocess
from pathlib import Path


def generate_fstab(target, partitions):
    """Generate /etc/fstab from partition UUIDs.

    LUKS opt-in (D-001): when partitions["root_mapper"] is set, the
    root entry uses the ext4 filesystem UUID from /dev/mapper/cryptroot
    (NOT the underlying LUKS partition UUID, which is the crypttab's
    job). The kernel can mount the mapper by UUID once the crypttab-
    declared cryptsetup-unlock has completed at boot time (fde-init.sh).
    """
    fstab_path = Path(target) / "etc" / "fstab"
    fstab_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# /etc/fstab — InterGenOS",
        "# Generated by InterGenOS installer",
        "# <file system>  <mount point>  <type>  <options>         <dump>  <pass>",
    ]

    # Root partition (use the LUKS mapper if present — fstab references
    # the unlocked filesystem, not the underlying LUKS container)
    root_device = partitions.get("root_mapper") or partitions["root"]
    root_uuid = _get_uuid(root_device)
    if root_uuid:
        lines.append(f"UUID={root_uuid}  /              ext4    defaults          1       1")
    else:
        lines.append(f"{root_device}  /              ext4    defaults          1       1")

    # EFI System Partition
    # umask=0077 hides ESP contents from non-root users (HG: signing keys
    # may be staged here transiently during signed-boot updates)
    if partitions.get("efi") and partitions.get("esp"):
        esp_uuid = _get_uuid(partitions["esp"])
        if esp_uuid:
            lines.append(f"UUID={esp_uuid}  /boot/efi      vfat    umask=0077        0       2")
        else:
            lines.append(f"{partitions['esp']}  /boot/efi      vfat    umask=0077        0       2")

    fstab_path.write_text("\n".join(lines) + "\n")


def generate_hostname(target, hostname):
    """Generate /etc/hostname and /etc/hosts."""
    etc = Path(target) / "etc"
    etc.mkdir(parents=True, exist_ok=True)

    (etc / "hostname").write_text(f"{hostname}\n")

    hosts = (
        f"# /etc/hosts — InterGenOS\n"
        f"\n"
        f"127.0.0.1    localhost\n"
        f"127.0.1.1    {hostname}.localdomain {hostname}\n"
        f"::1          localhost ip6-localhost ip6-loopback\n"
        f"ff02::1      ip6-allnodes\n"
        f"ff02::2      ip6-allrouters\n"
    )
    (etc / "hosts").write_text(hosts)


def generate_locale(target, locale="en_US.UTF-8"):
    """Generate /etc/locale.conf."""
    etc = Path(target) / "etc"
    (etc / "locale.conf").write_text(f"LANG={locale}\n")


def generate_vconsole(target, keymap="us"):
    """Generate /etc/vconsole.conf."""
    etc = Path(target) / "etc"
    (etc / "vconsole.conf").write_text(
        f"KEYMAP={keymap}\n"
        f"FONT=Lat2-Terminus16\n"
    )


def set_timezone(target, timezone="UTC"):
    """Set timezone via /etc/localtime symlink."""
    localtime = Path(target) / "etc" / "localtime"
    zoneinfo = Path(target) / "usr" / "share" / "zoneinfo" / timezone

    if localtime.exists() or localtime.is_symlink():
        localtime.unlink()

    if zoneinfo.exists():
        localtime.symlink_to(f"/usr/share/zoneinfo/{timezone}")
    else:
        # Fallback to UTC
        localtime.symlink_to("/usr/share/zoneinfo/UTC")


def generate_network(target):
    """Generate systemd-networkd DHCP config."""
    netdir = Path(target) / "etc" / "systemd" / "network"
    netdir.mkdir(parents=True, exist_ok=True)

    (netdir / "10-dhcp.network").write_text(
        "[Match]\n"
        "Name=en*\n"
        "\n"
        "[Network]\n"
        "DHCP=yes\n"
    )

    # DNS via systemd-resolved
    resolv = Path(target) / "etc" / "resolv.conf"
    if resolv.exists() or resolv.is_symlink():
        resolv.unlink()
    resolv.symlink_to("/run/systemd/resolve/stub-resolv.conf")


def generate_os_release(target):
    """Generate /etc/os-release and related identity files."""
    etc = Path(target) / "etc"

    (etc / "os-release").write_text(
        'NAME="InterGenOS"\n'
        'VERSION="1.0-dev (Revival)"\n'
        'ID=intergenos\n'
        'ID_LIKE=lfs\n'
        'VERSION_ID=1.0\n'
        'VERSION_CODENAME=revival\n'
        'PRETTY_NAME="InterGenOS 1.0-dev (Revival)"\n'
        'HOME_URL="https://github.com/InterGenJLU/intergenos"\n'
        'BUG_REPORT_URL="https://github.com/InterGenJLU/intergenos/issues"\n'
    )

    (etc / "igos-release").write_text("1.0-dev\n")


def generate_branding(target):
    """Generate /etc/issue and /etc/motd branding files."""
    etc = Path(target) / "etc"

    (etc / "issue").write_text(
        "\n"
        "  InterGenOS 1.0-dev (Revival)\n"
        "  Kernel \\r on \\m (\\l)\n"
        "\n"
    )

    (etc / "motd").write_text(
        "\n"
        '  Welcome to InterGenOS\n'
        '  "A system you understand, can modify, and can trust."\n'
        "\n"
        "  Documentation:  https://github.com/InterGenJLU/intergenos\n"
        "  Report issues:  https://github.com/InterGenJLU/intergenos/issues\n"
        "\n"
    )


def generate_crypttab(target, partitions):
    """Generate /etc/crypttab for LUKS-at-install systems (D-001).

    Writes a single line declaring the LUKS root volume:
        cryptroot UUID=<luks-uuid> none luks,discard

    - "cryptroot" matches CRYPT_NAME in installer/init/fde-init.sh and
      LUKS_MAPPER_NAME in installer/backend/disks.py — these three must
      agree, since fde-init.sh's awk lookup keys on field 1.
    - "UUID=<luks-uuid>" references the LUKS-formatted underlying
      partition (NOT the ext4 filesystem UUID — that lives on the
      mapper, which doesn't exist until cryptsetup-open has run).
    - "none" tells cryptsetup-open to read the passphrase from stdin
      (which fde-init.sh attaches to /dev/tty so the prompt fires).
    - "luks,discard" enables LUKS2 parsing + TRIM passthrough to the
      underlying SSD (allows the kernel's discard plumbing to reach
      hardware through the encryption layer; safe by default for v1.0
      desktop installs — TRIM-leak side-channels are documented and
      out-of-scope for v1.0 per D-001 ratified scope).

    Only emitted when partitions reflects a LUKS install (presence of
    "luks_enabled": True). Plain installs do not get a /etc/crypttab.
    """
    if not partitions.get("luks_enabled"):
        return  # plain install — no crypttab needed

    etc = Path(target) / "etc"
    etc.mkdir(parents=True, exist_ok=True)

    luks_uuid = _get_uuid(partitions["root"])
    if luks_uuid:
        device_ref = f"UUID={luks_uuid}"
    else:
        # blkid lookup failed — fall through to bare partition path. This
        # is fragile across device renumbering between boots, but better
        # than emitting a broken crypttab line that fde-init.sh would
        # refuse with FATAL.
        device_ref = partitions["root"]

    crypttab = (
        "# /etc/crypttab — InterGenOS\n"
        "# Generated by InterGenOS installer (D-001 LUKS-at-install v1.0)\n"
        "# <name>     <device>                <key file>  <options>\n"
        f"cryptroot   {device_ref}    none        luks,discard\n"
    )
    (etc / "crypttab").write_text(crypttab)


def generate_grub_defaults(target, partitions):
    """Generate /etc/default/grub.

    LUKS opt-in (D-001): when LUKS is enabled, GRUB_CMDLINE_LINUX points
    at the ext4 filesystem UUID on /dev/mapper/cryptroot (NOT the LUKS
    partition UUID). The UKI boot path (D-005 Phase D) handles unlock
    via fde-init.sh; this grub.cfg is the fallback path. The fallback
    boots vmlinuz + a generic initramfs that does NOT include cryptsetup
    — operator recovery via grub-loads-vmlinuz + manual unlock per
    D-005 fallback semantics. Documented in the user FDE guide.
    """
    etc_default = Path(target) / "etc" / "default"
    etc_default.mkdir(parents=True, exist_ok=True)

    # Use mapper-fs UUID when LUKS active; underlying partition UUID
    # for plain installs.
    root_device = partitions.get("root_mapper") or partitions["root"]
    root_uuid = _get_uuid(root_device)
    root_arg = f"root=UUID={root_uuid}" if root_uuid else f"root={root_device}"

    # OS_PROBER=false so other OSes (Windows alongside install, other Linux
    # distros on additional partitions) get menu entries automatically.
    # Required for the dual-boot Monday install path.
    (etc_default / "grub").write_text(
        "# GRUB defaults for InterGenOS\n"
        "GRUB_DEFAULT=0\n"
        "GRUB_TIMEOUT=5\n"
        'GRUB_DISTRIBUTOR="InterGenOS"\n'
        'GRUB_CMDLINE_LINUX_DEFAULT=""\n'
        f'GRUB_CMDLINE_LINUX="{root_arg}"\n'
        "GRUB_DISABLE_OS_PROBER=false\n"
    )


def generate_all(target, partitions, hostname="intergenos",
                 locale="en_US.UTF-8", keymap="us", timezone="UTC"):
    """Generate all system configuration files."""
    generate_fstab(target, partitions)
    generate_crypttab(target, partitions)   # D-001 LUKS-at-install
    generate_hostname(target, hostname)
    generate_locale(target, locale)
    generate_vconsole(target, keymap)
    set_timezone(target, timezone)
    generate_network(target)
    generate_os_release(target)
    generate_branding(target)
    generate_grub_defaults(target, partitions)


def _get_uuid(device):
    """Get filesystem UUID for a device."""
    result = subprocess.run(
        ["blkid", "-s", "UUID", "-o", "value", device],
        capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else None
