# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
"""System configuration generator for InterGenOS installer."""

import logging
import os
import re
import shutil
import subprocess
import uuid
from pathlib import Path

from installer.backend.gpu_detect import write_detection_record

LOG = logging.getLogger("forge.config")

# S4 (security-review 2026-07-01): a glibc/POSIX locale name is strictly
# <lang>[_TERRITORY][.CODESET][@modifier] — only letters, digits, and the
# separators . _ @ - . The user-selected locale is interpolated into a root
# `bash -c` inside the target chroot (generate_locale -> run_chroot), so a
# name carrying shell metacharacters ("en_US.UTF-8; rm -rf /", backticks,
# $(...)) would break out of the localedef command into arbitrary root code.
# Positive allowlist (stronger than a metachar denylist) — every SUPPORTED
# glibc locale matches, so a non-match is malformed or hostile and is refused
# before it reaches the shell.
_VALID_LOCALE_NAME = re.compile(r"^[A-Za-z0-9._@-]+$")

# crypttab(5) option that keeps the root LUKS volume out of the shutdown
# transaction's early detach window. See generate_crypttab's docstring for
# the measured failure it removes.
ROOT_CRYPT_SHUTDOWN_OPT = "x-initrd.attach"

# The fields a target's os-release must carry for generate_os_release to treat
# it as the file intergenos-base-files ships. Absence means the packages phase
# did not deliver the package's identity file, not that the values defaulted.
OS_RELEASE_IDENTITY_FIELDS = ("NAME", "VERSION", "VERSION_ID", "PRETTY_NAME")


def generate_fstab(target, partitions):
    """Generate /etc/fstab — PARTUUID for plain installs, UUID-of-mapper for LUKS.

    Ratified boot design (2026-04-08/09 + reaffirmed 2026-04-10 FINAL +
    Q-INIT 2026-05-05/06): PARTUUID + rootwait + no-installed-system-
    initramfs for plain installs. The kernel reads PARTUUID from the
    partition table directly without needing userland blkid; that is the
    whole reason for choosing PARTUUID over filesystem UUID.

    LUKS opt-in (D-001) narrowing: when partitions["root_mapper"] is set,
    /etc/fstab references the unlocked filesystem UUID (NOT the underlying
    LUKS partition's PARTUUID; that PARTUUID points at the encrypted
    container which is not directly mountable). The FDE initramfs runs
    fde-init.sh which uses /etc/crypttab to unlock, then exposes
    /dev/mapper/cryptroot whose ext4 UUID this fstab entry references.

    B-041 (T0-2 sub-cluster 6): closes the install-time drift from the
    ratified image-time path (scripts/create-image.sh:148-150 + 177 emit
    PARTUUID). Pre-fix this file emitted root=UUID= for both plain and
    LUKS installs, which would have caused plain installs to halt at
    first boot with "VFS: Unable to mount root fs" — no initramfs means
    no userland blkid means kernel can't resolve filesystem UUID.
    """
    fstab_path = Path(target) / "etc" / "fstab"
    fstab_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# /etc/fstab — InterGenOS",
        "# Generated by InterGenOS installer",
        "# <file system>  <mount point>  <type>  <options>         <dump>  <pass>",
    ]

    # Root entry: LUKS uses unlocked-mapper filesystem UUID; plain uses
    # PARTUUID of the partition holding the filesystem.
    if partitions.get("root_mapper"):
        root_mapper = partitions["root_mapper"]
        root_uuid = _get_uuid(root_mapper)
        if root_uuid:
            lines.append(f"UUID={root_uuid}  /              ext4    defaults          1       1")
        else:
            lines.append(f"{root_mapper}  /              ext4    defaults          1       1")
    else:
        root_partuuid = _get_partuuid(partitions["root"])
        if root_partuuid:
            lines.append(f"PARTUUID={root_partuuid}  /              ext4    defaults          1       1")
        else:
            lines.append(f"{partitions['root']}  /              ext4    defaults          1       1")

    # EFI System Partition — PARTUUID per ratified boot design (firmware
    # reads partition table directly; PARTUUID is the canonical key).
    # umask=0077 hides ESP contents from non-root users (signing keys may
    # be staged here transiently during signed-boot updates).
    if partitions.get("efi") and partitions.get("esp"):
        esp_partuuid = _get_partuuid(partitions["esp"])
        if esp_partuuid:
            lines.append(f"PARTUUID={esp_partuuid}  /boot/efi      vfat    umask=0077        0       2")
        else:
            lines.append(f"{partitions['esp']}  /boot/efi      vfat    umask=0077        0       2")

    fstab_path.write_text("\n".join(lines) + "\n")


ACCOUNT_DATABASES = ("passwd", "group", "shadow", "gshadow")
ACCOUNT_SKEL_REL = "usr/share/intergenos-base-files/account-skel"
_ACCOUNT_DB_MODES = {"passwd": 0o644, "group": 0o644, "shadow": 0o640, "gshadow": 0o640}


def seed_account_databases(target):
    """Create the target's account databases from the shipped skeleton.

    intergenos-base-files ships passwd/group/shadow/gshadow as reference data
    under /usr/share, NOT as /etc payload (decided 2026-07-24): when they were
    ordinary payload, installing the package on a system that had never had it
    deployed the pristine skeleton over the live databases and lost every real
    account. Nothing now writes those four paths as part of a package deploy,
    so the install has to create them explicitly — and this is the right layer
    for it, since initial account state is install-time state (build-rules
    §2.7: install-time decisions are written by the installer, not routed
    through a package).

    Ordering is load-bearing, and on any target that received packages the
    effective seed happens EARLIER than this call. pkm's canonical
    account-skel-seed hook (pkm/hooks.py, CANONICAL_HOOKS_PRE) runs the same
    create-only helper during the package phase, immediately ahead of the
    first systemd-sysusers run — which is the only point at which a seed can
    still act, because sysusers creates the databases itself from its declared
    entries and the helper never rewrites a database that exists. Measured on
    a fresh install before that hook existed: the config-phase call found all
    four already present and the skeleton's bin/sys/daemon accounts were
    absent for the life of the system.

    This call is retained as an idempotent belt for the path where no package
    install wrote the databases at all, and because the users phase's
    `useradd --root` immediately downstream cannot run without them. It is a
    no-op whenever the hook has already acted.

    A recipe post_install hook could not serve either role — those run in the
    hooks phase, later still than this one.

    CREATE-ONLY, like the shipped helper it mirrors: a database that already
    exists is left exactly as found. On a fresh install none exist and all four
    are created; the guard matters for a re-run over a populated target, where
    silently rewriting them would be the very loss this split exists to stop.

    Returns:
        dict with "seeded" and "kept" lists of database names.

    Raises:
        FileNotFoundError: the skeleton is absent from the target, which means
            base-files did not land — fail loudly rather than leave a system
            with no account databases at all.
    """
    target_path = Path(target)
    skel = target_path / ACCOUNT_SKEL_REL
    if not skel.is_dir():
        raise FileNotFoundError(
            f"account skeleton missing at {skel} — intergenos-base-files ships "
            f"it; a target without it did not receive the package"
        )

    etc = target_path / "etc"
    etc.mkdir(parents=True, exist_ok=True)
    seeded, kept = [], []
    for db in ACCOUNT_DATABASES:
        src = skel / db
        if not src.is_file():
            raise FileNotFoundError(f"account skeleton incomplete: {src} missing")
        dest = etc / db
        if dest.exists():
            kept.append(db)
            continue
        shutil.copyfile(src, dest)
        os.chmod(dest, _ACCOUNT_DB_MODES[db])
        try:
            os.chown(dest, 0, 0)
        except PermissionError:
            # Unprivileged test/dry runs: content is what matters here, and a
            # real install runs as root. Not silently ignored — the caller's
            # trace records the outcome either way.
            pass
        seeded.append(db)
    return {"seeded": seeded, "kept": kept}


def generate_hostname(target, hostname):
    """Generate /etc/hostname and /etc/hosts."""
    etc = Path(target) / "etc"
    etc.mkdir(parents=True, exist_ok=True)

    (etc / "hostname").write_text(f"{hostname}\n")

    hosts = (
        f"# /etc/hosts — InterGenOS\n"
        f"\n"
        f"127.0.0.1    localhost\n"
        f"127.0.1.1    {hostname}.localdomain {hostname}\n"
        f"::1          localhost ip6-localhost ip6-loopback\n"
        f"ff02::1      ip6-allnodes\n"
        f"ff02::2      ip6-allrouters\n"
    )
    (etc / "hosts").write_text(hosts)


def generate_locale(target, locale="en_US.UTF-8"):
    """Generate /etc/locale.conf AND compile the locale into the target glibc.

    C-010 + J-026 combined fix: previously only wrote /etc/locale.conf, which
    pointed LANG at a locale that didn't exist on the target — glibc-core/
    build.sh:69-74 bakes only C.UTF-8 / en_US / en_US.UTF-8, so any other
    user-picked locale (fr_FR.UTF-8, de_DE.UTF-8, ja_JP.UTF-8, ...) silently
    fell back to C at every login.

    Fix: after writing /etc/locale.conf, invoke localedef in the target chroot
    to compile the locale into /usr/lib/locale/<locale>/ on the installed
    system. localedef parses the locale name as <base>.<encoding> (e.g.
    "fr_FR.UTF-8" → base="fr_FR" + encoding="UTF-8") and reads the matching
    locale definition file under /usr/share/i18n/locales/ + the charmap under
    /usr/share/i18n/charmaps/.

    Skipped for locales without an encoding suffix (C, POSIX, single-name)
    — these are always-present in the glibc-core baked set; localedef would
    fail with "cannot read character map" since they don't have a separate
    encoding step.

    Skipped for malformed locale strings (empty base or encoding after the
    partition) — locale.conf is still written so the user can hand-fix
    post-install, but localedef gets garbage input on malformed names.

    Orchestrator owns virtual_fs lifecycle (C-006); this runs during
    PHASE_CONFIG which is between PHASE_VIRTUAL_FS and PHASE_CLEANUP, so
    the chroot is mountable.
    """
    from .hooks import run_chroot

    # S4 fix — validate the user-selected locale BEFORE it is written or reaches
    # the root chroot shell. run_chroot execs `bash -c "<cmd>"`, and localedef's
    # argv below interpolates `locale`/`base`/`encoding` verbatim; a name with
    # shell metacharacters would inject arbitrary root commands into the target.
    # Fail-closed: refuse a non-allowlisted name outright (never persist a
    # poisoned locale.conf, never touch the shell) — the validation cannot live
    # in run_chroot itself because other callers (bootloader) legitimately pass
    # shell syntax, so the input must be gated where the untrusted value enters.
    if not _VALID_LOCALE_NAME.match(locale):
        raise ValueError(
            f"refusing to configure an invalid locale name {locale!r}: a locale "
            "must be <lang>[_TERRITORY][.CODESET][@modifier] "
            "(letters, digits, and . _ @ - only)")

    etc = Path(target) / "etc"
    (etc / "locale.conf").write_text(f"LANG={locale}\n")

    # C / POSIX / single-name locale — always-present in baked set; nothing
    # to compile. localedef would fail with "cannot read character map".
    if "." not in locale:
        return

    base, _, encoding = locale.partition(".")
    if not base or not encoding:
        # Malformed locale string ("foo.", ".bar", ".") — locale.conf
        # already written; don't run localedef on garbage.
        return

    cmd = f"localedef -i {base} -f {encoding} {locale}"
    rc, stdout, stderr = run_chroot(str(target), cmd)
    if rc != 0:
        raise RuntimeError(
            f"localedef failed for locale {locale!r} "
            f"(base={base!r}, encoding={encoding!r}): "
            f"{(stderr or '').strip()}"
        )


def generate_vconsole(target, keymap="us"):
    """Generate /etc/vconsole.conf."""
    etc = Path(target) / "etc"
    (etc / "vconsole.conf").write_text(
        f"KEYMAP={keymap}\n"
        f"FONT=Lat2-Terminus16\n"
    )


def set_timezone(target, timezone="UTC"):
    """Set timezone via /etc/localtime symlink."""
    localtime = Path(target) / "etc" / "localtime"
    zoneinfo = Path(target) / "usr" / "share" / "zoneinfo" / timezone

    if localtime.exists() or localtime.is_symlink():
        localtime.unlink()

    if zoneinfo.exists():
        localtime.symlink_to(f"/usr/share/zoneinfo/{timezone}")
    else:
        # The requested zone is missing from the target's zoneinfo — surface it
        # instead of silently shipping UTC. This is the class that hid the
        # glibc-core zoneinfo-staging gap (the install passed with the clock on
        # UTC and no signal); never fall back silently.
        LOG.warning("set_timezone: %r not found under %s/usr/share/zoneinfo — "
                    "falling back to UTC; the installed clock will be UTC, not "
                    "%r", timezone, target, timezone)
        localtime.symlink_to("/usr/share/zoneinfo/UTC")


AI_PANEL_EXTENSION_UUID = "intergen@intergenos.org"


def _augment_enabled_extensions_override(override_text, add_uuid):
    """Given the text of the 91 enabled-extensions gschema override, return the
    text for a higher-priority override that adds add_uuid to enabled-extensions.

    Returns the new override text, or None if the source has no parseable
    enabled-extensions line or add_uuid is already present (nothing to do).
    Pure (no I/O) so the list parse/merge is unit-testable.
    """
    import ast
    for line in override_text.splitlines():
        s = line.strip()
        if s.startswith("enabled-extensions="):
            try:
                lst = ast.literal_eval(s.split("=", 1)[1].strip())
            except (ValueError, SyntaxError):
                return None
            if not isinstance(lst, (list, tuple)) or add_uuid in lst:
                return None
            lst = list(lst) + [add_uuid]
            arr = "[" + ", ".join("'%s'" % e for e in lst) + "]"
            return "[org.gnome.shell]\nenabled-extensions=%s\n" % arr
    return None


def enable_ai_panel_extension(target):
    """Opt-in enable of the InterGen AI panel GNOME extension (D-010).

    The default 91_intergenos-extensions.gschema.override deliberately OMITS
    intergen@intergenos.org (AI is opt-in); when the user chooses AI at install,
    ship a higher-priority 95 override (gschema overrides are last-wins by
    filename) that adds it, derived from the 91 default list READ FROM THE TARGET
    so it stays in sync with whatever shipped. The caller must run
    glib-compile-schemas in the chroot afterward for the change to take effect.

    Returns True if the 95 override was written (recompile needed), False if
    skipped (source missing / extension already enabled by default).
    """
    schemas = Path(target) / "usr" / "share" / "glib-2.0" / "schemas"
    src = schemas / "91_intergenos-extensions.gschema.override"
    if not src.exists():
        LOG.warning("enable_ai_panel_extension: %s missing; cannot opt-in the "
                    "AI panel extension", src)
        return False
    new_text = _augment_enabled_extensions_override(
        src.read_text(), AI_PANEL_EXTENSION_UUID)
    if new_text is None:
        return False
    (schemas / "95_intergen-ai.gschema.override").write_text(
        "# Opt-in (D-010): the InterGen AI panel extension is enabled here\n"
        "# ONLY because InterGen AI was chosen at install time. Numbered above\n"
        "# 91 so it wins; derived from 91's list so it stays in sync.\n"
        + new_text)
    return True


def generate_network(target):
    """Generate systemd-networkd DHCP config."""
    netdir = Path(target) / "etc" / "systemd" / "network"
    netdir.mkdir(parents=True, exist_ok=True)

    (netdir / "10-dhcp.network").write_text(
        "[Match]\n"
        "Name=en*\n"
        "\n"
        "[Network]\n"
        "DHCP=yes\n"
    )

    # DNS via systemd-resolved
    resolv = Path(target) / "etc" / "resolv.conf"
    if resolv.exists() or resolv.is_symlink():
        resolv.unlink()
    resolv.symlink_to("/run/systemd/resolve/stub-resolv.conf")


def carry_wifi_connections(target, live_root="/"):
    """Carry the live session's Wi-Fi connection profiles onto the install.

    Operator-proposed 2026-07-11 ("automagically connected on first boot"),
    surfaced as a Confirm-screen opt-out (default ON) that renders only when
    the live session has an active Wi-Fi connection — the r15/D1 ask-only-
    when-it-matters shape. This function is the backend copy step; the
    frontends own the ask, install.py threads the choice.

    Portability rules (v1 — conservative, every skip is reported):
      - Only `[connection] type=wifi` (or the legacy `802-11-wireless`)
        keyfiles are considered; wired/other profiles are ignored (DHCP
        wired config is generate_network()'s job).
      - Open networks (no security section) carry.
      - WPA-PSK/SAE profiles carry ONLY when the secret is system-stored in
        the keyfile itself (`psk=` present, `psk-flags` absent or 0). A
        keyring-scoped secret (psk-flags != 0, or no psk) is NOT portable —
        the live user's keyring does not exist on the target — so the
        profile is skipped, loudly.
      - Enterprise profiles ([802-1x]) are skipped in v1: they commonly
        reference certificate paths that will not exist on the target, and
        silently carrying a broken profile is worse than not carrying it.

    Files are copied line-verbatim with ONE normalization: a `[connection]`
    `permissions=` line is stripped. NM writes `permissions=user:<creator>:;`
    when a profile is created from a user session, and the live session's
    creator (the live user) does not exist on the installed system — a
    carried binding to that user makes the profile unusable by anyone
    (never autoconnects, never offered), which defeats the carry. Dropping
    the line makes it a system-wide connection, matching what NM writes
    when the installed user connects manually. Every other byte is
    preserved (auditable against the live source), with NetworkManager's
    required ownership/permissions (dir 0700, file 0600, root:root — NM
    refuses group/world-readable keyfiles). Same-machine install, so any
    `interface-name=` pin stays valid.

    Returns {"carried": [connection ids], "skipped": {filename: reason},
    "normalized": {filename: reason}} — install.py records the whole dict
    in the forensic trace, so a modified profile on the installed system
    is always explainable from the trace alone.
    """
    import configparser

    src_dir = Path(live_root) / "etc" / "NetworkManager" / "system-connections"
    dst_dir = Path(target) / "etc" / "NetworkManager" / "system-connections"
    carried = []
    skipped = {}
    normalized = {}

    if not src_dir.is_dir():
        return {"carried": carried, "skipped": skipped,
                "normalized": normalized}

    for keyfile in sorted(src_dir.glob("*.nmconnection")):
        cp = configparser.ConfigParser(interpolation=None, strict=False,
                                       delimiters=("=",))
        try:
            cp.read_string(keyfile.read_text(errors="replace"))
        except (configparser.Error, OSError) as e:
            skipped[keyfile.name] = f"unparseable ({e.__class__.__name__})"
            continue

        conn_type = cp.get("connection", "type", fallback="")
        if conn_type not in ("wifi", "802-11-wireless"):
            continue  # not a Wi-Fi profile — not this feature's concern
        conn_id = cp.get("connection", "id", fallback=keyfile.stem)

        if cp.has_section("802-1x"):
            skipped[keyfile.name] = "enterprise-8021x-not-portable-v1"
            continue

        sec = None
        for cand in ("wifi-security", "802-11-wireless-security"):
            if cp.has_section(cand):
                sec = cand
                break
        if sec is not None:
            psk = cp.get(sec, "psk", fallback=None)
            psk_flags = cp.get(sec, "psk-flags", fallback="0")
            if psk is None or psk_flags.strip() != "0":
                skipped[keyfile.name] = "secret-not-system-stored"
                continue

        dst_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(dst_dir, 0o700)
        dst = dst_dir / keyfile.name
        # Strip the creator binding (see docstring): a permissions= line
        # references the live-session user, who does not exist on the
        # target — carrying it yields a profile NM will never autoconnect
        # or offer. The `permissions` key is only defined for the
        # [connection] section (NM keyfile format), so a line-level match
        # cannot collide with another section's keys. All other lines are
        # written byte-for-byte.
        out_lines = []
        stripped = False
        for line in keyfile.read_text(errors="replace").splitlines(True):
            if line.strip().startswith("permissions="):
                stripped = True
                continue
            out_lines.append(line)
        dst.write_text("".join(out_lines))
        if stripped:
            normalized[keyfile.name] = "live-user-permissions-stripped"
            LOG.info("Wi-Fi carry: %s — stripped live-user permissions "
                     "binding (system-wide on target)", conn_id)
        os.chmod(dst, 0o600)
        if os.geteuid() == 0:
            os.chown(dst, 0, 0)
        carried.append(conn_id)
        LOG.info("Wi-Fi carry: %s -> installed system", conn_id)

    return {"carried": carried, "skipped": skipped,
            "normalized": normalized}


def _live_build_id():
    """BUILD_ID of the RUNNING medium (stamped by build-squashfs), or None.

    Recorded onto the target as IMAGE_VERSION so an installed system can
    say which medium installed it (N-6) — the hostname is operator-typed
    and the install trace previously recorded no source-media identity.
    """
    try:
        with open("/etc/os-release") as f:
            for line in f:
                if line.startswith("BUILD_ID="):
                    return line.split("=", 1)[1].strip().strip('"') or None
    except OSError:
        pass
    return None


def generate_os_release(target):
    """Record the medium's build identity onto the shipped os-release.

    The release identity strings (NAME, VERSION, VERSION_ID, the codename,
    PRETTY_NAME, LOGO) are authored in exactly one place — the files
    packages/core/intergenos-base-files ships — and the packages phase has
    already installed them on the target by the time the config phase runs
    (PHASE_PACKAGES precedes PHASE_CONFIG in installer/backend/install.py).
    This step therefore does not restate any of them. It reads what the
    package installed, replaces any medium stamp with the running medium's
    BUILD_ID recorded as IMAGE_VERSION (N-6), and writes the file back.

    Decided 2026-08-19: single-source the identity. This function used to
    write its own hardcoded copy of every field, which made two hand-
    maintained copies of the same strings with nothing comparing them. They
    had already drifted — the copy here never carried the shipped
    `LOGO=intergenos` line, so every installed system lost that field
    silently (measured on an installed system against the package's own
    files). Reading the installed file removes the second copy, and with it
    the drift.

    /etc/igos-release is likewise the package's file and is left exactly as
    shipped; its presence is asserted so a target that never received the
    package fails here rather than at first boot.

    Raises:
        FileNotFoundError: os-release or igos-release is absent from the
            target, which means intergenos-base-files did not land.
        ValueError: the target's os-release carries none of the identity
            fields, so it is not the file this step is recording onto.
    """
    etc = Path(target) / "etc"
    os_release = etc / "os-release"

    for path in (os_release, etc / "igos-release"):
        if not path.is_file():
            raise FileNotFoundError(
                f"{path} missing — intergenos-base-files ships it; a target "
                f"without it did not receive the package"
            )

    shipped = os_release.read_text()
    missing = [field for field in OS_RELEASE_IDENTITY_FIELDS
               if not re.search(rf"^{field}=", shipped, re.M)]
    if missing:
        raise ValueError(
            f"{os_release} carries no {', '.join(missing)} line — it is not "
            f"the identity file intergenos-base-files ships"
        )

    # A stamp already on the target (a re-run, or the image build's own
    # Step 2.8 stamp riding the shipped file) is replaced, never appended to.
    content = "".join(
        line for line in shipped.splitlines(keepends=True)
        if not line.startswith(("BUILD_ID=", "IMAGE_VERSION="))
    )
    build_id = _live_build_id()
    if build_id:
        if content and not content.endswith("\n"):
            content += "\n"
        content += f'IMAGE_VERSION="{build_id}"\n'
    os_release.write_text(content)


def generate_branding(target):
    """Assert the shipped /etc/issue and /etc/motd landed on the target.

    Both files are authored in packages/core/intergenos-base-files and
    installed by the packages phase. This step used to write its own copies
    of them; those copies were byte-identical to the package's files, so
    they added a second place to edit and nothing else (proven byte-equal
    before removal, 2026-08-19). Nothing is rewritten here — what remains is
    the check, so a target that never received the package fails loudly
    instead of installing a system with no identity text at all.

    Raises:
        FileNotFoundError: either file is absent from the target.
    """
    etc = Path(target) / "etc"
    for name in ("issue", "motd"):
        path = etc / name
        if not path.is_file():
            raise FileNotFoundError(
                f"{path} missing — intergenos-base-files ships it; a target "
                f"without it did not receive the package"
            )


def generate_crypttab(target, partitions):
    """Generate /etc/crypttab for LUKS-at-install systems (D-001).

    Writes a single line declaring the LUKS root volume:
        cryptroot UUID=<luks-uuid> none <options>

    - "cryptroot" matches CRYPT_NAME in installer/init/fde-init.sh and
      LUKS_MAPPER_NAME in installer/backend/disks.py — these three must
      agree, since fde-init.sh's awk lookup keys on field 1.
    - "UUID=<luks-uuid>" references the LUKS-formatted underlying
      partition (NOT the ext4 filesystem UUID — that lives on the
      mapper, which doesn't exist until cryptsetup-open has run).
    - "none" tells cryptsetup-open to read the passphrase from stdin
      (which fde-init.sh attaches to /dev/tty so the prompt fires).
    - Options come from partitions["crypt_opts"] (a list set by
      disks.partition_disk). Always includes "luks,discard" baseline;
      adds "tpm2" / "fido2" when D-001 EXPERIMENTAL methods are
      enrolled (operator Option A 2026-05-18T22:52Z). fde-init.sh
      reads field 4 to decide which unlock methods to attempt before
      the passphrase prompt.
    - "x-initrd.attach" is always appended for the root volume. Without
      it systemd-cryptsetup-generator emits `Conflicts=umount.target` +
      `Before=umount.target` on systemd-cryptsetup@cryptroot.service, so
      shutdown stops that unit — and runs `systemd-cryptsetup detach
      cryptroot` — while the root filesystem is still mounted on the
      mapper. The detach can only fail there:
          Device cryptroot is still in use.
          Failed to deactivate 'cryptroot': Device or resource busy
          systemd-cryptsetup@cryptroot.service: Failed with result 'exit-code'
      Every FDE install therefore recorded a failed unit at every
      shutdown. With the option the generator drops both umount.target
      ordering lines, nothing attempts an early detach, and the mapper
      is released by systemd-shutdown's own device-detach loop after the
      root filesystem is unmounted — which is what crypttab(5) prescribes
      for the volume holding the root filesystem. The token is inert for
      fde-init.sh (it matches unlock methods by exact token) and is
      recognised by systemd-cryptsetup, so it raises no unknown-option
      warning.

    Only emitted when partitions reflects a LUKS install (presence of
    "luks_enabled": True). Plain installs do not get a /etc/crypttab.
    """
    if not partitions.get("luks_enabled"):
        return  # plain install — no crypttab needed

    etc = Path(target) / "etc"
    etc.mkdir(parents=True, exist_ok=True)

    luks_uuid = _get_uuid(partitions["root"])
    if luks_uuid:
        device_ref = f"UUID={luks_uuid}"
    else:
        # blkid lookup failed — fall through to bare partition path. This
        # is fragile across device renumbering between boots, but better
        # than emitting a broken crypttab line that fde-init.sh would
        # refuse with FATAL.
        device_ref = partitions["root"]

    # crypt_opts default = ["luks", "discard"] for plain-passphrase
    # LUKS installs; partition_disk extends with tpm2/fido2 tokens
    # when EXPERIMENTAL slots get enrolled.
    opts_list = list(partitions.get("crypt_opts") or ["luks", "discard"])
    # Root-volume shutdown-detach ordering — see the docstring. Appended
    # here rather than in disks.partition_disk so it holds for every
    # caller that reaches this writer, including a crypt_opts list built
    # elsewhere; appended once, never duplicated.
    if ROOT_CRYPT_SHUTDOWN_OPT not in opts_list:
        opts_list.append(ROOT_CRYPT_SHUTDOWN_OPT)
    opts = ",".join(opts_list)

    crypttab = (
        "# /etc/crypttab — InterGenOS\n"
        "# Generated by InterGenOS installer (D-001 LUKS-at-install v1.0)\n"
        "# <name>     <device>                <key file>  <options>\n"
        f"cryptroot   {device_ref}    none        {opts}\n"
    )
    (etc / "crypttab").write_text(crypttab)


def generate_grub_defaults(target, partitions, detect_other_oses=True):
    """Generate /etc/default/grub.

    Ratified boot design: GRUB_CMDLINE_LINUX uses PARTUUID for plain
    installs (no installed-system initramfs → kernel resolves root from
    partition table without userland). LUKS installs use the unlocked
    /dev/mapper/cryptroot UUID; the FDE initramfs (D-005) ignores root=
    cmdline and runs cryptsetup via /etc/crypttab, but this fallback
    cmdline is what the grub-loads-vmlinuz recovery path uses (manual
    unlock required for LUKS recovery — documented in the user FDE guide).

    B-041 (T0-2): closes the install-time drift from the ratified image-
    time path. Pre-fix this emitted root=UUID= for both plain + LUKS;
    plain installs would have halted at first boot with "VFS: Unable
    to mount root fs" — same fix mechanism as generate_fstab.

    GRUB_DISABLE_OS_PROBER honors the user's install-time choice (Option C,
    2026-05-24): when detect_other_oses=True (user opted in to dual-boot
    detection), os-prober runs on every kernel update and keeps Windows /
    other-Linux entries fresh in the menu. When False, os-prober is
    disabled permanently (the secure default — os-prober mounts other
    partitions during grub-mkconfig, an attack surface). Default True
    matches Forge's per-install prompt default (most users installing
    on a machine with another OS want dual-boot to keep working). The
    legacy hardcoded `=false` was the source of a real defect: after
    first install + first kernel update, Windows entries would vanish
    from the GRUB menu because the file disagreed with bootloader.py's
    one-shot env-var override.
    """
    etc_default = Path(target) / "etc" / "default"
    etc_default.mkdir(parents=True, exist_ok=True)

    os_prober_value = "false" if detect_other_oses else "true"

    # Duplicate-root= fix has TWO halves; both required.
    #
    #   1. GRUB_CMDLINE_LINUX intentionally does NOT include `root=...`.
    #      /etc/grub.d/10_linux probes the live filesystem and injects
    #      `root=...` for every linux-image menuentry. If both this file
    #      AND 10_linux supply root=, the bare-vmlinuz menuentry's
    #      linux command line carries TWO `root=` args.
    #
    #   2. GRUB_DISABLE_LINUX_PARTUUID=false explicitly. Upstream
    #      10_linux DEFAULTS this to "true" (line 50:
    #      `: ${GRUB_DISABLE_LINUX_PARTUUID=true}`). Without an explicit
    #      `=false` here, 10_linux falls into its device-path branch
    #      (line 60: `LINUX_ROOT_DEVICE=${GRUB_DEVICE}`) and emits
    #      `root=/dev/sda2` — a renamable kernel-name path that breaks
    #      on USB plug-in shifts and other re-enumeration events.
    #      Setting `=false` here forces 10_linux into the PARTUUID
    #      branch (line 274: `LINUX_ROOT_DEVICE=PARTUUID=…`), matching
    #      the UKI's `/etc/kernel/cmdline` content and the ratified
    #      plain-install boot design (2026-04-08/09 + 2026-04-10 FINAL).
    #
    # Surfaced 2026-05-27 install #29 inspection (decided
    # follow-up to the 6-anomaly wave): /etc/default/grub had
    # `root=PARTUUID=…` in GRUB_CMDLINE_LINUX AND grub.cfg's linux line
    # carried a second root= from 10_linux's probe.
    #
    # The UKI menuentry (GRUB_DEFAULT=0) chainloads the UKI directly;
    # it doesn't consume GRUB_CMDLINE_LINUX. The UKI's own .cmdline
    # section is written by generate_kernel_cmdline() and DOES include
    # `root=…` because that file is the kernel's only cmdline source
    # on the UKI boot path.
    # D-030 transparent boot (GBC001.5, 2026-06-05): no `quiet`, no
    # `loglevel=3`. Both suppress the boot output D-030 deliberately surfaces
    # — `quiet` hides systemd [OK]/[FAILED]; `loglevel=3` (err+ only) hides the
    # kernel INFO/NOTICE/WARNING (levels 4-6) that flag a "weird module load or
    # hardware quirk" the moment it happens. Stripping both lets the kernel fall
    # back to its compiled default verbosity; systemd shows status by default
    # once `quiet` is gone. See docs/users/desktop-experience.md.
    # pcie_aspm=off: hard-disable PCIe ASPM bus-wide. The RTL8821CE (rtw88) on
    # HP 15-dw0037wm-class hardware leaves ASPM L1 only briefly on IRQ; under
    # NAPI poll the link stays in L1, RX DMA stalls, and the card escalates from
    # AER "Correctable RxErr" to a fatal "pci bus timeout, check dma status" ->
    # "Hardware restart was requested" that wedges the PCIe bus and LOCKS the
    # machine (observed on a development machine, 2026-06-10 — see G3-12). The rtw88_pci
    # disable_aspm=y module param alone did NOT prevent the lockup (firmware can
    # re-enable L1 substates the module param doesn't reach), so we force ASPM
    # off at the kernel level too. Pairs with disable_msi=y in
    # /etc/modprobe.d/rtw88-aspm.conf. Bus-wide costs some PCIe idle power on
    # laptops, but a card that freezes the system is the worse outcome.
    cmdline_tail = "rootwait vt.default_utf8=1 pcie_aspm=off"
    # GRUB theme + gfxmode + background + color block. Mirrors the
    # set that intergenos-grub-theme/build.sh would have appended to
    # /etc/default/grub at package install time, but pulled into the
    # Forge SoT here because this function does a full write_text()
    # — anything the package wrote earlier would otherwise be wiped.
    # Surfaced 2026-05-27 install #27: theme settings package-installed
    # then overwritten here, leaving the installed system with no
    # GRUB_THEME, so grub-mkconfig's 00_header never emitted `set
    # theme=...` and the InterGenOS background never displayed.
    #
    # Resolution chain mirrors the 14 PNGs shipped by intergenos-grub-
    # theme to /boot/grub/backgrounds/<WxH>.png + the 1920x1080
    # default at /boot/grub/grub_background.png (Steam hardware-survey
    # set; covers 16:9 + 16:10 + 21:9 aspect families). 1920x1080 leads:
    # it is the resolution the theme is drawn for — at 4K-class native
    # modes the unscaled theme font renders illegibly small (measured on
    # a 3840x2400 panel), so the menu prefers the blessed mode and GRUB
    # falls through for panels that cannot serve it.
    gfx_chain = (
        "1920x1080,3840x2400,3840x2160,3440x1440,3072x1920,2560x1600,"
        "2560x1440,1920x1200,1680x1050,1600x900,1366x768,1280x800,"
        "1024x768,800x600,auto"
    )
    # EFI installs read grub's config + assets from the unencrypted ESP (an FDE
    # root fs is LUKS/argon2id, which GRUB cannot unlock); BIOS installs keep the
    # legacy /boot/grub root-fs paths (no ESP, and BIOS GRUB reads the root fs).
    if partitions.get("efi"):
        grub_theme_path = "/EFI/InterGenOS/themes/intergenos/theme.txt"
        grub_bg_path = (
            "/EFI/InterGenOS/themes/intergenos/backgrounds/grub_background.png"
        )
    else:
        grub_theme_path = "/boot/grub/themes/intergenos/theme.txt"
        grub_bg_path = "/boot/grub/grub_background.png"
    # THE DEFAULT IS A NAME, NOT A POSITION. GRUB_DEFAULT=0 selects whatever
    # entry happens to be first, and the unified-kernel entry is first only
    # because /etc/grub.d/06_uki sorts before 10_linux. Any generator that
    # later emits an entry ahead of it would take the default silently, on a
    # machine that boots correctly today. 06_uki gives its newest entry the
    # fixed id below and this pins that id, which no ordering can move.
    from .bootloader import STABLE_UKI_MENU_ID

    # An encrypted install whose stock Linux menu entries survive
    # (bootloader.apply_fde_menu_policy keeps them only when /boot carries an
    # initramfs that can plausibly unlock) must also be TOLD what to unlock:
    # those entries name the mapper device as the root filesystem and carry no
    # way to open it. The unified-kernel path does not read this cmdline at
    # all — its own embedded cmdline is written by generate_kernel_cmdline —
    # so adding this affects only the fallback entries.
    crypt_fragment = ""
    if partitions.get("luks_enabled"):
        luks_uuid = _get_uuid(partitions.get("root"))
        if luks_uuid:
            crypt_fragment = f" cryptdev=UUID={luks_uuid}"
        else:
            # No uuid to name. Emitting nothing is right: a cryptdev= pointing
            # at a renamable kernel device path would be worse than none, and
            # the entries are withheld anyway when the initramfs cannot unlock.
            LOG.warning(
                "Encrypted install: no filesystem uuid for %s, so the fallback "
                "boot entries carry no cryptdev=. They cannot unlock the root "
                "filesystem on their own.", partitions.get("root"),
            )

    (etc_default / "grub").write_text(
        "# GRUB defaults for InterGenOS\n"
        f"GRUB_DEFAULT={STABLE_UKI_MENU_ID}\n"
        "GRUB_TIMEOUT_STYLE=menu\n"
        "GRUB_TIMEOUT=10\n"
        'GRUB_DISTRIBUTOR="InterGenOS"\n'
        'GRUB_CMDLINE_LINUX_DEFAULT=""\n'
        f'GRUB_CMDLINE_LINUX="{cmdline_tail}{crypt_fragment}"\n'
        "GRUB_DISABLE_LINUX_PARTUUID=false\n"
        f"GRUB_DISABLE_OS_PROBER={os_prober_value}\n"
        f"GRUB_GFXMODE={gfx_chain}\n"
        f'GRUB_BACKGROUND="{grub_bg_path}"\n'
        f'GRUB_THEME="{grub_theme_path}"\n'
        'GRUB_COLOR_NORMAL="light-gray/black"\n'
        'GRUB_COLOR_HIGHLIGHT="light-blue/black"\n'
    )


def _root_arg_for_cmdline(partitions):
    """Resolve the canonical `root=` kernel-cmdline fragment for an install.

    Plain installs: `root=PARTUUID=<part-uuid-of-root>` — the kernel reads
    PARTUUID from the partition table at mount time without needing an
    initramfs or userland blkid. This is the ratified design (2026-04-08/
    09 + 2026-04-10 FINAL + Q-INIT).

    LUKS installs: `root=UUID=<fs-uuid-of-mapper>` — the FDE initramfs
    handles the actual unlock via /etc/crypttab and exposes the mapper
    node; the kernel root= is informational on this path because
    fde-init.sh has already done switch_root by the time the kernel-level
    root= resolution would fire. Kept consistent with the fstab entry.

    Returns a string like `root=PARTUUID=abc-123` or `root=UUID=def-456`.
    Falls back to `root=<raw-device-path>` only when blkid fails — last-
    resort path that should not be exercised on a healthy install.
    """
    if partitions.get("root_mapper"):
        root_mapper = partitions["root_mapper"]
        root_uuid = _get_uuid(root_mapper)
        return f"root=UUID={root_uuid}" if root_uuid else f"root={root_mapper}"
    root_partuuid = _get_partuuid(partitions["root"])
    if root_partuuid:
        return f"root=PARTUUID={root_partuuid}"
    return f"root={partitions['root']}"


def generate_kernel_cmdline(target, partitions):
    """Write /etc/kernel/cmdline — UKI source-of-truth cmdline (B-041 + D-005).

    The linux-kernel package's post_install hook (D-005 Phase A) bakes
    /etc/kernel/cmdline into the UKI's .cmdline section via ukify. Without
    this file the hook falls back to /proc/cmdline (post-install.sh:141-145)
    which at install time is the LIVE ISO's cmdline (`root=live-iso-stuff
    igos.mode=live ...`). That would land in the first installed-system
    UKI and cause boot failure.

    Writing /etc/kernel/cmdline here is the install-time half of the B-041
    resolution explicitly anticipated by the post-install hook comment
    "B-041 cmdline drift: resolves via UKI .cmdline section bundling
    (sourced from /etc/kernel/cmdline; falls back to /proc/cmdline if
    unset)".

    Cmdline contents:
      root=PARTUUID=...  (or root=UUID=... for LUKS — see
                          _root_arg_for_cmdline rationale)
      rootwait           — wait for storage to enumerate (required for
                          no-initramfs path; matches image-time create-
                          image.sh:177 emission)
      quiet              — suppress kernel printk noise; `splash` removed
                          per D-030 no-Plymouth transparency posture
                          (operator ratification 2026-05-22, commit
                          8de756f1; see docs/users/desktop-experience.md
                          §"No Plymouth boot splash")
      loglevel=3         — surface warnings + errors but suppress noise
                          (matches installer/init/cmdline.live.txt
                          posture for the installed system)
    """
    kernel_dir = Path(target) / "etc" / "kernel"
    kernel_dir.mkdir(parents=True, exist_ok=True)

    root_arg = _root_arg_for_cmdline(partitions)
    # vt.default_utf8=1 is explicit-set rather than relying on kernel
    # default (which is "1" on modern kernels but unconfigured during
    # the early-boot framebuffer-takeover window). Without it, the
    # framebuffer console + VT encoding can briefly disagree, rendering
    # unmapped Unicode chars as "@" placeholders during the window
    # between kernel takeover of fbcon and systemd-vconsole-setup
    # (which runs late, after PID-1-systemd is up). Surfaced 2026-05-26
    # install #18 first-boot.
    # D-030 transparent boot (GBC001.5): no `quiet`/`loglevel=3` on the UKI
    # cmdline either — same rationale as cmdline_tail above.
    # pcie_aspm=off: force PCIe ASPM off bus-wide on the installed UKI cmdline.
    # The RTL8821CE (rtw88) escalates from AER RxErr noise to a fatal "pci bus
    # timeout, check dma status" DMA hang that wedges the bus and LOCKS the
    # machine (G3-12, observed on a development machine 2026-06-10); the rtw88_pci disable_aspm=y
    # module param alone did NOT prevent it. Pairs with disable_msi=y in
    # /etc/modprobe.d/rtw88-aspm.conf.
    cmdline = f"{root_arg} rootwait vt.default_utf8=1 pcie_aspm=off"

    # LUKS installs: pass the encrypted volume's identity on the cmdline as a
    # deterministic fallback to the baked /etc/crypttab — the FDE initramfs
    # (installer/init/fde-init.sh) reads `cryptdev=` when crypttab is absent or
    # unreadable. Use the LUKS partition's stable fs UUID (the SAME identifier
    # generate_crypttab writes), NOT a raw /dev/sdaN path (which re-enumerates
    # across boots and USB plug-ins — the brittle form the A12 manual completion
    # had to use). fde-init.sh resolves UUID= via a blkid scan, since the busybox
    # initramfs has no udev to populate /dev/disk/by-uuid. (Gap B device wiring.)
    if partitions.get("luks_enabled"):
        luks_uuid = _get_uuid(partitions["root"])
        if luks_uuid:
            cmdline = f"{cmdline} cryptdev=UUID={luks_uuid}"
        else:
            cmdline = f"{cmdline} cryptdev={partitions['root']}"

    (kernel_dir / "cmdline").write_text(cmdline + "\n")


def generate_all(target, partitions, hostname="intergenos",
                 locale="en_US.UTF-8", keymap="us", timezone="UTC",
                 detect_other_oses=True):
    """Generate all system configuration files.

    detect_other_oses: Option C 2026-05-24 — threaded through to
    generate_grub_defaults so the installed system's
    /etc/default/grub permanently reflects the user's dual-boot-
    detection choice. See generate_grub_defaults docstring.
    """
    # FIRST: the account databases must exist before anything downstream
    # touches accounts — the users phase's useradd --root is next but one.
    # base-files ships them as reference data, never as /etc payload
    # (2026-07-24), so the install creates them here or they do not exist.
    seed_account_databases(target)
    generate_fstab(target, partitions)
    generate_crypttab(target, partitions)   # D-001 LUKS-at-install
    generate_kernel_cmdline(target, partitions)  # B-041 UKI source-of-truth
    generate_hostname(target, hostname)
    generate_machine_id(target)
    generate_locale(target, locale)
    generate_vconsole(target, keymap)
    set_timezone(target, timezone)
    generate_network(target)
    generate_os_release(target)
    generate_branding(target)
    generate_grub_defaults(target, partitions, detect_other_oses=detect_other_oses)
    # LAST: the display-controller record the first-boot welcome reads to
    # decide whether to offer this machine's vendor driver/compute stack.
    # It installs nothing and reaches no network — it writes down what the
    # same PCI probe the hardware gate uses already found.
    write_detection_record(target)


def generate_machine_id(target):
    """Write a random 32-hex-char /etc/machine-id on the target.

    systemd-firstboot.service activates on boot when /etc/machine-id is
    missing OR set to the literal string "uninitialized" (see man
    systemd-firstboot.service ConditionFirstBoot=). If we don't write
    this file, the installed system drops the user into the interactive
    firstboot prompt on first boot — a terrible UX for a 'completed'
    install. Surfaced 2026-05-26 install attempt #18 first-boot: user
    saw firstboot prompt + scary screen artifacts, didn't know if system
    was bricked.

    The value must be 32 lowercase hex chars + trailing newline, mode
    0444 (read-only for everyone — systemd refuses to read otherwise).
    See man machine-id(5). uuid.uuid4().hex gives exactly the right
    shape (128-bit random, hex-encoded, no dashes).

    Sibling file /var/lib/dbus/machine-id is shipped as a symlink to
    /etc/machine-id by the dbus package — no additional handling needed
    here.
    """
    mid = uuid.uuid4().hex
    path = Path(target) / "etc" / "machine-id"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(mid + "\n")
    path.chmod(0o444)


def _get_uuid(device):
    """Get filesystem UUID for a device."""
    result = subprocess.run(
        ["blkid", "-s", "UUID", "-o", "value", device],
        capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else None


def _get_partuuid(device):
    """Get GPT/MBR PARTUUID for a partition.

    Required for the ratified PARTUUID + rootwait + no-installed-system-
    initramfs boot path (B-041 resolution). The kernel reads PARTUUID
    from the partition table directly at mount time, without needing
    userland blkid or an initramfs — that is the whole point of choosing
    PARTUUID over filesystem UUID for plain installs.

    Returns None on blkid failure (e.g., MBR partition without disk
    signature) — callers fall back to the raw device path.
    """
    result = subprocess.run(
        ["blkid", "-s", "PARTUUID", "-o", "value", device],
        capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else None
