name: fftw
version: "3.3.11"
release: 1
description: Fastest Fourier Transform in the West (float + double precision)
license: GPL-2.0-or-later
homepage: http://www.fftw.org/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: http://fftw.org/fftw-${version}.tar.gz
  sha256: 5630c24cdeb33b131612f7eb4b1a9934234754f9f388ff8617458d0be6f239a1
dependencies:
  build:
  - pkgconf
  host: []
  runtime: []
