name: libaom
version: "3.13.1"
release: 1
description: AV1 video codec reference implementation
license: BSD-2-Clause
homepage: https://aomedia.googlesource.com/aom/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://storage.googleapis.com/aom-releases/libaom-${version}.tar.gz
  sha256: 19e45a5a7192d690565229983dad900e76b513a02306c12053fb9a262cbeca7d
patches:
  - libaom-3.13.1-nasm3-1.patch
dependencies:
  build:
  - nasm
  host: []
  runtime: []
