name: font-alias
version: 1.0.5
release: 1
description: X font aliases
license: MIT
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/font/font-alias-${version}.tar.xz
  sha256: 9f89e217bb73e0e3636a0a493fbf8b7c995156e0c53d9a0476d201b67c2d6b6e
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
