name: totem-pl-parser
version: "3.26.6"
release: 1
description: Playlist parser library
license: LGPL-2.0-or-later
homepage: ''
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-${version}.tar.xz
  sha256: c0df0f68d5cf9d7da43c81c7f13f11158358368f98c22d47722f3bd04bd3ac1c
dependencies:
  build:
  - libarchive
  - libgcrypt
  - libxml2
  - cmake
  - glib2
  host: []
  runtime: []
verify_paths:
  - /usr/lib/libtotem-plparser-mini.so
