name: systemd
version: '259.1'
release: 1
description: System and service manager
license: LGPL-2.1-or-later
source:
- url: https://github.com/systemd/systemd/archive/v${version}/systemd-${version}.tar.gz
  sha256: 7af4f36db512ad2f0f749a0f9886370edeb2bb5128014fc47cdf73702c7e1911
- url: https://anduin.linuxfromscratch.org/LFS/systemd-man-pages-259.1.tar.xz
  sha256: 0d130b265ed45015a88c35a1647463945dacbb48a379b506d09b1584360a49e1
dependencies:
  build:
    - meson
    - ninja
  host:
  - jinja2
  - pyelftools
  - util-linux-core
  - kmod
  - libcap
  - openssl
  - elfutils
  - acl
  - expat
  runtime: []
tier: core
build_style: meson
