name: glibc-core
version: '2.43'
release: 1
description: GNU C Library (final system)
license: LGPL-2.1-or-later
homepage: https://www.gnu.org/software/libc/
tier: core
build_style: custom
install_func: do_install
source:
- url: https://ftp.gnu.org/gnu/glibc/glibc-${version}.tar.xz
  sha256: d9c86c6b5dbddb43a3e08270c5844fc5177d19442cf5b8df4be7c07cd5fa3831
patches:
- glibc-fhs-1.patch
dependencies:
  build: []
  host: []
  runtime: []
