name: webkitgtk-gtk3
version: "2.50.5"
release: 1
description: Web content engine for GTK (GTK-3 version)
license: LGPL-2.0-or-later
homepage: https://webkitgtk.org/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://webkitgtk.org/releases/webkitgtk-${version}.tar.xz
  sha256: 8737631bac3e9c7ad3e5208f9370e076c09d9c45b39980021ce54edadcc6f94f
dependencies:
  build:
  - cairo
  - gst-plugins-base
  - gst-plugins-bad
  - gtk3
  - libgudev
  - libsoup3
  - libwebp
  - openjpeg2
  - ruby
  - enchant
  - unifdef
  - bubblewrap
  - geoclue2
  - libseccomp
  - xdg-dbus-proxy
  - libX11
  - wayland
  - icu
  - cmake
  - glib2
  - gtk4
  - harfbuzz
  - hicolor-icon-theme
  - lcms2
  - libavif
  - libjxl
  - libsecret
  - libtasn1
  - mesa
  - which
  - woff2
  host: []
  runtime: []
