name: evolution-data-server
version: "3.58.3"
release: 1
description: Calendar and contacts data server
license: LGPL-2.0-or-later
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://download.gnome.org/sources/evolution-data-server/3.58/evolution-data-server-${version}.tar.xz
  sha256: da136d1190d9e8b09499452f6058e24eee6b77f441a8c769f74a52451bf379f1
patches:
  - file: evolution-data-server-3.58.3-security_fixes-1.patch
    sha256: f2388a8c41e7535b6249b8b104f3ac7e77edf61eafa1de982047602c7fff027e
dependencies:
  build:
  - libical
  - libsecret
  - nss
  - gnome-online-accounts
  - gtk3
  - gtk4
  - libgweather
  - vala
  - webkitgtk
  - glib2
  - icu
  - libcanberra
  - mitkrb
  - openldap
  host: []
  runtime: []
verify_paths:
  - /usr/lib/libcamel-1.2.so
