# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
"""The boot menu on a full-disk-encryption install: what is offered, and first.

WHAT WAS MEASURED, on an installed encrypted machine's own ESP configuration
(/boot/efi/EFI/InterGenOS/grub.cfg, read at 2026-08-24):

* the unified kernel image entry, generated by /etc/grub.d/06_uki, is FIRST —
  but only because 06 sorts before 10. Nothing names it. The stock header emits
  `set default="0"`, which is a POSITION, so anything that later generates an
  entry ahead of it silently moves the default onto that entry instead;
* below it, /etc/grub.d/10_linux generates three more entries — the plain one,
  the advanced one and the recovery one — each with
  root=/dev/mapper/cryptroot, NO cryptdev= of any kind, and
  initrd /boot/initramfs.img;
* /boot/initramfs.img on that machine is FIFTY BYTES: an empty gzipped cpio,
  the placeholder the installer writes so the image builder has something to
  bundle. It contains no cryptsetup and no init. The installer's own code says
  an encrypted install replaces it with the real unlock initramfs at kernel-hook
  time, and on that machine it was never replaced.

So all three of those entries would hand the kernel an encrypted root device, no
way to ask for a passphrase, and an empty early-userspace. They are not a
fallback; they are three ways to reach a panic, presented in the same menu, in
the same style, as the entry that works.

WHAT THIS FILE ASSERTS:

* the unified-kernel entry carries a STABLE NAME and the boot configuration
  pins that name, so the default is not a position that a future generator can
  take;
* on an encrypted install whose /boot carries only the placeholder, the entries
  that cannot unlock are not generated at all, and the reason is written down
  where an operator will find it;
* on an encrypted install whose /boot carries a real unlock initramfs, those
  entries ARE kept and DO carry the device to unlock;
* a plain install is untouched by any of it.

WHAT THIS FILE CANNOT ASSERT. Whether a fallback entry actually boots is a
cold-boot question on real hardware, and that leg belongs to the operator. These
tests measure what the generators produce, which is the part that can be wrong
in a way nobody notices until the machine will not start.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

REPO_ROOT = Path(__file__).resolve().parents[2]
UKI_GENERATOR = (REPO_ROOT / "packages" / "desktop" / "intergenos-grub-theme"
                 / "assets" / "etc-grub.d" / "06_uki")

#: The name the boot configuration must pin. A position cannot be pinned.
STABLE_UKI_ID = "intergenos-uki"


def _sym(module, name):
    """A symbol this behaviour needs, or a legible failure."""
    try:
        return getattr(module, name)
    except AttributeError:
        raise AssertionError(
            f"{module.__name__} has no {name!r}: the installer has no notion of "
            "which boot-menu entries an encrypted install may safely offer."
        ) from None


class UkiEntryIsNamedTests(unittest.TestCase):
    """Run the SHIPPED generator and read what it emits."""

    def setUp(self):
        self._tmp = TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        if not shutil.which("bash"):
            self.skipTest("bash is not available, so the generator cannot run")

    def _run_generator(self, kernels):
        """Emit the menu for an ESP holding *kernels*, newest first in the list."""
        esp = self.tmp / "boot" / "efi" / "EFI" / "Linux"
        esp.mkdir(parents=True)
        # Oldest written first so modification time orders them; the generator
        # sorts by mtime descending and the first name in *kernels* must win.
        for index, kver in enumerate(reversed(kernels)):
            path = esp / f"intergenos-{kver}.efi"
            path.write_bytes(b"not a real image")
            os.utime(path, (1_700_000_000 + index, 1_700_000_000 + index))

        # grub-probe is not meaningful outside a real boot environment; the
        # generator's only use of it is to resolve the ESP filesystem uuid, so
        # it is answered with a fixed one. Everything else in the script runs.
        stub_dir = self.tmp / "bin"
        stub_dir.mkdir()
        probe = stub_dir / "grub-probe"
        probe.write_text("#!/bin/sh\necho 1234-ABCD\n")
        probe.chmod(0o755)

        env = dict(os.environ)
        env["PATH"] = f"{stub_dir}:{env.get('PATH', '/usr/bin:/bin')}"
        script = self.tmp / "06_uki"
        text = UKI_GENERATOR.read_text(encoding="utf-8")
        # The generator hard-codes the live ESP path; point it at the fixture.
        text = text.replace("ESP_UKI_DIR=/boot/efi/EFI/Linux",
                            f"ESP_UKI_DIR={esp}")
        text = text.replace("grub-probe --target=fs_uuid /boot/efi",
                            "grub-probe --target=fs_uuid")
        script.write_text(text)
        script.chmod(0o755)
        proc = subprocess.run(["bash", str(script)], capture_output=True,
                              text=True, env=env, timeout=60)
        self.assertEqual(proc.returncode, 0,
                         f"the generator failed: {proc.stderr}")
        return proc.stdout

    def test_the_newest_entry_carries_a_stable_name(self):
        out = self._run_generator(["6.18.10-igos-17", "6.18.9-igos-16"])
        first = out.split("menuentry", 2)[1]
        self.assertIn(f"--id {STABLE_UKI_ID}", first,
                      "the newest unified-kernel entry has no stable name, so "
                      "the boot configuration can only point at its POSITION:\n"
                      + out)

    def test_older_entries_are_named_too_and_do_not_take_the_stable_name(self):
        out = self._run_generator(["6.18.10-igos-17", "6.18.9-igos-16"])
        self.assertEqual(out.count(f"--id {STABLE_UKI_ID} "), 1,
                         "the stable name must identify exactly one entry:\n" + out)
        self.assertIn(f"--id {STABLE_UKI_ID}-6.18.9-igos-16", out,
                      "an older kernel's entry cannot be selected by name:\n" + out)

    def test_the_newest_kernel_is_still_the_first_entry(self):
        out = self._run_generator(["6.18.10-igos-17", "6.18.9-igos-16"])
        self.assertLess(out.index("6.18.10-igos-17"), out.index("6.18.9-igos-16"),
                        "the newest kernel is no longer first:\n" + out)


class GrubDefaultPinsTheUkiTests(unittest.TestCase):
    def setUp(self):
        self._tmp = TemporaryDirectory()
        self.target = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)

    def _generate(self, partitions):
        from installer.backend import config
        config.generate_grub_defaults(self.target, partitions,
                                      detect_other_oses=False)
        return (self.target / "etc" / "default" / "grub").read_text()

    def test_the_default_is_a_name_not_a_position(self):
        text = self._generate({"efi": "/dev/sda1", "root": "/dev/sda2"})
        self.assertIn(f"GRUB_DEFAULT={STABLE_UKI_ID}", text,
                      "the default boot entry is a position, so any generator "
                      "that emits an entry earlier takes it:\n" + text)
        self.assertNotIn("GRUB_DEFAULT=0", text)

    def test_the_timeout_is_still_written(self):
        """Unchanged behaviour, asserted so the pin cannot quietly drop it."""
        text = self._generate({"efi": "/dev/sda1", "root": "/dev/sda2"})
        self.assertIn("GRUB_TIMEOUT=10", text)
        self.assertIn("GRUB_TIMEOUT_STYLE=menu", text)


class FallbackEntriesOnAnEncryptedInstallTests(unittest.TestCase):
    """The generator-level decision, measured on a fixture target tree."""

    def setUp(self):
        self._tmp = TemporaryDirectory()
        self.target = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        self.grub_d = self.target / "etc" / "grub.d"
        self.grub_d.mkdir(parents=True)
        self.linux_generator = self.grub_d / "10_linux"
        self.linux_generator.write_text("#!/bin/sh\n# stock generator\n")
        self.linux_generator.chmod(0o755)
        self.boot = self.target / "boot"
        self.boot.mkdir(parents=True)

    def _initramfs(self, size):
        (self.boot / "initramfs.img").write_bytes(b"\0" * size)

    def _apply(self, partitions):
        from installer.backend import bootloader
        return _sym(bootloader, "apply_fde_menu_policy")(self.target, partitions)

    def _is_executable(self):
        return bool(self.linux_generator.stat().st_mode & stat.S_IXUSR)

    def test_a_placeholder_initramfs_means_those_entries_are_not_generated(self):
        self._initramfs(50)
        decision = self._apply({"luks_enabled": True, "root": "/dev/sda2"})
        self.assertFalse(
            self._is_executable(),
            "entries that hand an encrypted root to an empty early-userspace "
            "are still generated",
        )
        self.assertTrue(decision.suppressed)
        note = self.grub_d / "10_linux.disabled-by-intergenos"
        self.assertTrue(note.is_file(),
                        "nothing on the machine records why the entries are gone")
        text = note.read_text()
        self.assertIn("initramfs", text.lower())
        self.assertIn("50", text, "the note does not state the measured size")

    def test_a_real_unlock_initramfs_keeps_the_entries(self):
        self._initramfs(2 * 1024 * 1024)
        decision = self._apply({"luks_enabled": True, "root": "/dev/sda2"})
        self.assertTrue(self._is_executable(),
                        "a usable fallback was removed")
        self.assertFalse(decision.suppressed)
        self.assertFalse((self.grub_d / "10_linux.disabled-by-intergenos").exists())

    def test_a_plain_install_is_untouched(self):
        self._initramfs(50)
        decision = self._apply({"luks_enabled": False, "root": "/dev/sda2"})
        self.assertTrue(self._is_executable())
        self.assertFalse(decision.suppressed)
        self.assertFalse((self.grub_d / "10_linux.disabled-by-intergenos").exists())


class FallbackEntriesNameTheDeviceToUnlockTests(unittest.TestCase):
    def setUp(self):
        self._tmp = TemporaryDirectory()
        self.target = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)
        (self.target / "boot").mkdir(parents=True)

    def _generate(self, partitions, initramfs_bytes):
        (self.target / "boot" / "initramfs.img").write_bytes(
            b"\0" * initramfs_bytes)
        from installer.backend import config
        config.generate_grub_defaults(self.target, partitions,
                                      detect_other_oses=False)
        return (self.target / "etc" / "default" / "grub").read_text()

    def test_a_kept_fallback_carries_the_device_to_unlock(self):
        from installer.backend import config
        original = config._get_uuid
        config._get_uuid = lambda device: "1111-2222"
        try:
            text = self._generate(
                {"efi": "/dev/sda1", "root": "/dev/sda2", "luks_enabled": True},
                2 * 1024 * 1024)
        finally:
            config._get_uuid = original
        self.assertIn("cryptdev=UUID=1111-2222", text,
                      "the fallback entries name an encrypted root and no way "
                      "to unlock it:\n" + text)

    def test_a_plain_install_names_no_device_to_unlock(self):
        text = self._generate({"efi": "/dev/sda1", "root": "/dev/sda2"}, 50)
        self.assertNotIn("cryptdev=", text)


if __name__ == "__main__":
    unittest.main()
