name: hatch-vcs
version: "0.5.0"
release: 1
description: Hatch plugin for VCS version source
license: MIT
homepage: https://github.com/ofek/hatch-vcs
tier: core
build_style: custom
install_func: do_install
source:
- url: https://files.pythonhosted.org/packages/source/h/hatch-vcs/hatch_vcs-${version}.tar.gz
  sha256: 0395fa126940340215090c344a2bf4e2a77bcbe7daab16f41b37b98c95809ff9
dependencies:
  build:
  - hatchling
  - setuptools-scm
  host: []
  runtime: []

verify_paths:
  - /usr/lib/python3.13/site-packages
