name: openjpeg2
version: 2.5.3
release: 1
description: JPEG 2000 codec library
license: BSD-2-Clause
homepage: ''
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://github.com/uclouvain/openjpeg/archive/v${version}/openjpeg-${version}.tar.gz
  sha256: 368fe0468228e767433c9ebdea82ad9d801a3ad1e4234421f352c8b06e7aa707
dependencies:
  build: []
  host: []
  runtime: []
