name: efibootmgr
version: "18"
release: 1
description: Tool for managing UEFI boot entries
license: GPL-2.0-or-later
homepage: https://github.com/rhboot/efibootmgr
tier: core
build_style: custom
install_func: do_install
source:
- url: https://github.com/rhboot/efibootmgr/archive/${version}/efibootmgr-${version}.tar.gz
  sha256: 442867d12f8525034a404fc8af3036dba8e1fc970998af2486c3b940dfad0874
dependencies:
  build:
  - efivar
  - popt
  host: []
  runtime: []
verify_paths:
  - /usr/sbin/efibootmgr
  - /usr/sbin/efibootdump
