name: appstream
version: "1.1.2"
release: 1
description: AppStream metadata handling library
license: LGPL-2.1-or-later
homepage: https://www.freedesktop.org/wiki/Distributions/AppStream/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://www.freedesktop.org/software/appstream/releases/AppStream-${version}.tar.xz
  sha256: 46b4257100e25a6468ceed7b3ab82441f47b119da3398d30aea6d7b91174b586
dependencies:
  build:
  - curl
  - itstool
  - libfyaml
  - libxml2
  - libxmlb
  - libxslt
  - docbook-xsl-nons
  host: []
  runtime: []
