name: time
version: "1.9"
release: 1
description: GNU time - runs programs and summarizes resource usage
license: GPL-3.0-or-later
homepage: https://www.gnu.org/software/time/
tier: base
build_style: custom
install_func: do_install

source:
  - url: https://ftpmirror.gnu.org/time/time-${version}.tar.gz
    sha256: fbacf0c81e62429df3e33bda4cee38756604f18e01d977338e23306a3e3b521e

dependencies:
  build: []
  host: []
  runtime: []
