name: localsearch
version: "3.10.2"
release: 1
description: Filesystem indexer and metadata extractor
license: GPL-2.0-or-later
homepage: https://gnome.pages.gitlab.gnome.org/localsearch/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/localsearch/3.10/localsearch-${version}.tar.xz
  sha256: b4dd89c85d76617101bad4ec9a33678f631ec5032e9880eb423dce52e878a285
patches:
  - localsearch-3.10.2-security_fixes-1.patch
dependencies:
  build:
  - gexiv2
  - gst-plugins-base
  - tinysparql
  host: []
  runtime: []
