name: hicolor-icon-theme
version: '0.18'
release: 1
description: Default fallback icon theme
license: GPL-2.0-or-later
homepage: https://www.freedesktop.org/wiki/Software/icon-theme/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://icon-theme.freedesktop.org/releases/hicolor-icon-theme-${version}.tar.xz
  sha256: db0e50a80aa3bf64bb45cbca5cf9f75efd9348cf2ac690b907435238c3cf81d7
dependencies:
  build: []
  host: []
  runtime: []
configure_flags: []
verify_paths:
  - /usr/share/icons/hicolor
