name: libdvdread
version: 7.0.1
release: 1
description: DVD reading library
license: GPL-2.0-or-later
homepage: https://www.videolan.org/developers/libdvdread.html
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://get.videolan.org/libdvdread/${version}/libdvdread-${version}.tar.xz
  sha256: 2e3e04a305c15c3963aa03ae1b9a83c1d239880003fcf3dde986d3943355d407
dependencies:
  build: []
  host: []
  runtime: []
