name: colord-gtk
version: "0.3.1"
release: 1
description: GTK integration for colord
license: LGPL-2.1-or-later
homepage: https://www.freedesktop.org/software/colord/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://www.freedesktop.org/software/colord/releases/colord-gtk-${version}.tar.xz
  sha256: c176b889b75630a17f4e3d7ef24c09a3e12368e633496087459c8b53ac3a122d
dependencies:
  build:
  - colord
  - gtk3
  - gtk4
  host: []
  runtime: []
