name: nano
version: "8.7.1"
release: 1
description: Small, friendly text editor with syntax highlighting and UTF-8 support
license: GPL-3.0-or-later
source:
- url: https://www.nano-editor.org/dist/v8/nano-${version}.tar.xz
  sha256: 76f0dcb248f2e2f1251d4ecd20fd30fb400a360a3a37c6c340e0a52c2d1cdedf
dependencies:
  build: []
  host:
  - ncurses
  - gettext
  runtime: []
tier: core
build_style: custom
