name: yelp-xsl
version: '42.1'
release: 1
description: GNOME help stylesheets
license: GPL-2.0-or-later
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://download.gnome.org/sources/yelp-xsl/42/yelp-xsl-${version}.tar.xz
  sha256: 238be150b1653080ce139971330fd36d3a26595e0d6a040a2c030bf3d2005bcd
dependencies:
  build:
  - libxslt
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
