name: nasm
version: "3.01"
release: 1
description: Netwide Assembler
license: BSD-2-Clause
homepage: https://www.nasm.us/
tier: core
build_style: autotools
install_func: do_install
source:
- url: https://www.nasm.us/pub/nasm/releasebuilds/${version}/nasm-${version}.tar.xz
  sha256: b7324cbe86e767b65f26f467ed8b12ad80e124e3ccb89076855c98e43a9eddd4
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
