name: nasm
version: 2.16.03
release: 1
description: Netwide Assembler
license: BSD-2-Clause
homepage: https://www.nasm.us/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.nasm.us/pub/nasm/releasebuilds/${version}/nasm-${version}.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
