name: gtkmm3
version: "3.24.10"
release: 1
description: C++ interface to GTK3
license: LGPL-2.1-or-later
homepage: https://www.gtkmm.org/
tier: extra
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/gtkmm/3.24/gtkmm-${version}.tar.xz
  sha256: 7ab7e2266808716e26c39924ace1fb46da86c17ef39d989624c42314b32b5a76
dependencies:
  build:
  - atkmm
  - gtk3
  - pangomm1
  host: []
  runtime: []
