name: exim
version: 4.99.1
release: 1
description: Message Transfer Agent
license: GPL-2.0-or-later
homepage: https://www.exim.org/
tier: base
build_style: custom

source:
  - url: https://ftp.exim.org/pub/exim/exim4/exim-${version}.tar.xz
    sha256: placeholder-exim-4.99.1

dependencies:
  build:
    - libnsl
    - perl-file-fcntllock
    - linux-pam
  host: []
  runtime: []
