name: exim
version: 4.99.1
release: 1
description: Message Transfer Agent
license: GPL-2.0-or-later
homepage: https://www.exim.org/
tier: base
build_style: custom

source:
  - url: https://ftp.exim.org/pub/exim/exim4/exim-${version}.tar.xz
    sha256: eae967bd49a5f879933b8c6ec88c30475a1c6646232135f37f05b55dbc4e3447

dependencies:
  build:
    - libnsl
    - perl-file-fcntllock
    - linux-pam
  host: []
  runtime: []
