name: libXpm
version: 3.5.17
release: 1
description: X Pixmap library
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/lib/libXpm-${version}.tar.xz
  sha256: 64b31f81019e7d388c822b0b28af8d51c4622b83f1f0cb6fa3fc95e271226e43
dependencies:
  build:
  - libXt
  - libXext
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
- --disable-open-zfile
