name: unixodbc
version: "2.3.14"
release: 1
description: Open Database Connectivity (ODBC) implementation for Unix
license: LGPL-2.1-or-later
homepage: https://www.unixodbc.org/
tier: extra
build_style: custom
install_func: do_install
source:
- url: https://github.com/lurcher/unixODBC/archive/v${version}/unixODBC-${version}.tar.gz
  sha256: 3bd23171aca274820ef5cb4961b191adf2cf98509bea4d1b1b0a8630359ee2fb
dependencies:
  build: []
  host: []
  runtime: []
