name: wayland-protocols
version: '1.38'
release: 1
description: Wayland protocol extensions
license: MIT
homepage: https://wayland.freedesktop.org/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/${version}/downloads/wayland-protocols-${version}.tar.xz
  sha256: ff17292c05159d2b20ce6cacfe42d7e31a28198fa1429a769b03af7c38581dbe
dependencies:
  build:
  - wayland
  host: []
  runtime: []
