name: cairomm1
version: "1.14.5"
release: 1
description: C++ bindings for Cairo graphics library (GTK3 API version 1.0)
license: LGPL-2.0-or-later
homepage: https://www.cairographics.org/cairomm/
tier: extra
build_style: meson
install_func: do_install
source:
- url: https://www.cairographics.org/releases/cairomm-${version}.tar.xz
  sha256: 70136203540c884e89ce1c9edfb6369b9953937f6cd596d97c78c9758a5d48db
dependencies:
  build:
  - cairo
  - libsigcpp2
  - python
  host: []
  runtime: []
verify_paths:
  - /usr/lib/libcairomm-1.0.so
  - /usr/lib/pkgconfig/cairomm-1.0.pc
