name: nettle
version: 3.10.2
release: 1
description: Low-level cryptographic library
license: LGPL-3.0-or-later
homepage: https://www.lysator.liu.se/~nisse/nettle/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://ftpmirror.gnu.org/nettle/nettle-${version}.tar.gz
  sha256: c79255f6cb550eaa07d6e90d859b8c1abe81658115ae8175e74b67ac22c7ed87
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
