name: xorgproto
version: '2024.1'
release: 1
description: X11 protocol headers
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://xorg.freedesktop.org/archive/individual/proto/xorgproto-${version}.tar.xz
  sha256: 372225fd40815b8423547f5d890c5debc72e88b91088fbfb13158c20495ccb59
dependencies:
  build:
  - util-macros
  host: []
  runtime: []
