name: gdm
version: '49.2'
release: 1
description: GNOME Display Manager
license: GPL-2.0-or-later
homepage: https://wiki.gnome.org/Projects/GDM
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/gdm/49/gdm-${version}.tar.xz
  sha256: 9813631f9f5f0f860ea14a437866e60efc7bed3023b7c3b765cc5de1de597a06
dependencies:
  build:
  - accountsservice
  - dconf
  - libcanberra
  - linux-pam
  - gtk3
  - keyutils
  - glib2
  - libgudev
  - systemd
  host: []
  runtime: []
