name: tokei
version: "12.1.2"
release: 1
description: Count your code, quickly
license: MIT OR Apache-2.0
homepage: https://github.com/XAMPPRocky/tokei
tier: extra
build_style: custom
install_func: do_install
source:
  - url: https://github.com/XAMPPRocky/tokei/archive/v12.1.2/tokei-12.1.2.tar.gz
    sha256: 81ef14ab8eaa70a68249a299f26f26eba22f342fb8e22fca463b08080f436e50
build_artifacts:
  - name: tokei-12.1.2-vendor.tar.xz
    generated_by: cargo-vendor
dependencies:
  build:
  - rust
  host: []
  runtime: []
verify_paths:
  - /usr/bin/tokei
