name: mtdev
version: "1.1.7"
release: 1
description: Multitouch protocol translation library
license: MIT
homepage: https://bitmath.org/code/mtdev/
tier: core
build_style: autotools
install_func: do_install
source:
- url: https://bitmath.org/code/mtdev/mtdev-${version}.tar.bz2
  sha256: a107adad2101fecac54ac7f9f0e0a0dd155d954193da55c2340c97f2ff1d814e
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
