name: libgudev
version: '238'
release: 1
description: GObject-based wrapper around libudev
license: LGPL-2.1-or-later
homepage: https://wiki.gnome.org/Projects/libgudev
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/libgudev/238/libgudev-${version}.tar.xz
  sha256: 61266ab1afc9d73dbc60a8b2af73e99d2fdff47d99544d085760e4fa667b5dd1
dependencies:
  build: []
  host: []
  runtime: []
