#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 InterGenJLU
#
# vpnc-scripts — the helper a VPN client executes once a tunnel is up, to add
# the routes, addresses and DNS settings the server pushed.
#
# There is nothing to compile: the payload is a POSIX shell script. netunshare.c
# in the same repository is a test harness for the project's own namespace
# tests, not part of what a client uses, so it is deliberately not built here.
#
# The install path is /etc/vpnc/vpnc-script — the last entry in openconnect's
# own search list (configure.ac:201) and the one Debian, Fedora and Arch all
# use, so a user following any openconnect documentation finds it where the
# documentation says it is.
#
# ⚠️ The source is a GitLab archive of a pinned commit. Such archives are
# regenerated by the forge and are not guaranteed byte-identical forever; the
# sha256 above is what makes that safe. If the bytes ever change the build
# fails closed at source verification rather than quietly compiling something
# else, which is the outcome we want from a pin.

do_install() {
    set -e
    install -Dm755 vpnc-script "${DESTDIR}/etc/vpnc/vpnc-script"
}
