name: libxkbcommon
version: 1.13.1
release: 1
description: Keyboard handling library
license: MIT
homepage: https://xkbcommon.org/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://github.com/lfs-book/libxkbcommon/archive/v${version}/libxkbcommon-${version}.tar.gz
  sha256: 04e3bf1ab0858a26218576d956d83ebb3ec9c583402b8807b454250be10775b1
dependencies:
  build:
  - xkeyboard-config
  - libxcb
  - wayland
  - wayland-protocols
  host: []
  runtime: []
