name: evince
version: '48.1'
release: 1
description: GNOME document viewer
license: GPL-2.0-or-later
homepage: https://wiki.gnome.org/Apps/Evince
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/evince/48/evince-${version}.tar.xz
  sha256: 7d8b9a6fa3a05d3f5b9048859027688c73a788ff6e923bc3945126884943fa10
dependencies:
  build:
  - gtk3
  - openjpeg2
  - adwaita-icon-theme
  - gsettings-desktop-schemas
  - itstool
  - libhandy1
  - libxml2
  - glib2
  - poppler
  - gnome-keyring
  - libarchive
  - libsecret
  - cairo
  - gdk-pixbuf
  host: []
  runtime: []
