name: mpg123
version: 1.33.4
release: 1
description: MPEG audio decoder
license: LGPL-2.1-or-later
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://downloads.sourceforge.net/mpg123/mpg123-${version}.tar.bz2
  sha256: 3ae8c9ff80a97bfc0e22e89fbcd74687eca4fc1db315b12607f27f01cb5a47d9
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
