name: soundtouch
version: 2.3.3
release: 1
description: Audio tempo/pitch processing library
license: LGPL-2.1-or-later
homepage: https://www.surina.net/soundtouch/
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://www.surina.net/soundtouch/soundtouch-${version}.tar.gz
  sha256: NEEDS_CHECKSUM
dependencies:
  build: []
  host: []
  runtime: []
