name: docutils
version: 0.22.4
release: 1
description: Python documentation utilities
license: Public-Domain
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${version}.tar.gz
  sha256: 4db53b1fde9abecbb74d91230d32ab626d94f6badfc575d6db9194a49df29968
dependencies:
  build: []
  host: []
  runtime: []
