name: xev
version: "1.2.6"
release: 1
description: X event monitor
license: MIT
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/app/xev-${version}.tar.xz
  sha256: 61e1c5e008ac9973aca7cdddf36e9df7410e77083b030eb04f4dc737c51807d7
dependencies:
  build:
  - libX11
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
