name: luajit
version: "20260213"
release: 1
description: Just-In-Time compiler for Lua
license: MIT
homepage: https://luajit.org/
tier: core
build_style: custom
install_func: do_install
source:
- url: https://anduin.linuxfromscratch.org/BLFS/luajit/luajit-${version}.tar.xz
  sha256: fb81576bb22649178e6c31eff041acb5ba60e408d39b01df483f39d304c95009
dependencies:
  build: []
  host: []
  runtime: []
verify_paths:
  - /usr/bin/luajit
  - /usr/bin/luajit-2.1.ROLLING
  - /usr/lib/libluajit-5.1.so
