name: editables
version: '0.5'
release: 1
description: Python editable installs helper
license: MIT
homepage: ''
tier: core
build_style: custom
install_func: do_install
source:
- url: https://files.pythonhosted.org/packages/source/e/editables/editables-${version}.tar.gz
  sha256: 309627d9b5c4adc0e668d8c6fa7bac1ba7c8c5d415c2d27f60f081f8e80d1de2
dependencies:
  build: []
  host: []
  runtime: []
verify_paths:
  - /usr/bin/hatchling
  - /usr/lib/python3.14/site-packages/editables
