name: libcdio-paranoia
version: "10.2+2.0.2"
release: 1
description: CD paranoia library from libcdio
license: GPL-3.0-or-later
homepage: https://www.gnu.org/software/libcdio/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://ftpmirror.gnu.org/libcdio/libcdio-paranoia-${version}.tar.bz2
  sha256: 186892539dedd661276014d71318c8c8f97ecb1250a86625256abd4defbf0d0c
dependencies:
  build:
  - libcdio
  host: []
  runtime: []

verify_paths:
  - /usr/lib/libcdio_paranoia.so
