name: lua
version: "5.4.8"
release: 1
description: Lightweight scripting language
license: MIT
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://www.lua.org/ftp/lua-${version}.tar.gz
  sha256: 4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae
patches:
  - file: lua-5.4.8-shared_library-1.patch
    sha256: 44324a802822f0a35d095aaad2f5f58fa7b1821ae87ae44dbcfc8a23fcd2e67e
dependencies:
  build: []
  host: []
  runtime: []
