name: iptables
version: 1.8.11
release: 1
description: Linux kernel packet filtering framework
license: GPL-2.0-or-later
homepage: https://www.netfilter.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.netfilter.org/projects/iptables/files/iptables-${version}.tar.xz
  sha256: d87303d55ef8c92bcad4dd3f978b26d272013642b029425775f5bad1009fe7b2
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-nftables
- --enable-libipq
