name: iptables
version: 1.8.12
release: 1
description: Linux kernel packet filtering framework
license: GPL-2.0-or-later
homepage: https://www.netfilter.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.netfilter.org/projects/iptables/files/iptables-${version}.tar.xz
  sha256: 8e7ee962601492de6503d171d4a948092ab18f89f111de72e3037c1f40cfb846
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-nftables
- --enable-libipq
