name: xdg-user-dirs
version: '0.19'
release: 1
description: XDG user directory management
license: GPL-2.0-or-later
homepage: https://www.freedesktop.org/wiki/Software/xdg-user-dirs/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://gitlab.freedesktop.org/xdg/xdg-user-dirs/-/archive/v${version}/xdg-user-dirs-v${version}.tar.gz
  filename: xdg-user-dirs-v${version}.tar.gz
  sha256: aa18765c6f48b6c61f2fb426656dba640920f8436a04733965146af4c9a1f5e1
dependencies:
  build:
  - libxslt
  - docbook-xml
  - docbook-xsl-nons
  host: []
  runtime: []
configure_flags:
- -Dsysconfdir=/etc
