name: gettext-tmp
version: "1.0"
release: 1
description: "GNU internationalization utilities (temporary tools)"
license: GPL-3.0-or-later
homepage: https://www.gnu.org/software/gettext/

source:
  - url: https://ftpmirror.gnu.org/gettext/gettext-${version}.tar.xz
    sha256: 71132a3fb71e68245b8f2ac4e9e97137d3e5c02f415636eb508ae607bc01add7

dependencies:
  build: []
  host:
    - ncurses
  runtime: []

tier: toolchain
target_triple: x86_64-igos-linux-gnu
build_style: custom
install_func: install
