name: strace
version: "6.14"
release: 1
description: System call tracer
license: LGPL-2.1-or-later
homepage: https://strace.io/
tier: base
build_style: autotools

source:
  - url: https://strace.io/files/${version}/strace-${version}.tar.xz
    sha256: 244f3b5c20a32854ca9b7ca7a3ee091dd3d4bd20933a171ecee8db486c77d3c9

dependencies:
  build: []
  host: []
  runtime: []

configure_flags:
  - "--prefix=/usr"
