name: sassc
version: 3.6.2
release: 1
description: SASS CSS preprocessor compiler
license: MIT
homepage: https://github.com/sass/sassc
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://github.com/sass/sassc/archive/${version}/sassc-${version}.tar.gz
  sha256: 608dc9002b45a91d11ed59e352469ecc05e4f58fc1259fc9a9f5b8f0f8348a03
dependencies:
  build: []
  host: []
  runtime: []
