name: pluggy
version: 1.5.0
release: 1
description: Plugin management framework
license: MIT
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://files.pythonhosted.org/packages/source/p/pluggy/pluggy-${version}.tar.gz
  sha256: 2cffa88e94fdc978c4c574f15f9e59b7f4201d439195c3715ca9e2486f1d0cf1
dependencies:
  build: []
  host: []
  runtime: []
