name: xdriinfo
version: 1.0.7
release: 1
description: DRI information utility
license: MIT
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/app/xdriinfo-${version}.tar.xz
  sha256: dd838bae9d2b19ddd71fe6d30ed33abc7c85e19d223e79d35600db3fa44bf734
dependencies:
  build:
  - libX11
  - mesa
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
