name: hugo
version: "0.125.4"
release: 1
description: The world’s fastest framework for building websites
license: Apache-2.0
homepage: https://gohugo.io
tier: extra
build_style: custom
install_func: do_install
source:
  - url: https://github.com/gohugoio/hugo/archive/v0.125.4/hugo-0.125.4.tar.gz
    sha256: 0000000000000000000000000000000000000000000000000000000000000000
build_artifacts:
  - name: hugo-0.125.4-vendor.tar.xz
    generated_by: go-vendor
dependencies:
  build:
  - go
  host: []
  runtime: []
