name: xkbcomp
version: 1.4.7
release: 1
description: XKB keyboard description compiler
license: MIT
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/app/xkbcomp-${version}.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - libX11
  - libxkbfile
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
