name: lynx
version: "2.9.2"
release: 1
description: Text-mode web browser
license: GPL-2.0-or-later
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://invisible-mirror.net/archives/lynx/tarballs/lynx${version}.tar.bz2
  sha256: 7374b89936d991669e101f4e97f2c9592036e1e8cdaa7bafc259a77ab6fb07ce
dependencies:
  build:
  - openssl
  - zlib
  - ncurses
  - brotli
  - gnutls
  - libarchive
  - libidn2
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --sysconfdir=/etc/lynx
- --with-zlib
- --with-bzlib
- --with-ssl
- --with-screen=ncursesw
- --enable-locale-charset
