name: libXft
version: 2.3.9
release: 1
description: X FreeType interface library
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/lib/libXft-${version}.tar.xz
  sha256: 60a25b78945ed6932635b3bb1899a517d31df7456e69867ffba27f89ff3976f5
dependencies:
  build:
  - libXrender
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
