name: libXft
version: 2.3.8
release: 1
description: X FreeType interface library
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/lib/libXft-${version}.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - libXrender
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
