name: libFS
version: "1.0.10"
release: 1
description: X Font Service client library
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/lib/libFS-${version}.tar.xz
  sha256: 9babbd3c86069c98563da044045fdc0ece4ec0c93dcdd2c68aa74eb34b4f3b77
dependencies:
  build:
  - xtrans
  - xorgproto
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
