name: linux-headers
version: "6.18.10"
release: 1
description: "Linux kernel API headers"
license: GPL-2.0-only
homepage: https://www.kernel.org/

source:
  - url: https://www.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.xz
    sha256: d6d377161741ada2fab28eed69143277634a2aeb5e3883e50c031588ede48ede

dependencies:
  build: []
  host: []
  runtime: []

tier: toolchain
build_style: custom
