name: libcloudproviders
version: 0.3.6
release: 1
description: Cloud storage integration library
license: LGPL-3.0-or-later
homepage: ''
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/libcloudproviders/0.3/libcloudproviders-${version}.tar.xz
  sha256: 3b75110b3a4fdef4c5c5a440e48701fe054d2ae061d156c89136bb5ba05e74b7
dependencies:
  build:
  - vala
  host: []
  runtime: []
