name: spirv-tools
version: "1.4.341.0"
release: 1
description: SPIR-V tools
license: Apache-2.0
homepage: ''
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://github.com/KhronosGroup/SPIRV-Tools/archive/vulkan-sdk-${version}/spirv-tools-${version}.tar.gz
  sha256: 15bfb678138cdf9cd1480dfb952547bbb66b763a735b6d5582578572f5c2e6f9
dependencies:
  build:
  - spirv-headers
  - cmake
  host: []
  runtime: []
verify_paths:
  - /usr/bin/spirv-as
  - /usr/lib/libSPIRV-Tools-diff.so
