name: spirv-tools
version: 1.3.290.0
release: 1
description: SPIR-V tools
license: Apache-2.0
homepage: ''
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://github.com/KhronosGroup/SPIRV-Tools/archive/vulkan-sdk-${version}/spirv-tools-${version}.tar.gz
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - spirv-headers
  host: []
  runtime: []
