name: pycairo
version: "1.29.0"
release: 1
description: Python bindings for Cairo
license: LGPL-2.1-or-later
homepage: https://pycairo.readthedocs.io/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://github.com/pygobject/pycairo/releases/download/v${version}/pycairo-${version}.tar.gz
  sha256: f3f7fde97325cae80224c09f12564ef58d0d0f655da0e3b040f5807bd5bd3142
dependencies:
  build:
  - cairo
  - docbook-xsl-nons
  host: []
  runtime: []
