name: pycairo
version: 1.27.0
release: 1
description: Python bindings for Cairo
license: LGPL-2.1-or-later
homepage: https://pycairo.readthedocs.io/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://github.com/pygobject/pycairo/releases/download/v${version}/pycairo-${version}.tar.gz
  sha256: 5cb21e7a00a2afcafea7f14390235be33497a2cce53a98a19389492a60628430
dependencies:
  build:
  - cairo
  host: []
  runtime: []
