name: libXvMC
version: 1.0.14
release: 1
description: X Video Motion Compensation library
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/lib/libXvMC-${version}.tar.xz
  sha256: e4be9eb6b6bafdbbf81f47f7163047215376e45e2dc786d0ea6181c930725ed9
dependencies:
  build:
  - libXv
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
