name: libtasn1
version: 4.21.0
release: 1
description: ASN.1 library used by GnuTLS and p11-kit
license: LGPL-2.1-or-later
homepage: https://www.gnu.org/software/libtasn1/
tier: core
build_style: autotools

source:
  - url: https://ftpmirror.gnu.org/libtasn1/libtasn1-${version}.tar.gz
    sha256: 1d8a444a223cc5464240777346e125de51d8e6abf0b8bac742ac84609167dc87

dependencies:
  build: []
  host: []
  runtime: []

configure_flags:
  - "--prefix=/usr"
  - "--disable-static"
