name: gdk-pixbuf
version: "2.44.5"
release: 1
description: Image loading library for GTK
license: LGPL-2.1-or-later
homepage: https://wiki.gnome.org/Projects/GdkPixbuf
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://download.gnome.org/sources/gdk-pixbuf/2.44/gdk-pixbuf-${version}.tar.xz
  sha256: 69b93e09139b80c0ee661503d60deb5a5874a31772b5184b9cd5462a4100ab68
dependencies:
  build:
  - shared-mime-info
  - libjpeg-turbo
  - libpng
  - libtiff
  host: []
  runtime: []
