name: tecla
version: '49.0'
release: 1
description: GNOME on-screen keyboard
license: GPL-2.0-or-later
homepage: ''
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/tecla/49/tecla-${version}.tar.xz
  sha256: 2ca424e402baf60cd6b13777703b701ebb1faf8f3d0f2f971144d823f651249f
dependencies:
  build:
  - libadwaita1
  - libxkbcommon
  - gtk4
  host: []
  runtime: []
