name: networkmanager
version: 1.56.0
release: 1
description: Network connection manager
license: GPL-2.0-or-later
homepage: https://networkmanager.dev/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/NetworkManager/1.56/NetworkManager-${version}.tar.xz
  sha256: 6e95d3011ecc51a72fec8b2a8e5b06b4e134c2b2cfe513bfce42d9029c6c8dd1
dependencies:
  build:
  - iptables
  - libndp
  - libnl
  - polkit
  - pygobject3
  - vala
  - wpa_supplicant
  host: []
  runtime: []
