name: libportal
version: "0.9.1"
release: 1
description: Flatpak portal library
license: LGPL-3.0-or-later
homepage: https://github.com/flatpak/libportal
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://github.com/flatpak/libportal/releases/download/${version}/libportal-${version}.tar.xz
  sha256: de801ee349ed3c255a9af3c01b1a401fab5b3fc1c35eb2fd7dfb35d4b8194d7f
patches:
  - file: libportal-0.9.1-qt6.9_fixes-1.patch
    sha256: 52fa427c47cf92edcb4f3d800e6f1232dbcb6251dc897954c96ec1db8668d271
dependencies:
  build:
  - gtk3
  - gtk4
  - glib2
  - vala
  host: []
  runtime: []
verify_paths:
  - /usr/lib/libportal.so
