name: wayland
version: 1.23.1
release: 1
description: Wayland display server protocol
license: MIT
homepage: https://wayland.freedesktop.org/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://gitlab.freedesktop.org/wayland/wayland/-/releases/${version}/downloads/wayland-${version}.tar.xz
  sha256: 864fb2a8399e2d0ec39d56e9d9b753c093775beadc6022ce81f441929a81e5ed
dependencies:
  build:
  - libxml2
  host: []
  runtime: []
