name: lazygit
version: "0.41.0"
release: 1
description: Simple terminal UI for git commands
license: MIT
homepage: https://github.com/jesseduffield/lazygit
tier: extra
build_style: custom
install_func: do_install
source:
  - url: https://github.com/jesseduffield/lazygit/archive/v0.41.0/lazygit-0.41.0.tar.gz
    sha256: 0000000000000000000000000000000000000000000000000000000000000000
build_artifacts:
  - name: lazygit-0.41.0-vendor.tar.xz
    generated_by: go-vendor
dependencies:
  build:
  - go
  host: []
  runtime: []
