name: libsigcpp3
version: 3.6.0
release: 1
description: Typesafe callback system for C++
license: LGPL-3.0-or-later
homepage: https://libsigcplusplus.github.io/libsigcplusplus/
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/libsigc++/3.6/libsigc++-${version}.tar.xz
  sha256: c3d23b37dfd6e39f2e09f091b77b1541fbfa17c4f0b6bf5c89baef7229080e17
dependencies:
  build:
  - boost
  - libxslt
  host: []
  runtime: []
