name: util-macros
version: 1.20.2
release: 1
description: Xorg autotools macros
license: MIT
homepage: https://www.x.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/util/util-macros-${version}.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
