name: celluloid
version: "0.27"
release: 1
description: GTK4 frontend for mpv media player
license: GPL-3.0-or-later
homepage: https://celluloid-player.github.io/
tier: extra
build_style: meson
install_func: do_install
source:
- url: https://github.com/celluloid-player/celluloid/releases/download/v${version}/celluloid-${version}.tar.xz
  sha256: FIXME
dependencies:
  build:
  - mpv
  - gtk4
  - libadwaita
  - glib2
  host: []
  runtime: []
