name: gnutls
version: 3.8.12
release: 1
description: GNU TLS library
license: LGPL-2.1-or-later
homepage: https://gnutls.org/
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-${version}.tar.xz
  sha256: a7b341421bfd459acf7a374ca4af3b9e06608dcd7bd792b2bf470bea012b8e51
dependencies:
  build:
  - libtasn1
  - libunistring
  - make-ca
  - nettle
  - p11-kit
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-static
- '--with-default-trust-store-pkcs11=pkcs11:'
