name: dav1d
version: 1.5.0
release: 1
description: AV1 video decoder
license: BSD-2-Clause
homepage: https://code.videolan.org/videolan/dav1d
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://code.videolan.org/videolan/dav1d/-/archive/${version}/dav1d-${version}.tar.bz2
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - nasm
  host: []
  runtime: []
