name: docbook-xml
version: '4.5'
release: 1
description: DocBook XML DTD
license: OASIS
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://archive.docbook.org/xml/${version}/docbook-xml-${version}.zip
  sha256: 4e4e037a2b83c98c6c94818390d4bdd3f6e10f6ec62dd79188594e26190dc7b4
dependencies:
  build: []
  host: []
  runtime: []
