name: gnome-keyring
version: '48.0'
release: 1
description: GNOME password and secret storage
license: GPL-2.0-or-later
homepage: https://wiki.gnome.org/Projects/GnomeKeyring
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://download.gnome.org/sources/gnome-keyring/48/gnome-keyring-${version}.tar.xz
  sha256: f20518c920e9ea3f9c9b8b44be8c50d8d7feecd0dd5624960f77bd2ca4fbeb9d
dependencies:
  build:
  - gcr
  - linux-pam
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --with-pam-dir=/usr/lib/security
