name: at
version: 3.2.5
release: 1
description: Job scheduling commands (at, batch, atq, atrm)
license: GPL-2.0-or-later
tier: base
build_style: custom
install_func: do_install

source:
  - url: https://anduin.linuxfromscratch.org/BLFS/at/at_${version}.orig.tar.gz
    sha256: bb066b389d7c9bb9d84a35738032b85c30cba7d949f758192adc72c9477fd3b8

dependencies:
  build:
    - exim
    - linux-pam
  host: []
  runtime:
    - exim
