#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
# scripts/anchor-tracker.sh — advance the TRACKER anchor to the public repo's
# current HEAD + commit + push the private repo. Invoked by the public repo's
# pre-push gate when an out-of-date anchor is detected.
#
# Workflow:
#   1. Read public-repo's about-to-be-pushed HEAD (passed as $1, or auto-detect)
#   2. Read TRACKER.md's current ANCHOR line
#   3. If they match, no-op (push proceeds)
#   4. Otherwise, rewrite the ANCHOR line in TRACKER.md to point at HEAD
#   5. git add + commit (conventional-commit-formatted) + push private repo
#   6. Public repo's pre-push gate then re-verifies + allows the public push
#
# This is the anti-drift enforcement: every public-repo push to master
# advances the TRACKER anchor in lock-step. Drift becomes mechanically
# impossible at the push boundary.
#
# Operator workflow note: substantive TRACKER content updates (STATE banner
# refresh, new entries, status changes) are handled manually and happen
# as separate manual edits + commits to the private repo. This script only
# advances the ANCHOR line — the bookkeeping piece, not the content piece.
# Operator should still update STATE banner + relevant entries when state
# materially changes; this script ensures the anchor-bookkeeping always
# tracks the public-repo HEAD without operator action.
#
# Usage:
#   scripts/anchor-tracker.sh                    # auto-detect HEAD
#   scripts/anchor-tracker.sh <SHA>              # anchor to specific SHA
#
# Exit codes:
#   0 — anchor advanced (or already current; no-op)
#   1 — anchor advancement failed (network, conflict, etc.)
#   2 — script invocation error

set -euo pipefail

# Public-repo path defaults to this script's parent dir (anchor-tracker.sh
# lives in scripts/, so parent is the repo root). Override via env for
# non-standard layouts.
SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
PUBLIC_REPO="${INTERGENOS_PUBLIC_REPO:-$(cd "$SCRIPT_DIR/.." && pwd)}"

# Private-repo discovery chain (first match wins):
#   1. $INTERGENOS_PRIVATE_REPO env var (explicit override)
#   2. $HOME/intergenos-private (common layout — home-dir sibling)
#   3. $PUBLIC_REPO/../intergenos-private (sibling-of-public-repo layout)
# Fails with actionable error if none resolve to a git repo.
if [ -n "${INTERGENOS_PRIVATE_REPO:-}" ]; then
    PRIVATE_REPO="$INTERGENOS_PRIVATE_REPO"
elif [ -d "${HOME:-/nonexistent}/intergenos-private/.git" ]; then
    PRIVATE_REPO="$HOME/intergenos-private"
elif [ -d "$PUBLIC_REPO/../intergenos-private/.git" ]; then
    PRIVATE_REPO="$(cd "$PUBLIC_REPO/.." && pwd)/intergenos-private"
else
    echo "ERROR: private repo not found via any of:" >&2
    echo "  - \$INTERGENOS_PRIVATE_REPO env var" >&2
    echo "  - \$HOME/intergenos-private" >&2
    echo "  - \$PUBLIC_REPO/../intergenos-private" >&2
    echo "  Set INTERGENOS_PRIVATE_REPO to the clone path of InterGenJLU/intergenos-private" >&2
    exit 2
fi
TRACKER="$PRIVATE_REPO/TRACKER.md"

[ -d "$PUBLIC_REPO/.git" ] || { echo "ERROR: PUBLIC_REPO ($PUBLIC_REPO) not a git repo" >&2; exit 2; }
[ -d "$PRIVATE_REPO/.git" ] || { echo "ERROR: PRIVATE_REPO ($PRIVATE_REPO) not a git repo" >&2; exit 2; }
[ -f "$TRACKER" ] || { echo "ERROR: TRACKER not found at $TRACKER" >&2; exit 2; }

# Determine target SHA.
if [ $# -ge 1 ]; then
    TARGET_SHA="$1"
else
    TARGET_SHA=$(git -C "$PUBLIC_REPO" rev-parse HEAD)
fi
TARGET_SHORT=$(git -C "$PUBLIC_REPO" rev-parse --short=8 "$TARGET_SHA")

# Read current anchor.
CURRENT_ANCHOR=$(grep -oE '<!-- ANCHOR: public-master HEAD [a-f0-9]+ -->' "$TRACKER" | head -1 | awk '{print $5}' || true)

if [ -z "$CURRENT_ANCHOR" ]; then
    echo "[anchor-tracker] no ANCHOR line in TRACKER; cannot proceed without bootstrap" >&2
    exit 1
fi

if [ "$CURRENT_ANCHOR" = "$TARGET_SHORT" ] || [ "$CURRENT_ANCHOR" = "$TARGET_SHA" ]; then
    echo "[anchor-tracker] anchor already at $CURRENT_ANCHOR; no-op"
    exit 0
fi

echo "[anchor-tracker] advancing anchor: $CURRENT_ANCHOR → $TARGET_SHORT"

# Rewrite the ANCHOR line in place.
python3 - "$TRACKER" "$TARGET_SHORT" <<'PY'
import sys, re, pathlib
path = pathlib.Path(sys.argv[1])
new_sha = sys.argv[2]
text = path.read_text()
new_text, n = re.subn(
    r'<!-- ANCHOR: public-master HEAD [a-f0-9]+ -->',
    f'<!-- ANCHOR: public-master HEAD {new_sha} -->',
    text,
    count=1,
)
if n != 1:
    sys.stderr.write(f"ERROR: expected exactly 1 ANCHOR line, found {n}\n")
    sys.exit(1)
path.write_text(new_text)
PY

# Stage + commit + push private repo.
cd "$PRIVATE_REPO"
git add TRACKER.md
git commit -m "$(cat <<EOF
chore(anchor): advance TRACKER anchor to public-master \`${TARGET_SHORT}\`

Auto-generated by scripts/anchor-tracker.sh as part of the public-repo
pre-push anti-drift discipline. Anchor advances from \`${CURRENT_ANCHOR}\` →
\`${TARGET_SHORT}\` to track the public-repo HEAD being pushed.

This commit is bookkeeping only — substantive TRACKER content updates
(STATE banner refresh, entry changes) land separately as manually-authored
commits.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>
EOF
)" >/dev/null

git push >/dev/null 2>&1 || {
    echo "[anchor-tracker] ERROR: private-repo push failed" >&2
    echo "[anchor-tracker] anchor committed locally at $(git -C "$PRIVATE_REPO" rev-parse --short HEAD) but not pushed" >&2
    exit 1
}

echo "[anchor-tracker] anchor advanced + pushed: $TARGET_SHORT"
exit 0
