#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
"""Generate THIRD-PARTY-NOTICES.md from the per-package license inventory.

Walks every packages/<tier>/<name>/package.yml, extracts the SPDX
license expression (and payload_license, if present), and emits a
single aggregated THIRD-PARTY-NOTICES.md at the repository root.

This is the IDX (index) artifact — it tells anyone receiving InterGenOS
which packages it ships and what license each one carries. The full
license text of each package is shipped on installed systems under
/usr/share/licenses/<package>/LICENSE (per docs/governance/license-policy.md
§5, which is also K21 follow-on work — see the bundle_license build
hook still pending implementation).

Closes audit P-004 (no THIRD-PARTY-NOTICES file) as the human-readable
index. The on-disk per-package LICENSE bundling at install time is the
mechanism's other half.

Usage:
    python3 scripts/generate-third-party-notices.py
        → writes ./THIRD-PARTY-NOTICES.md (overwriting if present)
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("ERROR: PyYAML not available; install python3-yaml.\n")
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGES_DIR = REPO_ROOT / "packages"
OUTPUT = REPO_ROOT / "THIRD-PARTY-NOTICES.md"

TIERS = ("toolchain", "core", "base", "desktop", "extra", "ai")

HEADER = """# InterGenOS — Third-Party Notices

This file aggregates the upstream attribution for every package
InterGenOS builds and ships. It is generated mechanically from the
per-package `package.yml` inventory by
`scripts/generate-third-party-notices.py`; do not edit by hand —
re-run the generator after package additions or license-field
changes.

Each entry lists the package name, the SPDX license expression
declared by the package's `package.yml`, a one-line description,
and the upstream homepage where applicable. For helper packages
that fetch a proprietary payload at install time, the
`payload_license:` field is shown separately — that is the EULA the
user accepts when running the helper, distinct from the GPL-3
license of the helper script itself.

The full upstream LICENSE text of each shipped package is bundled
under `/usr/share/licenses/<package>/` on installed systems, per
the source-availability commitment in [SOURCES.md](SOURCES.md) and
the license policy at
[docs/governance/license-policy.md](docs/governance/license-policy.md).

The aggregate ships on the installed system at
`/usr/share/doc/intergenos/THIRD-PARTY-NOTICES` for offline access.

---

## Coverage summary

"""

PROVENANCE = """
---

## Provenance

Generated by `scripts/generate-third-party-notices.py` from
`packages/*/*/package.yml`. The script is the source of truth; the
present file is its output, regenerated on each package-tree
change.

This file closes the human-readable index portion of audit finding
**P-004** (High: no `THIRD-PARTY-NOTICES` / `NOTICE` / `legal/`
directory exists). The per-package LICENSE-text bundling at
`/usr/share/licenses/<package>/` on installed systems — the other
half of P-004's remediation — lands as the `bundle_license` build
hook tracked at TRACKER K21.

License of this file: **CC0-1.0** (public domain dedication).
"""


def load_package(yml_path: Path) -> dict | None:
    try:
        data = yaml.safe_load(yml_path.read_text())
    except (yaml.YAMLError, OSError) as e:
        sys.stderr.write(f"WARN: failed to parse {yml_path}: {e}\n")
        return None
    if not isinstance(data, dict):
        return None
    return data


def render_entry(pkg: dict) -> str:
    name = pkg.get("name", "?")
    version = pkg.get("version", "?")
    license_expr = pkg.get("license", "?")
    description = pkg.get("description", "")
    homepage = pkg.get("homepage", "")
    payload_license = pkg.get("payload_license")

    lines = [f"### {name} ({version})"]
    if description:
        lines.append("")
        lines.append(description)
    lines.append("")
    lines.append(f"- License: `{license_expr}`")
    if payload_license:
        lines.append(f"- Payload license: `{payload_license}`")
    if homepage:
        lines.append(f"- Homepage: {homepage}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not PACKAGES_DIR.is_dir():
        sys.stderr.write(f"ERROR: {PACKAGES_DIR} not found\n")
        return 1

    tier_packages: dict[str, list[dict]] = defaultdict(list)
    license_counts: dict[str, int] = defaultdict(int)
    total = 0
    payload_helpers: list[dict] = []

    for tier in TIERS:
        tier_dir = PACKAGES_DIR / tier
        if not tier_dir.is_dir():
            continue
        for pkg_dir in sorted(tier_dir.iterdir()):
            if not pkg_dir.is_dir():
                continue
            yml = pkg_dir / "package.yml"
            if not yml.exists():
                continue
            pkg = load_package(yml)
            if pkg is None:
                continue
            tier_packages[tier].append(pkg)
            total += 1
            lic = pkg.get("license", "?")
            license_counts[lic] += 1
            if pkg.get("payload_license"):
                payload_helpers.append(pkg)

    # Compose
    parts = [HEADER]
    parts.append(f"**Total packages:** {total}\n")
    parts.append("**Distribution by tier:**\n")
    parts.append("| Tier | Count |")
    parts.append("|---|---:|")
    for tier in TIERS:
        if tier in tier_packages:
            parts.append(f"| {tier} | {len(tier_packages[tier])} |")
    parts.append("")
    parts.append("**Distribution by license (top 20):**\n")
    parts.append("| License | Count |")
    parts.append("|---|---:|")
    for lic, count in sorted(
        license_counts.items(), key=lambda x: -x[1]
    )[:20]:
        parts.append(f"| `{lic}` | {count} |")
    parts.append("")

    if payload_helpers:
        parts.append("**Helpers with proprietary payloads:**\n")
        parts.append(
            "| Helper | Helper license | Payload license (user-accepted) |"
        )
        parts.append("|---|---|---|")
        for h in payload_helpers:
            parts.append(
                f"| {h.get('name', '?')} "
                f"| `{h.get('license', '?')}` "
                f"| `{h.get('payload_license', '?')}` |"
            )
        parts.append("")
        parts.append(
            "See [`docs/legal/payload-licenses.md`]"
            "(docs/legal/payload-licenses.md) for each payload license's "
            "canonical URL + last-checked date.\n"
        )

    parts.append("---\n")
    parts.append("## Package entries by tier\n")

    for tier in TIERS:
        if tier not in tier_packages:
            continue
        parts.append(f"### Tier: `{tier}`\n")
        for pkg in sorted(tier_packages[tier], key=lambda p: p.get("name", "")):
            parts.append(render_entry(pkg))
        parts.append("")

    parts.append(PROVENANCE)

    OUTPUT.write_text("\n".join(parts) + "\n")
    print(f"Wrote {OUTPUT} ({total} packages across "
          f"{len(tier_packages)} tiers, {len(license_counts)} distinct "
          f"licenses).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
