name: cdparanoia
version: '10.2'
release: 1
description: CD audio extraction tool
license: GPL-2.0-or-later
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://downloads.xiph.org/releases/cdparanoia/cdparanoia-III-${version}.src.tgz
  sha256: 005db45ef4ee017f5c32ec124f913a0546e77014266c6a1c50df902a55fe64df
patches:
  - cdparanoia-III-10.2-gcc_fixes-1.patch
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
