name: atop
version: "2.11.0"
release: 1
description: Advanced system and process monitor
license: GPL-2.0-or-later
homepage: https://www.atoptool.nl/
tier: base
build_style: custom
install_func: do_install

source:
  - url: https://www.atoptool.nl/download/atop-${version}.tar.gz
    sha256: 9b94c666602efff7bf402ecce706c347f38c39cb63498f9d39626861e5646e20

dependencies:
  build: []
  host: []
  runtime: []
