name: nss
version: "3.121"
release: 1
description: Network Security Services
license: MPL-2.0
homepage: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
tier: core
build_style: custom
install_func: do_install

source:
  - url: https://archive.mozilla.org/pub/security/nss/releases/NSS_3_121_RTM/src/nss-${version}.tar.gz
    sha256: cb3a8f8781bea78b7b8edd3afb7a2cb58e4881bb0160d189a39b98216ba7632e

dependencies:
  build:
    - nspr
  host: []
  runtime:
    - p11-kit

patches:
  - file: nss-standalone-1.patch
    sha256: 87bb1af0b11fd41311b9899187f6e4b3fca9940651123c7bc836ec7497d2da84