name: libjpeg-turbo
version: 3.1.0
release: 1
description: High-speed JPEG compression/decompression library
license: IJG
homepage: https://libjpeg-turbo.org/
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${version}/libjpeg-turbo-${version}.tar.gz
  sha256: 9564c72b1dfd1d6fe6274c5f95a8d989b59854575d4bbee44ade7bc17aa9bc93
dependencies:
  build:
  - nasm
  host: []
  runtime: []
