name: expect
version: 5.45.4
release: 1
description: Tool for automating interactive applications
license: Public-Domain
homepage: https://core.tcl.tk/expect/
tier: core
build_style: custom
install_func: do_install
source:
- url: https://prdownloads.sourceforge.net/expect/expect${version}.tar.gz
  sha256: 49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34
dependencies:
  build: []
  host:
  - tcl
  runtime: []
