name: hwdata
version: '0.404'
release: 1
description: Hardware identification and configuration data
license: GPL-2.0-or-later
homepage: https://github.com/vcrhonek/hwdata
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://github.com/vcrhonek/hwdata/archive/v${version}/hwdata-${version}.tar.gz
  sha256: 5c14fc99bf193faad1ccc267ccfff14ee4e4550a582b17a76aec72178539f837
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
- --disable-blacklist
