name: giflib
version: 5.2.2
release: 1
description: GIF image library
license: MIT
homepage: https://giflib.sourceforge.net/
tier: desktop
build_style: make
install_func: do_install
source:
- url: https://sourceforge.net/projects/giflib/files/giflib-${version}.tar.gz
  sha256: be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb
patches:
  - giflib-5.2.2-upstream_fixes-1.patch
  - giflib-5.2.2-security_fixes-1.patch
dependencies:
  build: []
  host: []
  runtime: []
