name: fcron
version: "3.4.0"
release: 1
description: Periodical command scheduler
license: GPL-2.0-or-later
homepage: http://fcron.free.fr/
tier: base
build_style: custom
install_func: do_install

source:
  - url: http://fcron.free.fr/archives/fcron-${version}.src.tar.gz
    sha256: f4e7fc553cdd70ff4b3b6ac9138b3b7cffab9198b8c266d97af0a87506e0e1b5

dependencies:
  build:
  - linux-pam
  - vim
  host: []
  runtime: []
