#!/bin/bash
# bottom 0.12.3 — cross-platform graphical process/system monitor
# Upstream: https://github.com/ClementTsang/bottom
# License: MIT
# Binary name: btm (not bottom)

configure() {
    set -e
    tar xf "$IGOS_SOURCES/bottom-$PKG_VERSION-vendor.tar.xz" --strip-components=1
}

build() {
    set -e
    # build.rs generates shell completions to target/tmp/bottom/completion/ by
    # default; pin COMPLETION_DIR so we know where to find them at install time.
    export COMPLETION_DIR="${PWD}/target/release/completion"
    cargo build --release --frozen --offline
}

do_install() {
    set -e
    install -Dm755 target/release/btm "$DESTDIR/usr/bin/btm"

    # Install bash/zsh/fish completions generated by build.rs into
    # ${COMPLETION_DIR}. bottom 0.12.3 does NOT ship a build.rs-generated
    # man page (upstream uses an out-of-band Python+pandoc script for that;
    # not generated as part of `cargo build`). Skip man for now.
    local cdir="target/release/completion"
    if [ ! -d "$cdir" ]; then
        echo "ERROR: bottom completion dir not found at $cdir" >&2
        exit 1
    fi

    install -Dm644 "$cdir/btm.bash" \
        "$DESTDIR/usr/share/bash-completion/completions/btm"
    install -Dm644 "$cdir/btm.fish" \
        "$DESTDIR/usr/share/fish/vendor_completions.d/btm.fish"
    install -Dm644 "$cdir/_btm" \
        "$DESTDIR/usr/share/zsh/site-functions/_btm"
}
