name: bottom
version: "0.9.6"
release: 1
description: Yet another cross-platform graphical process/system monitor
license: MIT
homepage: https://github.com/ClementTsang/bottom
tier: extra
build_style: custom
install_func: do_install
source:
  - url: https://github.com/ClementTsang/bottom/archive/0.9.6/bottom-0.9.6.tar.gz
    sha256: 0000000000000000000000000000000000000000000000000000000000000000
build_artifacts:
  - name: bottom-0.9.6-vendor.tar.xz
    generated_by: cargo-vendor
dependencies:
  build:
  - rust
  host: []
  runtime: []
