name: atkmm
version: "2.28.4"
release: 1
description: C++ interface to the ATK accessibility toolkit (GTK3 version)
license: LGPL-2.1-or-later
homepage: https://www.gtkmm.org/
tier: extra
build_style: meson
install_func: do_install
source:
- url: https://download.gnome.org/sources/atkmm/2.28/atkmm-${version}.tar.xz
  sha256: FIXME
dependencies:
  build:
  - at-spi2-core
  - glibmm
  host: []
  runtime: []
