name: docbook-xsl-nons
version: 1.79.2
release: 1
description: DocBook XSL stylesheets
license: MIT
homepage: ''
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://github.com/docbook/xslt10-stylesheets/releases/download/release%2F${version}/docbook-xsl-nons-${version}.tar.bz2
  sha256: ee8b9eca0b7a8f89075832a2da7534bce8c5478fc8fc2676f512d5d87d832102
patches:
  - docbook-xsl-nons-1.79.2-stack_fix-1.patch
dependencies:
  build:
  - docbook-xml
  host: []
  runtime: []
