name: spidermonkey
version: 128.6.0
release: 1
description: Mozilla SpiderMonkey JavaScript engine
license: MPL-2.0
homepage: https://spidermonkey.dev/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://archive.mozilla.org/pub/firefox/releases/${version}esr/source/firefox-${version}esr.source.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - cbindgen
  - llvm
  - rust
  - icu
  host: []
  runtime: []
