#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2015-2016, 2026 InterGenJLU
#
# cracklib 2.10.3 — Password checking library
# BLFS 13.0

configure() {
    set -e
    ./configure --prefix=/usr \
                --disable-static \
                --with-default-dict=/usr/lib/cracklib/pw_dict
}

build() {
    set -e
    make -j${IGOS_JOBS}
}

do_install() {
    set -e
    make DESTDIR="$DESTDIR" install

    # Owned home for the generated dictionary (hook-contract wave); the
    # dict itself is generated by post_install on the target.
    install -dm755 "${DESTDIR}/usr/lib/cracklib"
}

post_install() {
    set -e
    # Dictionary GENERATION is legitimate maintenance (machine-state, like an
    # icon cache: depends on the target's words files / hostname fallback) and
    # stays here per the hook contract. The bare directory is owned payload and
    # is staged in do_install (hook-contract wave).

    # Use the words file from the system if available, otherwise create minimal one
    if [ -f /usr/share/dict/words ]; then
        create-cracklib-dict /usr/share/dict/words
    else
        # Create a minimal word list
        echo "password" > /tmp/cracklib-words
        echo "$(hostname)" >> /tmp/cracklib-words
        create-cracklib-dict /tmp/cracklib-words
        rm -f /tmp/cracklib-words
    fi
}
