name: iso-codes
version: 4.17.0
release: 1
description: Country, language, and currency code lists
license: LGPL-2.1-or-later
homepage: https://salsa.debian.org/iso-codes-team/iso-codes
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${version}/iso-codes-v${version}.tar.gz
  sha256: dd5ca13db77ec6dd1cc25f5c0184290a870ec1fed245d8e39a04ff34f59076c3
dependencies:
  build: []
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
