name: harfbuzz
version: "12.3.2"
release: 1
description: Text shaping engine
license: MIT
homepage: https://harfbuzz.github.io/
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://github.com/harfbuzz/harfbuzz/releases/download/${version}/harfbuzz-${version}.tar.xz
  sha256: 6f6db164359a2da5a84ef826615b448b33e6306067ad829d85d5b0bf936f1bb8
dependencies:
  build:
  - freetype2-pass1
  - graphite2
  - icu
  host: []
  runtime: []
