name: vte
version: 0.82.3
release: 1
description: Virtual Terminal Emulator widget
license: LGPL-2.1-or-later
homepage: https://wiki.gnome.org/Apps/Terminal/VTE
tier: desktop
build_style: custom
install_func: do_install
source:
- url: https://download.gnome.org/sources/vte/0.82/vte-${version}.tar.xz
  sha256: 6dc6278f6fee30d07d1a03e2ba3335b1ea4e8d2956ceb59d861943115d930a85
dependencies:
  build:
  - gtk3
  - gtk4
  - icu
  - gnutls
  - fribidi
  - vala
  host: []
  runtime: []
