name: libqmi
version: 1.34.0
release: 1
description: QMI protocol library
license: LGPL-2.1-or-later
homepage: ''
tier: desktop
build_style: meson
install_func: do_install
source:
- url: https://www.freedesktop.org/software/libqmi/libqmi-${version}.tar.xz
  sha256: NEEDS_CHECKSUM
dependencies:
  build:
  - libgudev
  - libmbim
  host: []
  runtime: []
