name: qpdf
version: "12.3.2"
release: 1
description: PDF transformation utility
license: Apache-2.0
homepage: ''
tier: desktop
build_style: cmake
install_func: do_install
source:
- url: https://github.com/qpdf/qpdf/releases/download/v${version}/qpdf-${version}.tar.gz
  sha256: 6cba2f9f2cd887d905faeb99e0e51a307b217920d1bbf3e9cfbb2e8178a2deda
dependencies:
  build:
  - libjpeg-turbo
  host: []
  runtime: []
