name: perl-core
version: "5.42.0"
release: 1
description: Practical Extraction and Report Language
license: Artistic-1.0-Perl OR GPL-1.0-or-later
source:
- url: https://www.cpan.org/src/5.0/perl-${version}.tar.xz
  sha256: 73cf6cc1ea2b2b1c110a18c14bbbc73a362073003893ffcedc26d22ebdbdd0c3
dependencies:
  build: []
  host:
  - gdbm
  - libxcrypt
  runtime: []
tier: core
build_style: custom
verify_paths:
  - /usr/bin/perl
  - /usr/bin/corelist
  - /usr/lib/here
