name: sd
version: "1.0.0"
release: 1
description: Intuitive find & replace CLI
license: MIT
homepage: https://github.com/chmln/sd
tier: extra
build_style: custom
install_func: do_install
source:
  - url: https://github.com/chmln/sd/archive/v1.0.0/sd-1.0.0.tar.gz
    sha256: 0000000000000000000000000000000000000000000000000000000000000000
build_artifacts:
  - name: sd-1.0.0-vendor.tar.xz
    generated_by: cargo-vendor
dependencies:
  build:
  - rust
  host: []
  runtime: []
