name: smproxy
version: 1.0.7
release: 1
description: Session Manager Proxy
license: MIT
homepage: ''
tier: desktop
build_style: autotools
install_func: do_install
source:
- url: https://www.x.org/pub/individual/app/smproxy-${version}.tar.xz
  sha256: 4aa99237cc9dab7d87ce9bc7cca4116674a853b5f08dfe3f9db1bb2b2cf9f305
dependencies:
  build:
  - libSM
  - libXt
  host: []
  runtime: []
configure_flags:
- --prefix=/usr
