name: libatomic_ops
version: "7.10.0"
release: 1
description: Atomic memory update operations library
license: MIT
homepage: https://github.com/bdwgc/libatomic_ops
tier: extra
build_style: custom
install_func: do_install
source:
- url: https://github.com/bdwgc/libatomic_ops/releases/download/v${version}/libatomic_ops-${version}.tar.gz
  sha256: 0db3ebff755db170f65e74a64ec4511812e9ee3185c232eeffeacd274190dfb0
dependencies:
  build: []
  host: []
  runtime: []
verify_paths:
  - /usr/lib/libatomic_ops.so
